/** Presents explicit local connection safety/retirement controls without auth, transport or storage ownership. @module messaging-connection-lifecycle */
import { useId } from "react";
import { Button, Checkbox, Label, Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "beez-ui";
import type { MessagingConnectionSuspensionInput } from "@/src/modules/messaging/domain/repositories/messaging-connection-lifecycle";
import { MESSAGING_CONNECTION_SECURITY_REASON } from "@/src/modules/messaging/constants/messaging-connection-security";
import { MESSAGING_CONNECTION_LABEL } from "@/src/modules/messaging/constants/messaging-connection-presentation";
import { MESSAGING_LIFECYCLE_BROWSER_PATH } from "@/src/modules/messaging/constants/messaging-lifecycle-browser";
import styles from "./styles.module.scss";

/** Own current view facts contain no credential, provider IDs or recipient information. */
export type MessagingLifecycleConnectionView={id:string;name:string;version:number;state:keyof typeof MESSAGING_CONNECTION_LABEL;selected:boolean;candidate:boolean};
/** The route container supplies current resource state, renewed confirmation and every action callback. */
export type MessagingConnectionLifecycleProps={connections:readonly MessagingLifecycleConnectionView[];targetId:string;retiring:boolean;reason:MessagingConnectionSuspensionInput["reason"];confirmed:boolean;busy:boolean;canAct:boolean;onTarget:(id:string)=>void;onRetiring:(retiring:boolean)=>void;onReason:(reason:MessagingConnectionSuspensionInput["reason"])=>void;onConfirm:(confirmed:boolean)=>void;onAct:()=>void;onReauthenticate:()=>void;message?:{kind:"status"|"alert";text:string}|null};

/** @param props - Guarded current metadata and callbacks only. @returns Accessible local safety/retirement confirmation and explicit impact. */
export function MessagingConnectionLifecycle(props:MessagingConnectionLifecycleProps){
  const instanceId=useId(),targetId=`${instanceId}-target`,actionId=`${instanceId}-action`,reasonId=`${instanceId}-reason`,confirmationId=`${instanceId}-consent`,target=props.connections.find((connection)=>connection.id===props.targetId);
  return<section className={styles.MessagingConnectionLifecycle} aria-label="Seguridad y retiro de conexiones"><h2 className={styles.MessagingConnectionLifecycle__title}>Seguridad y retiro</h2>
    {props.connections.length===0?<p className={styles.MessagingConnectionLifecycle__help}>No hay conexiones vigentes para gestionar.</p>:<>
      <div className={styles.MessagingConnectionLifecycle__field}><Label htmlFor={targetId}>Conexión que querés gestionar</Label><Select value={props.targetId} disabled={props.busy} onValueChange={props.onTarget}><SelectTrigger id={targetId}><SelectValue /></SelectTrigger><SelectContent>{props.connections.map((connection)=><SelectItem key={connection.id} value={connection.id}>{connection.name} · {connection.selected&&connection.candidate?"Seleccionada y candidata":connection.selected?"Seleccionada":"Candidata"}</SelectItem>)}</SelectContent></Select></div>
      {target&&<p className={styles.MessagingConnectionLifecycle__help}>Estado actual: {MESSAGING_CONNECTION_LABEL[target.state]}. La acción afecta a esta conexión y todas sus versiones.</p>}
      <div className={styles.MessagingConnectionLifecycle__field}><Label htmlFor={actionId}>Acción local</Label><Select value={props.retiring?MESSAGING_LIFECYCLE_BROWSER_PATH.disconnect:MESSAGING_LIFECYCLE_BROWSER_PATH.suspend} disabled={props.busy} onValueChange={(value)=>props.onRetiring(value===MESSAGING_LIFECYCLE_BROWSER_PATH.disconnect)}><SelectTrigger id={actionId}><SelectValue /></SelectTrigger><SelectContent><SelectItem value={MESSAGING_LIFECYCLE_BROWSER_PATH.suspend}>Suspender nuevos envíos</SelectItem><SelectItem value={MESSAGING_LIFECYCLE_BROWSER_PATH.disconnect}>Desconectar y retirar recursos</SelectItem></SelectContent></Select></div>
      {!props.retiring&&<div className={styles.MessagingConnectionLifecycle__field}><Label htmlFor={reasonId}>Motivo de suspensión</Label><Select value={props.reason} disabled={props.busy} onValueChange={(value)=>{const reason=Object.values(MESSAGING_CONNECTION_SECURITY_REASON).find((candidate)=>candidate===value);if(reason)props.onReason(reason);}}><SelectTrigger id={reasonId}><SelectValue /></SelectTrigger><SelectContent><SelectItem value={MESSAGING_CONNECTION_SECURITY_REASON.securityStop}>Detención de seguridad</SelectItem><SelectItem value={MESSAGING_CONNECTION_SECURITY_REASON.suspectedCompromise}>Sospecha de compromiso</SelectItem></SelectContent></Select></div>}
      <p className={styles.MessagingConnectionLifecycle__help}>{props.retiring?"El servidor comprueba las dependencias vigentes. Para retirar la seleccionada, resolvé la verificación requerida o pausá admisiones y desactivá los avisos externos dependientes. Las pruebas ya aplicadas conservan su procedencia.":props.reason===MESSAGING_CONNECTION_SECURITY_REASON.suspectedCompromise?"Se detienen los nuevos envíos y las pruebas afectadas de solicitudes pendientes requieren recomprobación. Los miembros admitidos y las invitaciones permanecen.":"Se detienen los nuevos envíos sin depender del proveedor. La selección y los ajustes de admisión permanecen; no se dispensa una verificación requerida."}</p>
      <p className={styles.MessagingConnectionLifecycle__help}>Los mensajes ya aceptados o inciertos pueden continuar y conservan su consumo. Revocar la clave en Zavu es una acción separada.</p>
      <div className={styles.MessagingConnectionLifecycle__consent}><Checkbox id={confirmationId} checked={props.confirmed} disabled={props.busy} onCheckedChange={(checked)=>props.onConfirm(checked===true)} /><Label htmlFor={confirmationId}>Revisé la conexión, la acción y su impacto y quiero confirmar.</Label></div>
      <div className={styles.MessagingConnectionLifecycle__actions}><Button type="button" variant="outline" disabled={props.busy} onClick={props.onReauthenticate}>Confirmar acción local con Google</Button><Button type="button" disabled={props.busy||!props.canAct||!props.confirmed} onClick={props.onAct}>{props.retiring?"Desconectar conexión":"Suspender conexión"}</Button></div>
    </>}
    {props.message&&<p className={styles.MessagingConnectionLifecycle__feedback} role={props.message.kind} aria-live={props.message.kind==="alert"?"assertive":"polite"}>{props.message.text}</p>}
  </section>;
}
