/** Renders policy editing and explicit confirmation from current props, without session or HTTP dependencies. @module admission-policy-form */
import { Button, Checkbox, Select, SelectContent, SelectItem, SelectTrigger, SelectValue, Textarea } from "beez-ui";
import { useId } from "react";
import { Link } from "@/components/navigation/link";
import type { AdmissionPolicyDraft } from "@/src/modules/academy-admissions/application/commands/admission-policy-draft";
import type { AdmissionPolicyStateDto } from "@/src/modules/academy-admissions/application/results/admission-policy-result-schemas";
import { ADMISSION_POLICY_MODE, ADMISSION_PHONE_CHANNEL, ADMISSION_POLICY_PUBLIC_STATE } from "@/src/modules/academy-admissions/constants/admission-policy";
import { ADMISSION_CONTACT_TYPE } from "@/src/modules/academy-admissions/constants/admission-contact";
import { ADMISSION_LIMIT } from "@/src/modules/academy-admissions/constants/admission-limits";
import styles from "./styles.module.scss";

/** Preparation and safe messages come from the route container; they are never authority supplied by a form. */
export type AdmissionPolicyFormProps = {
  state: AdmissionPolicyStateDto; draft: AdmissionPolicyDraft; confirmed: boolean; canEdit: boolean; busy: boolean;
  errorMessage: string | null; validationMessage: string | null; preflightMessage: string | null; activationAvailable: boolean; pauseReason: string; usageSettingsHref: string | null;
  onChange: (draft: AdmissionPolicyDraft) => void; onConfirm: (confirmed: boolean) => void; onPauseReason: (reason: string) => void;
  onInitialize: () => void; onSave: () => void; onActivate: () => void; onPause: () => void; onCheckPreflight: () => void; onReloadCurrent: () => void;
  statusMessage?: string | null; uncertain?: boolean; canRetry?: boolean; onRetryOriginal?: () => void;
  reauthenticationRequired?: boolean; reauthenticationHref?: string | null; onPrepareReauthentication?: () => void;
};

/** @param props - Current safe state, retained draft and validated container callbacks. @returns Accessible policy form with independent controls, explicit impact and current protection status. */
export function AdmissionPolicyForm(props: AdmissionPolicyFormProps) {
  const instanceId = useId(), modeId = `${instanceId}-mode`, contactId = `${instanceId}-contact`, checkId = `${instanceId}-check`, openId = `${instanceId}-open`, exceptionsId = `${instanceId}-exceptions`, phoneId = `${instanceId}-phone`, smsId = `${instanceId}-sms`, confirmId = `${instanceId}-confirm`, reasonId = `${instanceId}-reason`;
  const unavailable = props.state.state === ADMISSION_POLICY_PUBLIC_STATE.unavailable, disabled = !props.canEdit || props.busy || unavailable, hasPolicy = props.state.policy !== null;
  const mayConfirm = !disabled && props.confirmed && !props.validationMessage;
  return <form className={styles.AdmissionPolicyForm} aria-busy={props.busy} onSubmit={(event) => { event.preventDefault(); if (mayConfirm && hasPolicy) props.onSave(); }}>
    <header className={styles.AdmissionPolicyForm__header}><h1 className={styles.AdmissionPolicyForm__title}>Configuración de admisión</h1><p>Prepará las reglas de ingreso y revisá su impacto antes de confirmar.</p></header>
    <p role="status">{props.state.controlActivated ? "El control de admisión ya protege los ingresos gratuitos de esta academia." : "Esta academia todavía no tiene activado el control. Guardar un borrador no protege los enlaces anteriores."}</p>
    {!props.canEdit && <p>La configuración sólo está disponible para el líder activo de esta academia.</p>}
    {unavailable && <p role="alert" className={styles.AdmissionPolicyForm__error}>La configuración requiere revisión antes de continuar. La protección existente se conserva.</p>}
    {hasPolicy && <fieldset className={styles.AdmissionPolicyForm__fields} disabled={disabled}>
      <legend className={styles.AdmissionPolicyForm__legend}>Reglas de ingreso</legend>
      <div className={styles.AdmissionPolicyForm__field}><label htmlFor={modeId}>Forma de revisión</label><Select value={props.draft.mode} disabled={disabled} onValueChange={(value) => { if (value === ADMISSION_POLICY_MODE.manualReview || value === ADMISSION_POLICY_MODE.allowlist) props.onChange({ ...props.draft, mode: value }); }}><SelectTrigger id={modeId}><SelectValue /></SelectTrigger><SelectContent><SelectItem value={ADMISSION_POLICY_MODE.manualReview}>Revisión manual</SelectItem><SelectItem value={ADMISSION_POLICY_MODE.allowlist}>Lista de personas autorizadas</SelectItem></SelectContent></Select></div>
      <div className={styles.AdmissionPolicyForm__field}><label htmlFor={contactId}>Contacto para el ingreso</label><Select value={props.draft.contactType} disabled={disabled || props.state.impact.contactTypeLocked} onValueChange={(value) => { if (value === ADMISSION_CONTACT_TYPE.email || value === ADMISSION_CONTACT_TYPE.phone) props.onChange({ ...props.draft, contactType: value }); }}><SelectTrigger id={contactId}><SelectValue /></SelectTrigger><SelectContent><SelectItem value={ADMISSION_CONTACT_TYPE.email}>Correo</SelectItem><SelectItem value={ADMISSION_CONTACT_TYPE.phone}>Teléfono</SelectItem></SelectContent></Select>{props.state.impact.contactTypeLocked && <p className={styles.AdmissionPolicyForm__help}>El tipo de contacto quedó fijado al activar el control.</p>}</div>
      <div className={styles.AdmissionPolicyForm__check}><Checkbox id={checkId} checked={props.draft.requiresAdditionalVerification} disabled={disabled} onCheckedChange={(checked) => props.onChange({ ...props.draft, requiresAdditionalVerification: checked === true })} /><label htmlFor={checkId}>Comprobar el contacto con un código</label></div>
      <p className={styles.AdmissionPolicyForm__help}>Esta comprobación se elige por separado de los avisos y de la conexión de mensajería. Podés preparar un borrador antes de tener un canal disponible.</p>
      <div className={styles.AdmissionPolicyForm__check}><Checkbox id={openId} checked={props.draft.isOpen} disabled={disabled} onCheckedChange={(checked) => props.onChange({ ...props.draft, isOpen: checked === true })} /><label htmlFor={openId}>Recibir nuevas solicitudes</label></div>
      <div className={styles.AdmissionPolicyForm__check}><Checkbox id={exceptionsId} checked={props.draft.allowCommonExceptions} disabled={disabled} onCheckedChange={(checked) => props.onChange({ ...props.draft, allowCommonExceptions: checked === true })} /><label htmlFor={exceptionsId}>Permitir solicitudes comunes como excepción</label></div>
      {props.draft.contactType === ADMISSION_CONTACT_TYPE.phone && <>
        {!props.draft.requiresAdditionalVerification && <p role="status" className={styles.AdmissionPolicyForm__help}>Con teléfono y códigos desactivados, el ingreso común manual está disponible; las invitaciones personales por teléfono no están disponibles.</p>}
        <div className={styles.AdmissionPolicyForm__field}><label htmlFor={phoneId}>Canal del código</label><Select value={props.draft.phoneChannel ?? undefined} disabled={disabled || !props.draft.requiresAdditionalVerification} onValueChange={(value) => { if (value === ADMISSION_PHONE_CHANNEL.sms || value === ADMISSION_PHONE_CHANNEL.whatsapp) props.onChange({ ...props.draft, phoneChannel: value }); }}><SelectTrigger id={phoneId}><SelectValue placeholder="Elegí un canal" /></SelectTrigger><SelectContent><SelectItem value={ADMISSION_PHONE_CHANNEL.sms}>SMS</SelectItem><SelectItem value={ADMISSION_PHONE_CHANNEL.whatsapp}>WhatsApp</SelectItem></SelectContent></Select></div>
        <div className={styles.AdmissionPolicyForm__check}><Checkbox id={smsId} checked={props.draft.allowSmsAlternative} disabled={disabled || !props.draft.requiresAdditionalVerification || props.draft.phoneChannel !== ADMISSION_PHONE_CHANNEL.whatsapp} onCheckedChange={(checked) => props.onChange({ ...props.draft, allowSmsAlternative: checked === true })} /><label htmlFor={smsId}>Ofrecer SMS como alternativa a WhatsApp</label></div>
      </>}

    </fieldset>}
<div className={styles.AdmissionPolicyForm__field}><h2 className={styles.AdmissionPolicyForm__sectionTitle}>Países habilitados</h2><p>{props.state.usage?.allowedCountries.length ? props.state.usage.allowedCountries.join(", ") : "Todavía no hay países habilitados para el envío telefónico."}</p>{props.usageSettingsHref && <Link href={props.usageSettingsHref}>Configurar países y cupos de mensajería</Link>}</div>
    <section className={styles.AdmissionPolicyForm__impact} aria-label="Impacto de la configuración"><h2 className={styles.AdmissionPolicyForm__sectionTitle}>Antes de confirmar</h2><p>{props.state.impact.pendingRequestCount} solicitudes pendientes conservan su fecha y su estado; se revisarán con las reglas vigentes. Activar los códigos inicia una nueva exigencia de comprobación y no aprueba solicitudes automáticamente.</p><p>Al activar por primera vez, el tipo de contacto elegido queda fijo.</p></section>
    <div className={styles.AdmissionPolicyForm__check}><Checkbox id={confirmId} checked={props.confirmed} disabled={disabled} onCheckedChange={(checked) => props.onConfirm(checked === true)} /><label htmlFor={confirmId}>Revisé las reglas y su impacto y quiero confirmar esta acción.</label></div>
    {!props.confirmed && <p className={styles.AdmissionPolicyForm__help}>Marcá la confirmación para preparar o guardar la configuración.</p>}
    {props.validationMessage && <p role="alert" className={styles.AdmissionPolicyForm__error}>{props.validationMessage}</p>}
    {props.errorMessage && <div role="alert" className={styles.AdmissionPolicyForm__error}><p>{props.errorMessage}</p><Button type="button" variant="outline" disabled={props.busy} onClick={props.onReloadCurrent}>Consultar configuración actual</Button><p>El borrador se conserva para que puedas compararlo antes de volver a confirmar.</p></div>}
    <div className={styles.AdmissionPolicyForm__actions}>{hasPolicy ? <Button type="submit" disabled={!mayConfirm}>{props.busy ? "Procesando…" : props.state.controlActivated ? "Guardar configuración" : "Guardar borrador"}</Button> : <Button type="button" disabled={!mayConfirm} onClick={props.onInitialize}>Preparar configuración</Button>}{hasPolicy && !props.state.controlActivated && <><Button type="button" variant="outline" disabled={disabled} onClick={props.onCheckPreflight}>Revisar requisitos de activación</Button><Button type="button" disabled={!mayConfirm || !props.activationAvailable} onClick={props.onActivate}>Activar control de admisión</Button></>}</div>
    {props.preflightMessage && <p role="status" className={styles.AdmissionPolicyForm__help}>{props.preflightMessage}</p>}
    {props.statusMessage && <p role="status">{props.statusMessage}</p>}
    {props.reauthenticationRequired && <section className={styles.AdmissionPolicyForm__field} aria-label="Confirmación de Google"><p>La acción requiere confirmar tu cuenta de Google. El borrador y la operación original se conservan; al volver tendrás que revisar el estado y confirmar nuevamente.</p>{props.reauthenticationHref ? <Link href={props.reauthenticationHref}>Continuar con la confirmación de Google</Link> : <Button type="button" variant="outline" disabled={props.busy} onClick={props.onPrepareReauthentication}>Preparar confirmación con Google</Button>}</section>}
    {props.uncertain && <section className={styles.AdmissionPolicyForm__field} aria-label="Recuperar operación original"><p role="status">Todavía no podemos confirmar el resultado. Consultá la operación original antes de volver a guardar.</p><Button type="button" variant="outline" disabled={props.busy} onClick={props.onReloadCurrent}>Consultar operación original</Button>{props.canRetry && <><div className={styles.AdmissionPolicyForm__check}><Checkbox id={`${instanceId}-retry`} checked={props.confirmed} disabled={props.busy} onCheckedChange={(checked) => props.onConfirm(checked === true)} /><label htmlFor={`${instanceId}-retry`}>Confirmo reintentar la misma operación con sus datos originales.</label></div><Button type="button" disabled={!props.confirmed || props.busy} onClick={props.onRetryOriginal}>Reintentar operación original</Button></>}</section>}
    {props.state.policy?.isOpen && <section className={styles.AdmissionPolicyForm__field} aria-label="Pausar admisiones"><label htmlFor={reasonId}>Motivo de la pausa</label><Textarea id={reasonId} value={props.pauseReason} maxLength={ADMISSION_LIMIT.internalMessageCharacters} disabled={disabled} onChange={(event) => props.onPauseReason(event.target.value)} /><p className={styles.AdmissionPolicyForm__help}>La pausa cierra nuevas solicitudes y aprobaciones. Consultar, rechazar o cancelar solicitudes sigue disponible.</p><Button type="button" variant="outline" disabled={disabled || !props.confirmed || !props.pauseReason.trim()} onClick={props.onPause}>Pausar admisiones</Button></section>}
  </form>;
}
