/** Names the wizard route, original metadata transport and UI state without a global key or automatic mutation. @module messaging-connections-browser */
/** Leaf navigation is independent from the existing early countries/usage page. */
export const MESSAGING_CONNECTIONS_SETTINGS_SEGMENT="academia/admissions/messaging/connections";
/** Own endpoint fragments cannot be supplied by the browser as provider destinations. */
export const MESSAGING_CONNECTIONS_BROWSER_PATH={tribePrefix:"/api/tribes",configuration:"messaging/configuration",connections:"messaging/connections",operations:"messaging/operations",validate:"validate"} as const;
/** Writing and readonly recovery have distinct effects; aborting observation never asserts rollback. */
export const MESSAGING_CONNECTIONS_BROWSER_PHASE={checking:"checking",idle:"idle",confirming:"confirming",writing:"writing",recovering:"recovering",unavailable:"unavailable"} as const;
/** Only original UUID/type metadata is stored under viewer/route scope. */
export const MESSAGING_CONNECTIONS_INTENT_STORAGE_PREFIX="tutribu:messaging-connection-intent";
/** A full local history blocks another archive instead of silently dropping an original reference. */
export const MESSAGING_CONNECTION_HISTORY_LIMIT=20;
export const MESSAGING_CONNECTION_HISTORY_STORAGE_SUFFIX=":history";
/** Explicit inspection consumes its own credential allowance, never a message quota or channel proof. */
export const MESSAGING_CREDENTIAL_CHECK_UI_COPY={checking:"Comprobando la credencial…",checked:"La credencial quedó comprobada. Revisá el tipo de cuenta antes de continuar.",recovered:"La comprobación original quedó confirmada. Revisá el estado actual.",pending:"No pudimos confirmar la comprobación. Consultá el resultado original antes de repetirla.",readingCurrent:"Consultando la conexión actual…",currentRead:"La conexión actual quedó consultada. Revisá los datos y confirmá otra vez.",currentUnavailable:"No pudimos consultar la conexión actual. Reintentá la consulta antes de confirmar cambios.",confirming:"Confirmá tu cuenta con Google antes de comprobar la credencial."} as const;
/** Clear localized feedback without provider/internal errors or optimistic claims of a committed write. */
export const MESSAGING_CONNECTIONS_UI_COPY={nameRequired:"Ingresá un nombre para la conexión.",nameTooLong:"El nombre de la conexión es demasiado largo.",keyRequired:"Ingresá la clave antes de guardar.",confirmationRequired:"Confirmá que querés guardar la credencial.",writing:"Guardando la conexión…",saved:"La conexión candidata quedó guardada.",pending:"No pudimos confirmar el guardado. Consultá su resultado antes de volver a guardar.",reading:"Consultando el resultado del guardado…",viewerChanged:"La cuenta cambió. Volvé a abrir esta página para continuar.",clearFailed:"No pudimos limpiar la referencia local del guardado. Consultá el guardado para continuar.",storageUnavailable:"No pudimos conservar la referencia del guardado. Reintentá antes de guardar.",reauthenticationFailed:"No pudimos preparar la confirmación con Google. Reintentá.",keyAfterReauthentication:"Ingresá la clave después de confirmar tu cuenta con Google.",reauthenticationReady:"La confirmación está preparada. Continuá con Google."} as const;

/** Recovery preserves the exact original identity and requires a separate explicit continuation. */
export const MESSAGING_CONNECTION_RECOVERY_UI_COPY={originalMissing:"Esta referencia no conserva los datos originales necesarios para reanudar. Podés consultar el resultado y el estado actual, o conservarla en el historial sin cancelar el trabajo anterior.",archiveExplanation:"El historial conserva esta referencia en esta pestaña. Dejar de seguirla no cancela ni revierte la operación del servidor; puede completar después. Antes de otra acción, revisá el estado actual.",archiveFailed:"No pudimos conservar el intento en el historial. Se mantiene pendiente para evitar perder su referencia.",archived:"El intento quedó conservado en el historial local. No se canceló el trabajo del servidor. Revisá el estado actual antes de otra acción.",originalUnconfirmed:"El original todavía no tiene un resultado confirmado. La consulta actual no demuestra que se haya cancelado. Podés volver a consultar o reanudar ese mismo intento con los datos originales.",keyAgain:"Ingresá nuevamente la misma clave original. No se guardó en el navegador.",resuming:"Reanudando la operación original…",consultAgain:"La operación original fue consultada. Usá Consultar guardado para confirmar su resultado y el estado actual."} as const;
