/** Names closed semantic outcomes and safe Spanish copy; transport mapping remains in infrastructure. */
export const MESSAGING_ERROR_CODE = {
  invalidInput: "invalid_input",
  authenticationRequired: "authentication_required",
  permissionDenied: "permission_denied",
  resourceUnavailable: "resource_unavailable",
  idempotencyConflict: "idempotency_conflict",
  usagePolicyConflict: "usage_policy_conflict",
  recipientNotAllowed: "recipient_not_allowed",
  usageLimitReached: "usage_limit_reached",
  reauthenticationRequired: "reauthentication_required",
  connectionIncomplete: "connection_incomplete",
  missingCapability: "missing_capability",
  invalidCredentials: "invalid_credentials",
  upstreamRejected: "upstream_rejected",
  providerRateLimited: "provider_rate_limited",
  transportTimeout: "transport_timeout",
  dependencyUnavailable: "dependency_unavailable",
  deliveryUnknown: "delivery_unknown",
  operationUnresolved: "operation_unresolved",
  upstreamPayloadUnusable: "upstream_payload_unusable",
  publicContractUnusable: "public_contract_unusable",
  unexpectedFailure: "unexpected_failure",
} as const;

/** Only catalogue copy can cross the public error boundary. */
export const MESSAGING_ERROR_MESSAGE = {
  [MESSAGING_ERROR_CODE.invalidInput]: "Revisá los datos de la operación antes de confirmar.",
  [MESSAGING_ERROR_CODE.authenticationRequired]: "Iniciá sesión para gestionar la mensajería de la academia.",
  [MESSAGING_ERROR_CODE.permissionDenied]: "No tenés permiso para realizar esta operación.",
  [MESSAGING_ERROR_CODE.resourceUnavailable]: "El recurso solicitado no está disponible.",
  [MESSAGING_ERROR_CODE.idempotencyConflict]: "Esta operación ya tiene otro contenido. Consultá su estado antes de repetir.",
  [MESSAGING_ERROR_CODE.usagePolicyConflict]: "Los cupos o países cambiaron. Revisalos y volvé a confirmar.",
  [MESSAGING_ERROR_CODE.recipientNotAllowed]: "La academia no tiene habilitado el país de ese teléfono.",
  [MESSAGING_ERROR_CODE.usageLimitReached]: "Se alcanzó el límite de nuevos envíos. Podés validar un código vigente o consultar tu solicitud.",
  [MESSAGING_ERROR_CODE.reauthenticationRequired]: "Volvé a autenticarte para confirmar esta operación sensible.",
  [MESSAGING_ERROR_CODE.connectionIncomplete]: "La academia todavía no tiene preparada la conexión necesaria.",
  [MESSAGING_ERROR_CODE.missingCapability]: "La academia todavía no tiene preparado el canal necesario.",
  [MESSAGING_ERROR_CODE.invalidCredentials]: "El líder debe revisar las credenciales de mensajería de la academia.",
  [MESSAGING_ERROR_CODE.upstreamRejected]: "El proveedor rechazó la operación. Revisá la configuración antes de intentar otra vez.",
  [MESSAGING_ERROR_CODE.providerRateLimited]: "El proveedor limitó temporalmente la operación. Esperá antes de consultar otra vez.",
  [MESSAGING_ERROR_CODE.transportTimeout]: "La consulta de mensajería excedió su tiempo. Conservá los datos y consultá su estado.",
  [MESSAGING_ERROR_CODE.dependencyUnavailable]: "La mensajería no está disponible temporalmente. Podés consultar tu solicitud.",
  [MESSAGING_ERROR_CODE.deliveryUnknown]: "No pudimos confirmar el resultado del envío. Consultá su estado antes de repetir.",
  [MESSAGING_ERROR_CODE.operationUnresolved]: "La operación está registrada y su resultado todavía no se confirmó. Consultá su estado.",
  [MESSAGING_ERROR_CODE.upstreamPayloadUnusable]: "No pudimos interpretar la respuesta de mensajería. Conservá los datos y consultá el estado.",
  [MESSAGING_ERROR_CODE.publicContractUnusable]: "No pudimos mostrar el resultado de la operación. Conservá los datos y consultá el estado.",
  [MESSAGING_ERROR_CODE.unexpectedFailure]: "No pudimos completar la operación de mensajería. Conservá los datos y consultá el estado.",
} as const;
