import { fixupConfigRules } from "@eslint/compat";
import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import * as noEslintDisable from "eslint-plugin-no-eslint-disable";
import noMagic, { recommendedMagicNumberOptions } from "eslint-plugin-no-magic";

const deprecatedFeatureImportPatterns = ["@/src/features/*", "src/features/*"];
const moduleSetupImportPatterns = [
  "@/src/modules/setup",
  "@/src/modules/setup.*",
  "@/src/modules/*/setup",
  "@/src/modules/*/setup.*",
  "src/modules/setup",
  "src/modules/setup.*",
  "src/modules/*/setup",
  "src/modules/*/setup.*",
];
const relativeModuleSetupImportPatterns = [
  {
    regex: String.raw`^(?:\.\./)+(?:[^/]+/)?setup(?:\.[^/]+)?$`,
  },
];
const sitepingWidgetImportPatterns = ["@siteping/widget"];

const eslintConfig = defineConfig([
  ...fixupConfigRules(nextVitals),
  ...fixupConfigRules(nextTs),
  {
    files: ["**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: deprecatedFeatureImportPatterns,
        },
      ],
    },
  },
  {
    files: ["src/modules/*/{application,domain,infrastructure,presentation}/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: [
                ...deprecatedFeatureImportPatterns,
                ...moduleSetupImportPatterns,
              ],
            },
            ...relativeModuleSetupImportPatterns,
          ],
        },
      ],
    },
  },
  {
    files: ["src/modules/siteping/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: [
                ...deprecatedFeatureImportPatterns,
                ...moduleSetupImportPatterns,
                ...sitepingWidgetImportPatterns,
              ],
            },
            ...relativeModuleSetupImportPatterns,
          ],
        },
      ],
    },
  },
  {
    files: ["components/ui/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    files: [
      "app/**/*.{ts,tsx}",
      "components/**/*.{ts,tsx}",
      "hooks/**/*.{ts,tsx}",
      "src/**/*.{ts,tsx}",
      "lib/**/*.{ts,tsx}",
    ],
    ignores: [
      // Generated by the shadcn/ui CLI; must stay close to upstream defaults.
      "components/ui/**/*.{ts,tsx}",
    ],
    plugins: {
      "no-eslint-disable": noEslintDisable,
      "no-magic": noMagic,
    },
    rules: {
      "@typescript-eslint/no-magic-numbers": ["error", recommendedMagicNumberOptions],
      "no-eslint-disable/no-eslint-disable": "error",
      // The default sink list includes the router-oriented `push`, `replace`,
      // and `navigate`, matched by method name only. This app navigates through
      // `redirect()`, `<Link>`, and `ROUTES` constants, never `router.push("/...")`,
      // so those sinks add no real route-contract detection here and instead
      // flag ordinary `Array.prototype.push` and `String.prototype.replace`
      // calls. Keep only the sinks that model genuine hidden contracts:
      // analytics events, storage keys, and feature flags.
      "no-magic/no-magic-strings": [
        "error",
        {
          sinks: [
            "track",
            "trackEvent",
            "sendEvent",
            "logEvent",
            "captureEvent",
            "getItem",
            "setItem",
            "removeItem",
            "isFeatureEnabled",
            "isEnabled",
            "getFlag",
          ],
        },
      ],
    },
  },
  {
    // The Drizzle schema is a declarative persistence mapping: every string
    // literal is a physical column name or a referential action passed
    // positionally to a column builder, mirroring the adjacent property key
    // (a structural name the rule already ignores). These are visible contract
    // declarations, not hidden contracts, so naming them behind constants would
    // obscure the schema against the Drizzle idiom. Magic numbers stay enforced.
    // This block must follow the one that enables the rule so it wins.
    files: ["**/infrastructure/database/schema.ts"],
    rules: {
      "no-magic/no-magic-strings": "off",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    ".open-next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
]);

export default eslintConfig;
