allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  msw: false
  sharp: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - beez-ui
  - beez-rp
  - react-dom@19.3.0
  - react@19.3.0
  - scheduler@0.28.0
  - '@types/react-dom@19.3.0'
  - '@types/react@19.3.0'
  - '@types/node@24.13.4 || 26.5.1'
  - '@beezping/widget@0.12.0'
