"use client";
/** Presents private invitation history and controlled explicit proposals without adapters or session lookups. @module invitation-management */
import { useEffect, useId, useRef } from "react";
import { Button, Checkbox, Input, Label, Select, SelectContent, SelectItem, SelectTrigger, SelectValue, Textarea } from "beez-ui";
import { Link } from "@/components/navigation/link";
import type { PersonalInvitationManagementDraft } from "@/src/modules/academy-admissions/application/commands/personal-invitation-management-intent";
import type { PersonalInvitationManagementResult } from "@/src/modules/academy-admissions/application/results/admission-resource-result";
import { ADMISSION_LIMIT } from "@/src/modules/academy-admissions/constants/admission-limits";
import { PERSONAL_INVITATION_MANAGEMENT_COPY as COPY, PERSONAL_INVITATION_MANAGEMENT_MODE as MODE, PERSONAL_INVITATION_MANAGEMENT_STATUS_LABEL } from "@/src/modules/academy-admissions/constants/personal-invitation-management-browser";
import styles from "./styles.module.scss";

export type InvitationManagementProps = { draft: PersonalInvitationManagementDraft; items: readonly PersonalInvitationManagementResult[]; contactType: "email" | "phone" | null; requiresAdditionalVerification: boolean; hasUsableAllowlist: boolean; allowedCountries: readonly string[]; ready: boolean; busy: boolean; privateVisible: boolean; pending: boolean; confirmed: boolean; conflict: boolean; needsCurrent: boolean; selectionBlocked: boolean; onDiscardSelection: () => void; hasNext: boolean; errorMessage: string | null; fieldError: string | null; statusMessage: string | null; invitationUrl: string | null; reauthenticationRequired: boolean; recoveryHref: string | null; onDraftChange: (value: PersonalInvitationManagementDraft) => void; onConfirm: (value: boolean) => void; onSave: () => void; onSelect: (item: PersonalInvitationManagementResult, mode: "create" | "rename" | "revoke") => void; onNew: () => void; onReadOriginal: () => void; onReadCurrent: () => void; onNext: () => void; onReauthenticate: () => void; onHideUrl: () => void; onCopyUrl: () => void };

/** @param props - Controlled current state and explicit callbacks. @returns Responsive semantic controls with independent consent and visible feedback. */
export function InvitationManagement(props: InvitationManagementProps) {
  const id = useId(), feedback = useRef<HTMLParagraphElement>(null), disabled = !props.ready || props.busy || props.pending, create = props.draft.mode === MODE.create, revoke = props.draft.mode === MODE.revoke;
  const cannotCreate = !props.contactType || props.contactType === "phone" && !props.requiresAdditionalVerification;
  useEffect(() => { if (props.errorMessage || props.fieldError) feedback.current?.focus(); }, [props.errorMessage, props.fieldError]);
  return <section className={styles.InvitationManagement} aria-label="Gestión de invitaciones personales" aria-busy={props.busy}>
    {!props.privateVisible ? <p role="alert">{COPY.account}</p> : <>
      <p className={styles.InvitationManagement__help}>Cada invitación corresponde a un destinatario. Abrir el enlace o comprobar un código no lo canjea. Solo el líder puede gestionar estas invitaciones.</p>
      {props.invitationUrl && <section className={styles.InvitationManagement__link} aria-labelledby={`${id}-link-title`}><h2 id={`${id}-link-title`}>Enlace recién emitido</h2><p>Copialo ahora. El enlace completo se muestra una sola vez y no se recupera desde el historial. Si perdés esta respuesta, revocá la invitación y emití otra.</p><Label htmlFor={`${id}-link`}>Enlace personal</Label><Input id={`${id}-link`} readOnly value={props.invitationUrl} onFocus={(event) => event.currentTarget.select()} /><div className={styles.InvitationManagement__actions}><Button type="button" disabled={props.busy} onClick={props.onCopyUrl}>Copiar enlace</Button><Button type="button" variant="outline" onClick={props.onHideUrl}>Ocultar enlace</Button></div></section>}
      <section aria-labelledby={`${id}-history`}><h2 id={`${id}-history`}>Historial de invitaciones</h2>
        {props.items.length === 0 ? <p className={styles.InvitationManagement__help}>Todavía no hay invitaciones en esta vista.</p> : <ul className={styles.InvitationManagement__list}>{props.items.map((item) => <li key={item.id} className={styles.InvitationManagement__row}><div className={styles.InvitationManagement__identity}><strong>{item.internalName}</strong><span>{item.recipient.value}</span><span>{PERSONAL_INVITATION_MANAGEMENT_STATUS_LABEL[item.status]}{item.authorizationRevokedAt ? " · Autorización retirada" : ""} · Versión {item.version}</span><span className={styles.InvitationManagement__help}>{item.requiresAllowlist ? "Exige lista de habilitados" : "Dispensa la lista"} · {item.expiresAt ? `Vigencia del enlace: ${item.expiresAt} (UTC)` : "Sin vencimiento del enlace"}</span>{item.redeemedAt && <span className={styles.InvitationManagement__help}>Canje: {item.redeemedAt} (UTC)</span>}</div><div className={styles.InvitationManagement__actions}><Button type="button" variant="outline" disabled={disabled || props.conflict} onClick={() => props.onSelect(item, MODE.rename)} aria-label={`Renombrar ${item.internalName}`}>Renombrar</Button>{item.status === "active" && <Button type="button" variant="outline" disabled={disabled || props.conflict} onClick={() => props.onSelect(item, MODE.create)} aria-label={`Reemitir ${item.internalName}`}>Reemitir</Button>}{(item.status === "active" || item.status === "redeemed" && !item.authorizationRevokedAt) && <Button type="button" variant="outline" disabled={disabled || props.conflict} onClick={() => props.onSelect(item, MODE.revoke)} aria-label={`Revocar ${item.internalName}`}>{item.status === "redeemed" ? "Retirar autorización" : "Revocar"}</Button>}</div></li>)}</ul>}
        <div className={styles.InvitationManagement__actions}><Button type="button" variant="outline" disabled={props.busy || props.pending} onClick={props.onReadCurrent}>Consultar estado actual</Button>{props.hasNext && <Button type="button" variant="outline" disabled={disabled} onClick={props.onNext}>Ver más invitaciones</Button>}<Button type="button" variant="outline" disabled={disabled || props.conflict} onClick={props.onNew}>Nueva invitación</Button></div>
      </section>
      <form className={styles.InvitationManagement__form} noValidate onSubmit={(event) => { event.preventDefault(); props.onSave(); }}>
        <h2>{create ? props.draft.replaceSelected ? "Reemitir invitación" : "Emitir invitación personal" : revoke ? "Revocar invitación" : "Renombrar invitación"}</h2>
        {!props.contactType && <p role="status">{COPY.noPolicy}</p>}{props.contactType === "phone" && !props.requiresAdditionalVerification && <p role="status">{COPY.phoneOff}</p>}
        {!revoke && <div className={styles.InvitationManagement__field}><Label htmlFor={`${id}-name`}>Nombre interno</Label><Input id={`${id}-name`} value={props.draft.internalName} maxLength={ADMISSION_LIMIT.displayNameCharacters} disabled={disabled} onChange={(event) => props.onDraftChange({ ...props.draft, internalName: event.target.value })} /></div>}
        {create && <>
          <div className={styles.InvitationManagement__field}><Label htmlFor={`${id}-recipient`}>{props.contactType === "phone" ? "Teléfono destinatario" : "Correo destinatario"}</Label><Input id={`${id}-recipient`} type={props.contactType === "phone" ? "tel" : "email"} value={props.draft.identity} disabled={disabled || cannotCreate || props.draft.replaceSelected} aria-describedby={`${id}-recipient-help`} onChange={(event) => props.onDraftChange({ ...props.draft, identity: event.target.value })} /><p id={`${id}-recipient-help`} className={styles.InvitationManagement__help}>El destinatario queda fijo. Cambiar contacto, requisito de lista o vigencia exige otra emisión.</p></div>
          {props.contactType === "phone" && <div className={styles.InvitationManagement__field}><Label htmlFor={`${id}-country`}>País del teléfono</Label><Select value={props.draft.country} disabled={disabled || cannotCreate || props.draft.replaceSelected} onValueChange={(country) => props.onDraftChange({ ...props.draft, country })}><SelectTrigger id={`${id}-country`}><SelectValue placeholder="Elegí un país habilitado" /></SelectTrigger><SelectContent>{props.allowedCountries.map((country) => <SelectItem key={country} value={country}>{country}</SelectItem>)}</SelectContent></Select><p className={styles.InvitationManagement__help}>Ingresá un teléfono con prefijo internacional y un país habilitado por la academia.</p></div>}
          <div className={styles.InvitationManagement__confirmation}><Checkbox id={`${id}-list`} checked={props.draft.requiresAllowlist} disabled={disabled || !props.hasUsableAllowlist && !props.draft.requiresAllowlist} onCheckedChange={(value) => props.onDraftChange({ ...props.draft, requiresAllowlist: value === true, exemptionAcknowledged: false })} /><Label htmlFor={`${id}-list`}>Exigir coincidencia en la lista de habilitados</Label></div>
          {!props.hasUsableAllowlist && <p className={styles.InvitationManagement__help}>No hay una lista utilizable para este tipo de contacto. La dispensa requiere reconocimiento explícito.</p>}
          {!props.draft.requiresAllowlist && <div className={styles.InvitationManagement__confirmation}><Checkbox id={`${id}-exemption`} checked={props.draft.exemptionAcknowledged} disabled={disabled} onCheckedChange={(value) => props.onDraftChange({ ...props.draft, exemptionAcknowledged: value === true })} /><Label htmlFor={`${id}-exemption`}>Reconozco la dispensa de lista; se conservan la prueba del destinatario, los códigos exigibles, la revisión manual y los bloqueos.</Label></div>}
          <div className={styles.InvitationManagement__field}><Label htmlFor={`${id}-expiry`}>Vencimiento del enlace (fecha y hora UTC)</Label><Input id={`${id}-expiry`} type="datetime-local" value={props.draft.expiry} disabled={disabled || props.draft.noExpiry} onChange={(event) => props.onDraftChange({ ...props.draft, expiry: event.target.value })} /><p className={styles.InvitationManagement__help}>La propuesta inicial tiene siete días de vigencia. El vencimiento del enlace no cambia el plazo de una solicitud ya canjeada.</p></div>
          <div className={styles.InvitationManagement__confirmation}><Checkbox id={`${id}-no-expiry`} checked={props.draft.noExpiry} disabled={disabled} onCheckedChange={(value) => props.onDraftChange({ ...props.draft, noExpiry: value === true, noExpiryAcknowledged: false })} /><Label htmlFor={`${id}-no-expiry`}>Sin vencimiento</Label></div>
          {props.draft.noExpiry && <div className={styles.InvitationManagement__confirmation}><Checkbox id={`${id}-no-expiry-ack`} checked={props.draft.noExpiryAcknowledged} disabled={disabled} onCheckedChange={(value) => props.onDraftChange({ ...props.draft, noExpiryAcknowledged: value === true })} /><Label htmlFor={`${id}-no-expiry-ack`}>Reconozco que el enlace seguirá utilizable hasta su canje o revocación.</Label></div>}
          {props.draft.replaceSelected && props.draft.selected && <div className={styles.InvitationManagement__confirmation}><Checkbox id={`${id}-replacement`} checked={props.draft.replacementAcknowledged} disabled={disabled} onCheckedChange={(value) => props.onDraftChange({ ...props.draft, replacementAcknowledged: value === true })} /><Label htmlFor={`${id}-replacement`}>Confirmo revocar {props.draft.selected.internalName} en su versión {props.draft.selected.version} y emitir otra invitación.</Label></div>}
        </>}
        {revoke && props.draft.selected && <><p>Se revoca la versión {props.draft.selected.version} de {props.draft.selected.internalName}.</p><Label htmlFor={`${id}-reason`}>Motivo interno</Label><Textarea id={`${id}-reason`} value={props.draft.internalReason} maxLength={ADMISSION_LIMIT.internalMessageCharacters} disabled={disabled} onChange={(event) => props.onDraftChange({ ...props.draft, internalReason: event.target.value })} />{props.draft.selected.status === "redeemed" && <div className={styles.InvitationManagement__confirmation}><Checkbox id={`${id}-withdrawal`} checked={props.draft.withdrawalAcknowledged} disabled={disabled} onCheckedChange={(value) => props.onDraftChange({ ...props.draft, withdrawalAcknowledged: value === true })} /><Label htmlFor={`${id}-withdrawal`}>Confirmo retirar la autorización canjeada. Si su solicitud sigue pendiente, se cancela; un miembro admitido no se expulsa y el enlace no se recicla.</Label></div>}</>}
        {(props.fieldError || props.errorMessage) && <p ref={feedback} role="alert" tabIndex={-1} className={styles.InvitationManagement__error}>{props.fieldError ?? props.errorMessage}</p>}
        <div className={styles.InvitationManagement__confirmation}><Checkbox id={`${id}-confirmed`} checked={props.confirmed} disabled={disabled || props.conflict || props.needsCurrent || create && cannotCreate} onCheckedChange={(value) => props.onConfirm(value === true)} /><Label htmlFor={`${id}-confirmed`}>Confirmo esta acción sobre la invitación personal.</Label></div>
        <Button type="submit" disabled={disabled || !props.confirmed || props.conflict || props.needsCurrent || create && cannotCreate}>{props.busy ? "Guardando…" : "Guardar acción"}</Button>
      </form>
      {props.selectionBlocked && <Button type="button" variant="outline" disabled={props.busy || props.pending} onClick={props.onDiscardSelection}>Descartar selección</Button>}
      {props.statusMessage && <p role="status">{props.statusMessage}</p>}
      {props.pending && <Button type="button" variant="outline" disabled={props.busy} onClick={props.onReadOriginal}>Consultar operación original</Button>}
      {props.reauthenticationRequired && (props.recoveryHref ? <><p>Al volver, revisá y completá el borrador; no se guarda automáticamente.</p><Link href={props.recoveryHref}>Continuar confirmación con Google</Link></> : <Button type="button" variant="outline" disabled={props.busy} onClick={props.onReauthenticate}>Confirmar identidad para guardar</Button>)}
    </>}
  </section>;
}
