/** Names closed semantic outcomes and safe Spanish copy; transport mapping remains in infrastructure. */
export const ADMISSION_ERROR_CODE = {
  invalidInput: "invalid_input",
  authenticationRequired: "authentication_required",
  permissionDenied: "permission_denied",
  resourceUnavailable: "resource_unavailable",
  invitationUnavailable: "invitation_unavailable",
  policyConflict: "policy_conflict",
  requestConflict: "request_conflict",
  idempotencyConflict: "idempotency_conflict",
  allowlistConflict: "allowlist_conflict",
  allowlistImportConflict: "allowlist_import_conflict",
  invitationConflict: "invitation_conflict",
  usagePolicyConflict: "usage_policy_conflict",
  connectionConflict: "connection_conflict",
  recipientNotAllowed: "recipient_not_allowed",
  contactEvidenceRequired: "contact_evidence_required",
  additionalVerificationRequired: "additional_verification_required",
  contactBindingConflict: "contact_binding_conflict",
  challengeExpired: "challenge_expired",
  challengeInvalidated: "challenge_invalidated",
  proofUnavailable: "proof_unavailable",
  verificationAttemptsExceeded: "verification_attempts_exceeded",
  usageLimitReached: "usage_limit_reached",
  verificationCodeIncorrect: "verification_code_incorrect",
  reauthenticationRequired: "reauthentication_required",
  admissionsPaused: "admissions_paused",
  admissionIneligible: "admission_ineligible",
  membershipRecoveryRequired: "membership_recovery_required",
  connectionIncomplete: "connection_incomplete",
  missingCapability: "missing_capability",
  invalidCredentials: "invalid_credentials",
  upstreamRejected: "upstream_rejected",
  providerRateLimited: "provider_rate_limited",
  transportTimeout: "transport_timeout",
  dependencyUnavailable: "dependency_unavailable",
  deliveryUnknown: "delivery_unknown",
  operationUnresolved: "operation_unresolved",
  upstreamPayloadUnusable: "upstream_payload_unusable",
  publicContractUnusable: "public_contract_unusable",
  unexpectedFailure: "unexpected_failure",
} as const;

/** Only catalogue copy can cross the public error boundary. */
export const ADMISSION_ERROR_MESSAGE = {
  [ADMISSION_ERROR_CODE.invalidInput]: "Revisá los datos de la operación antes de confirmar.",
  [ADMISSION_ERROR_CODE.authenticationRequired]: "Iniciá sesión para continuar con el ingreso.",
  [ADMISSION_ERROR_CODE.permissionDenied]: "No tenés permiso para realizar esta operación.",
  [ADMISSION_ERROR_CODE.resourceUnavailable]: "El recurso solicitado no está disponible.",
  [ADMISSION_ERROR_CODE.invitationUnavailable]: "La invitación no está disponible para este ingreso.",
  [ADMISSION_ERROR_CODE.policyConflict]: "La configuración cambió. Revisala y volvé a confirmar.",
  [ADMISSION_ERROR_CODE.requestConflict]: "La solicitud cambió. Revisala antes de confirmar.",
  [ADMISSION_ERROR_CODE.idempotencyConflict]: "Esta operación ya tiene otro contenido. Consultá su estado antes de repetir.",
  [ADMISSION_ERROR_CODE.allowlistConflict]: "La entrada cambió. Revisala y volvé a confirmar.",
  [ADMISSION_ERROR_CODE.allowlistImportConflict]: "La importación cambió. Consultá su estado y volvé a confirmar.",
  [ADMISSION_ERROR_CODE.invitationConflict]: "La invitación cambió. Revisala y volvé a confirmar.",
  [ADMISSION_ERROR_CODE.usagePolicyConflict]: "Los cupos o países cambiaron. Revisalos y volvé a confirmar.",
  [ADMISSION_ERROR_CODE.connectionConflict]: "La conexión cambió o ya existe una candidata. Consultá la configuración y volvé a confirmar.",
  [ADMISSION_ERROR_CODE.recipientNotAllowed]: "La academia no tiene habilitado el país de ese teléfono.",
  [ADMISSION_ERROR_CODE.contactEvidenceRequired]: "No pudimos comprobar el contacto necesario para este ingreso.",
  [ADMISSION_ERROR_CODE.additionalVerificationRequired]: "Comprobá tu contacto para continuar con este ingreso.",
  [ADMISSION_ERROR_CODE.contactBindingConflict]: "No pudimos usar ese contacto para el ingreso. Revisá tu cuenta o pedí ayuda.",
  [ADMISSION_ERROR_CODE.challengeExpired]: "El código venció. Solicitá uno nuevo cuando esté disponible.",
  [ADMISSION_ERROR_CODE.challengeInvalidated]: "Ese código ya no está vigente. Consultá el estado antes de pedir otro.",
  [ADMISSION_ERROR_CODE.proofUnavailable]: "La prueba de contacto ya no está disponible para este ingreso.",
  [ADMISSION_ERROR_CODE.verificationAttemptsExceeded]: "Alcanzaste el límite de intentos de verificación. Esperá antes de intentar otra vez.",
  [ADMISSION_ERROR_CODE.usageLimitReached]: "Se alcanzó el límite de nuevos envíos. Podés validar un código vigente o consultar tu solicitud.",
  [ADMISSION_ERROR_CODE.verificationCodeIncorrect]: "El código no es correcto. Revisalo antes de intentar otra vez.",
  [ADMISSION_ERROR_CODE.reauthenticationRequired]: "Volvé a autenticarte para confirmar esta operación sensible.",
  [ADMISSION_ERROR_CODE.admissionsPaused]: "Las admisiones están pausadas. Podés consultar o cancelar tu solicitud.",
  [ADMISSION_ERROR_CODE.admissionIneligible]: "Falta un requisito actual para resolver el ingreso. Consultá el estado de la solicitud.",
  [ADMISSION_ERROR_CODE.membershipRecoveryRequired]: "La recuperación de tu pertenencia requiere asistencia autorizada.",
  [ADMISSION_ERROR_CODE.connectionIncomplete]: "La academia todavía no tiene preparada la conexión necesaria.",
  [ADMISSION_ERROR_CODE.missingCapability]: "La academia todavía no tiene preparado el canal necesario.",
  [ADMISSION_ERROR_CODE.invalidCredentials]: "El líder debe revisar las credenciales de mensajería de la academia.",
  [ADMISSION_ERROR_CODE.upstreamRejected]: "El proveedor rechazó la operación. Revisá la configuración antes de intentar otra vez.",
  [ADMISSION_ERROR_CODE.providerRateLimited]: "El proveedor limitó temporalmente la operación. Esperá antes de consultar otra vez.",
  [ADMISSION_ERROR_CODE.transportTimeout]: "La consulta de mensajería excedió su tiempo. Conservá los datos y consultá su estado.",
  [ADMISSION_ERROR_CODE.dependencyUnavailable]: "La mensajería no está disponible temporalmente. Podés consultar tu solicitud.",
  [ADMISSION_ERROR_CODE.deliveryUnknown]: "No pudimos confirmar el resultado del envío. Consultá su estado antes de repetir.",
  [ADMISSION_ERROR_CODE.operationUnresolved]: "La operación está registrada y su resultado todavía no se confirmó. Consultá su estado.",
  [ADMISSION_ERROR_CODE.upstreamPayloadUnusable]: "No pudimos interpretar la respuesta de mensajería. Conservá los datos y consultá el estado.",
  [ADMISSION_ERROR_CODE.publicContractUnusable]: "No pudimos mostrar el resultado de la operación. Conservá los datos y consultá el estado.",
  [ADMISSION_ERROR_CODE.unexpectedFailure]: "No pudimos completar la operación de admisión. Conservá los datos y consultá el estado.",
} as const;
