/** Owns list navigation, scoped local recovery and UI lifecycle semantics. @module allowlist-browser-constants */
export const ALLOWLIST_SETTINGS_SEGMENT = "academia/admissions/allowlist";
export const ALLOWLIST_BROWSER_STORAGE_PREFIX = "tutribu-allowlist-workflow";
export const ALLOWLIST_BROWSER_TIMEOUT_MS = 120_000;
export const ALLOWLIST_BROWSER_PATH = { prefix: "/api/tribes", segment: "admissions", entries: "allowlist", operations: "operations" } as const;
export const ALLOWLIST_BROWSER_STATUS = { ready: "ready", failed: "failed", aborted: "aborted" } as const;
export const ALLOWLIST_FILTER_ALL = "all";
export const ALLOWLIST_STATUS_LABEL = { enabled: "Habilitada", disabled: "Deshabilitada" } as const;
export const ALLOWLIST_SOURCE_LABEL = { manual: "Agregada manualmente", csv: "Importada" } as const;
export const ALLOWLIST_BROWSER_PHASE = { checking: "checking", idle: "idle", reading: "reading", writing: "writing", uncertain: "uncertain", changedViewer: "changed_viewer" } as const;
export const ALLOWLIST_BROWSER_COPY = { reading: "Consultando la lista…", saving: "Guardando la entrada…", invalid: "Revisá el contacto, su país y el nombre antes de confirmar.", confirm: "Confirmá el cambio antes de guardarlo.", saved: "El cambio de lista quedó guardado.", recovered: "Se confirmó el cambio original. La lista muestra los datos actuales.", uncertain: "La respuesta no quedó confirmada. Consultá la operación original antes de repetir.", started: "El cambio original sigue registrado en proceso. Consultá otra vez antes de crear otro.", absent: "El cambio original todavía no aparece. Conservamos el borrador y la referencia; consultá antes de repetir.", duplicate: "El contacto ya tiene una entrada incompatible. Buscalo en la lista y editá esa entrada, o revisá el contacto de este borrador.", conflict: "La entrada cambió. Conservamos tu borrador: consultá la versión actual y confirmá nuevamente.", storage: "No pudimos conservar el borrador en este navegador. Revisá el almacenamiento antes de guardar.", account: "La cuenta o el acceso cambió. Volvé a cargar esta página para continuar.", noPolicy: "Guardá la configuración de admisión antes de agregar contactos.", reauthentication: "Confirmá tu identidad con Google para guardar este cambio de lista.", reauthenticationFailed: "No pudimos preparar la confirmación de identidad. Conservamos el borrador para intentarlo otra vez." } as const;
