/** Owns management transport, recovery and visible lifecycle vocabulary. @module personal-invitation-management-browser */
import { z } from "zod";
import { REAUTHENTICATION_OPERATION } from "@/src/modules/auth/constants/reauthentication-resources";
import type { PersonalInvitationManagementReference } from "../application/commands/personal-invitation-management-intent";

export const PERSONAL_INVITATION_MANAGEMENT_PATH = { prefix: "/api/tribes", segment: "admissions/invitations", context: "context", operations: "admissions/operations", revoke: "revoke" } as const;
export const PERSONAL_INVITATION_MANAGEMENT_STORAGE_PREFIX = "tutribu-personal-invitation-management";
export const PERSONAL_INVITATION_MANAGEMENT_TIMEOUT_MS = 120_000;
export const PERSONAL_INVITATION_MANAGEMENT_DATE = { minuteCharacters: 16, utcSuffix: ":00Z", minutePattern: /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/u, timeZone: "UTC" } as const;
export const PERSONAL_INVITATION_MANAGEMENT_MODE = { create: "create", rename: "rename", revoke: "revoke" } as const;
export const PERSONAL_INVITATION_MANAGEMENT_PHASE = { checking: "checking", idle: "idle", reading: "reading", writing: "writing", uncertain: "uncertain", closed: "closed" } as const;
export const PERSONAL_INVITATION_MANAGEMENT_FILTER_ALL = "all";
/** A missing selected resource cannot be treated as a refreshed version. */
export const PERSONAL_INVITATION_MANAGEMENT_SELECTION_MISSING = "La invitación seleccionada no aparece en esta vista. Conservamos la acción bloqueada; consultá su estado o descartá la selección antes de otra propuesta.";
/** A consumed or revoked link cannot remain the replacement target of the previous proposal. */
export const PERSONAL_INVITATION_MANAGEMENT_REPLACEMENT_UNAVAILABLE = "La invitación ya no está activa y esta reemisión dejó de ser aplicable. Descartá la selección y elegí explícitamente otra acción.";
export const PERSONAL_INVITATION_MANAGEMENT_STATUS_LABEL = { active: "Activa", revoked: "Revocada", expired: "Vencida", redeemed: "Canjeada" } as const;
export const PERSONAL_INVITATION_MANAGEMENT_COPY = { reading: "Consultando las invitaciones…", saving: "Guardando la invitación…", invalid: "Revisá el destinatario, nombre, vigencia y confirmaciones antes de guardar.", confirm: "Confirmá la acción antes de guardar.", future: "Elegí una fecha y hora UTC futuras.", saved: "La acción quedó guardada.", recovered: "Se confirmó la operación original. Consultamos el estado actual por separado.", lostUrl: "La emisión original quedó confirmada, pero su enlace no se puede recuperar. Consultá la invitación, revocala y emití otra si necesitás el enlace.", uncertain: "La respuesta no quedó confirmada. Consultá la operación original antes de repetir.", absent: "La operación original todavía no aparece. Conservamos su referencia; consultá antes de repetir.", started: "La operación original sigue en proceso. Consultá otra vez antes de crear otra.", storage: "No pudimos guardar la referencia en este navegador. Revisá el almacenamiento antes de confirmar.", account: "La cuenta o el acceso cambió. Volvé a cargar esta página para continuar.", conflict: "La invitación cambió. Consultá su versión actual y revisá la acción antes de confirmar nuevamente.", current: "Estado actual consultado. Revisá los datos y confirmá la acción nuevamente.", authentication: "Confirmá tu identidad con Google antes de guardar esta acción.", authenticationFailed: "No pudimos preparar la confirmación de identidad. Podés intentarlo otra vez.", noPolicy: "Guardá la configuración de admisión antes de emitir invitaciones.", phoneOff: "Con teléfono y código apagado no se emiten invitaciones personales. El ingreso común manual sigue disponible.", copied: "Enlace copiado.", clipboard: "Seleccioná el enlace y copialo manualmente.", freshFailed: "La acción quedó confirmada, pero no pudimos consultar los datos actuales. Consultá el historial antes de otra acción." } as const;

/** Stored progress never retains plaintext creation material or permits a resumed POST. */
export const personalInvitationManagementReferenceSchema = z.strictObject({ type: z.enum([REAUTHENTICATION_OPERATION.createPersonalInvitation, REAUTHENTICATION_OPERATION.renamePersonalInvitation, REAUTHENTICATION_OPERATION.revokePersonalInvitation]), operationId: z.uuid(), invitationId: z.uuid().nullable(), expectedVersion: z.int().positive().nullable() }).refine((reference) => reference.type === REAUTHENTICATION_OPERATION.createPersonalInvitation ? reference.invitationId === null && reference.expectedVersion === null : reference.invitationId !== null && reference.expectedVersion !== null) satisfies z.ZodType<PersonalInvitationManagementReference>;
export const personalInvitationManagementStoredSchema = z.strictObject({ viewerId: z.string().min(1), slug: z.string().min(1), pending: personalInvitationManagementReferenceSchema.nullable() });
