/** Exercises the connection container with actual UI and owned browser/intent ports, preserving keys only in controlled memory. @module messaging-connections-container-tests */
import {randomUUID} from "node:crypto";
import {render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {describe,expect,it,vi} from "vitest";
import {MessagingConnectionsContainer} from "@/app/(platform)/[slug]/academia/admissions/messaging/connections/messaging-connections-container";
import type {MessagingConnectionsBrowserClient} from "@/src/modules/messaging/application/ports/messaging-connections-browser-client";
import type {MessagingConnectionsIntentStore} from "@/src/modules/messaging/application/ports/messaging-connections-intent-store";
import type {MessagingConnectionsPageState} from "@/src/modules/messaging/application/results/messaging-connections-page-state";
import type {MessagingResourcesBrowserClient} from "@/src/modules/messaging/application/ports/messaging-resources-browser-client";
import type {ReauthenticationIntentBrowserClient} from "@/src/modules/auth/application/ports/reauthentication-intent-browser-client";

/** @returns Guarded own SSR state and readonly/writing ports without auth/platform mocks. */
function containerFixture(){
  const viewerId=randomUUID(),tribeId=randomUUID(),configuration={audience:"leader" as const,selected:null,candidate:null,usage:{state:"not_configured" as const,policy:null}},initialState:MessagingConnectionsPageState={kind:"ready",slug:"synthetic",tribeId,viewerId,renderedAt:new Date().toISOString(),configuration},connectionId=randomUUID();
  const create=vi.fn<MessagingConnectionsBrowserClient["create"]>(async(_slug,input)=>({status:"ready",value:{state:"completed",operationId:input.operationId,replayed:false,result:{id:connectionId,name:input.name,version:1,configurationVersion:1,state:"draft",maskedCredential:"••••••••"}}})),client:MessagingConnectionsBrowserClient={viewer:vi.fn<MessagingConnectionsBrowserClient["viewer"]>(async()=>({status:"ready",value:{id:viewerId}})),read:vi.fn<MessagingConnectionsBrowserClient["read"]>(async()=>({status:"ready",value:configuration})),create,validate:vi.fn<MessagingConnectionsBrowserClient["validate"]>(async()=>({status:"failed",code:"resource_unavailable",message:"No disponible.",uncertain:false})),operation:vi.fn<MessagingConnectionsBrowserClient["operation"]>(async()=>({status:"failed",code:"resource_unavailable",message:"No disponible.",uncertain:false}))},store={read:vi.fn<MessagingConnectionsIntentStore["read"]>(()=>null),write:vi.fn<MessagingConnectionsIntentStore["write"]>(()=>true),history:vi.fn<MessagingConnectionsIntentStore["history"]>(()=>[]),archive:vi.fn<MessagingConnectionsIntentStore["archive"]>(()=>true)},reauthentication={create:vi.fn(async()=>({status:"ready" as const,href:`/auth/reauthenticate?intentId=${randomUUID()}`}))};
  return{initialState,viewerId,tribeId,connectionId,configuration,client,create,store,reauthentication};
}
describe("connection wizard first container step",()=>{
  it("should preserve SSR metadata without a second read, validate fields and save one ephemeral key without persisting it",async()=>{
    const fixture=containerFixture(),user=userEvent.setup(),credential=randomUUID();render(<MessagingConnectionsContainer {...fixture} />);
    expect(fixture.client.read).not.toHaveBeenCalled();await waitFor(()=>expect(screen.getByLabelText(/Nombre de la conexión/i)).toBeEnabled());await user.type(screen.getByLabelText(/Nombre de la conexión/i),"Zavu de prueba");await user.type(screen.getByLabelText(/Clave de Zavu/i),credential);await user.click(screen.getByRole("checkbox"));await user.click(screen.getByRole("button",{name:/Guardar conexión/i}));
    await waitFor(()=>expect(fixture.create).toHaveBeenCalledTimes(1));expect(fixture.create.mock.calls[0][1]).toMatchObject({name:"Zavu de prueba",apiKey:credential,confirmed:true,providerId:"zavu"});
    await waitFor(()=>expect(screen.queryByLabelText(/Clave de Zavu/i)).not.toBeInTheDocument());expect(screen.getByText("Conexión candidata")).toBeVisible();expect(JSON.stringify(fixture.store.write.mock.calls)).not.toContain(credential);
  });
  it("should preserve the original UUID after a lost write and recover before another mutation, without retaining the key",async()=>{
    const fixture=containerFixture(),user=userEvent.setup(),credential=randomUUID();fixture.create.mockResolvedValueOnce({status:"failed",code:"dependency_unavailable",message:"No pudimos confirmar el guardado.",uncertain:true});
    render(<MessagingConnectionsContainer {...fixture} />);await waitFor(()=>expect(screen.getByLabelText(/Nombre de la conexión/i)).toBeEnabled());await user.type(screen.getByLabelText(/Nombre de la conexión/i),"Zavu de prueba");await user.type(screen.getByLabelText(/Clave de Zavu/i),credential);await user.click(screen.getByRole("checkbox"));await user.click(screen.getByRole("button",{name:/Guardar conexión/i}));
    await waitFor(()=>expect(screen.getByRole("button",{name:/Consultar guardado/i})).toBeVisible());expect(screen.getByLabelText(/Clave de Zavu/i)).toHaveValue("");expect(fixture.create).toHaveBeenCalledTimes(1);expect(JSON.stringify(fixture.store.write.mock.calls)).not.toContain(credential);
  });
  it("should reconcile current metadata after an original replay instead of restoring the historical candidate over an active selection",async()=>{
    const fixture=containerFixture(),user=userEvent.setup(),operationId=randomUUID(),selected={id:fixture.connectionId,name:"Conexión actual",version:4,configurationVersion:2,state:"active" as const,credentialState:"valid" as const,credentialMode:"production" as const,maskedCredential:"••••••••" as const,capabilities:[]},current={...fixture.configuration,selected,candidate:null};
    fixture.store.read.mockReturnValue({type:"save_messaging_credentials",operationId});fixture.client.read=vi.fn<MessagingConnectionsBrowserClient["read"]>(async()=>({status:"ready" as const,value:current}));fixture.client.operation=vi.fn<MessagingConnectionsBrowserClient["operation"]>(async()=>({status:"ready" as const,value:{type:"save_messaging_credentials" as const,state:"completed" as const,operationId,replayed:true as const,result:{id:fixture.connectionId,name:"Nombre histórico",version:1,configurationVersion:1,state:"draft" as const,maskedCredential:"••••••••" as const}}}));
    render(<MessagingConnectionsContainer {...fixture} />);await user.click(await screen.findByRole("button",{name:/Consultar guardado/i}));
    await waitFor(()=>expect(screen.getByText("Conexión actual")).toBeVisible());expect(screen.queryByText("Nombre histórico")).not.toBeInTheDocument();expect(screen.queryByText("Conexión candidata")).not.toBeInTheDocument();expect(fixture.create).not.toHaveBeenCalled();
  });
  it("should block a new write while the initial viewer lookup is pending and restore the existing original reference",async()=>{
    const fixture=containerFixture(),user=userEvent.setup(),viewer=Promise.withResolvers<Awaited<ReturnType<MessagingConnectionsBrowserClient["viewer"]>>>(),operationId=randomUUID();fixture.client.viewer=vi.fn<MessagingConnectionsBrowserClient["viewer"]>().mockReturnValueOnce(viewer.promise).mockResolvedValue({status:"ready",value:{id:fixture.viewerId}});fixture.store.read.mockReturnValue({type:"save_messaging_credentials",operationId});
    render(<MessagingConnectionsContainer {...fixture} />);await user.type(screen.getByLabelText(/Nombre de la conexión/i),"Zavu de prueba");await user.type(screen.getByLabelText(/Clave de Zavu/i),randomUUID());await user.click(screen.getByRole("checkbox"));
    expect(screen.getByRole("button",{name:/Guardar conexión/i})).toBeDisabled();expect(fixture.create).not.toHaveBeenCalled();expect(fixture.store.write).not.toHaveBeenCalled();viewer.resolve({status:"ready",value:{id:fixture.viewerId}});expect(await screen.findByRole("button",{name:/Consultar guardado/i})).toBeVisible();
  });
  it("should keep a local reference cleanup failure visible after the server confirms creation",async()=>{
    const fixture=containerFixture(),user=userEvent.setup();fixture.store.write.mockImplementation((_viewer,_slug,intent)=>intent!==null);
    render(<MessagingConnectionsContainer {...fixture} />);await waitFor(()=>expect(screen.getByLabelText(/Nombre de la conexión/i)).toBeEnabled());await user.type(screen.getByLabelText(/Nombre de la conexión/i),"Zavu de prueba");await user.type(screen.getByLabelText(/Clave de Zavu/i),randomUUID());await user.click(screen.getByRole("checkbox"));await user.click(screen.getByRole("button",{name:/Guardar conexión/i}));
    expect(await screen.findByRole("alert")).toHaveTextContent(/referencia local/i);expect(screen.getByRole("button",{name:/Consultar guardado/i})).toBeVisible();expect(fixture.create).toHaveBeenCalledTimes(1);
  });
  it("should check a candidate credential only after explicit consent and keep test mode separate from channel preparation",async()=>{
    const fixture=containerFixture(),user=userEvent.setup(),candidate={id:fixture.connectionId,name:"Zavu candidata",version:1,configurationVersion:1,state:"draft" as const,credentialState:"not_validated" as const,credentialMode:"unknown" as const,maskedCredential:"••••••••" as const,capabilities:[]},initialState:MessagingConnectionsPageState={...fixture.initialState,kind:"ready",configuration:{...fixture.configuration,candidate}};
    const validate=vi.fn<MessagingConnectionsBrowserClient["validate"]>(async(_slug,id,input)=>({status:"ready",value:{state:"completed",operationId:input.operationId,replayed:false,result:{id,version:2,configurationVersion:1,credentialState:"valid",credentialMode:"test",validatedAt:new Date().toISOString()}}}));fixture.client.validate=validate;
    render(<MessagingConnectionsContainer {...fixture} initialState={initialState} />);await waitFor(()=>expect(screen.getByRole("checkbox",{name:/Confirmo que quiero comprobar/i})).toBeEnabled());expect(validate).not.toHaveBeenCalled();expect(screen.getByRole("button",{name:"Comprobar credencial"})).toBeDisabled();
    await user.click(screen.getByRole("checkbox",{name:/Confirmo que quiero comprobar/i}));await user.click(screen.getByRole("button",{name:"Comprobar credencial"}));
    await waitFor(()=>expect(screen.getByText("Cuenta de prueba")).toBeVisible());expect(screen.getByText("Credencial comprobada")).toBeVisible();expect(screen.getByText("Borrador")).toBeVisible();expect(screen.queryByText("Canal comprobado")).not.toBeInTheDocument();expect(validate).toHaveBeenCalledTimes(1);expect(validate.mock.calls[0]).toEqual(["synthetic",fixture.connectionId,expect.objectContaining({expectedVersion:1,confirmed:true}),expect.any(AbortSignal)]);expect(fixture.create).not.toHaveBeenCalled();expect(fixture.client.read).not.toHaveBeenCalled();
  });
  it("should preserve the validation original and read current metadata after an uncertain response without repeating the check",async()=>{
    const fixture=containerFixture(),user=userEvent.setup(),candidate={id:fixture.connectionId,name:"Zavu candidata",version:1,configurationVersion:1,state:"draft" as const,credentialState:"not_validated" as const,credentialMode:"unknown" as const,maskedCredential:"••••••••" as const,capabilities:[]},initialState:MessagingConnectionsPageState={...fixture.initialState,kind:"ready",configuration:{...fixture.configuration,candidate}};
    const validate=vi.fn<MessagingConnectionsBrowserClient["validate"]>(async()=>({status:"failed",code:"dependency_unavailable",message:"Consulta pendiente.",uncertain:true}));fixture.client.validate=validate;
    render(<MessagingConnectionsContainer {...fixture} initialState={initialState} />);await waitFor(()=>expect(screen.getByRole("checkbox",{name:/Confirmo que quiero comprobar/i})).toBeEnabled());await user.click(screen.getByRole("checkbox",{name:/Confirmo que quiero comprobar/i}));await user.click(screen.getByRole("button",{name:"Comprobar credencial"}));await waitFor(()=>expect(screen.getByRole("button",{name:"Consultar guardado"})).toBeEnabled());
    const operationId=validate.mock.calls[0][2].operationId;expect(fixture.store.write).toHaveBeenCalledWith(fixture.viewerId,"synthetic",{type:"validate_messaging_connection",operationId,original:{connectionId:fixture.connectionId,configurationVersion:1,expectedVersion:1}});
    fixture.client.operation=vi.fn<MessagingConnectionsBrowserClient["operation"]>(async()=>({status:"ready",value:{type:"validate_messaging_connection",state:"completed",operationId,replayed:true,result:{id:fixture.connectionId,version:2,configurationVersion:1,credentialState:"invalid",credentialMode:"unknown",validatedAt:new Date().toISOString(),failureCode:"invalid_credentials"}}}));fixture.client.read=vi.fn<MessagingConnectionsBrowserClient["read"]>(async()=>({status:"ready",value:{...fixture.configuration,candidate:{...candidate,version:2,credentialState:"invalid"}}}));
    await user.click(screen.getByRole("button",{name:"Consultar guardado"}));await waitFor(()=>expect(screen.getByText("Credencial no válida")).toBeVisible());expect(validate).toHaveBeenCalledTimes(1);expect(screen.getByRole("alert")).toBeVisible();expect(fixture.client.read).toHaveBeenCalledTimes(1);
  });

  it("should prepare Google confirmation for the candidate validation operation and exact resource without a provider check",async()=>{
    const fixture=containerFixture(),user=userEvent.setup(),candidate={id:fixture.connectionId,name:"Zavu candidata",version:1,configurationVersion:1,state:"draft" as const,credentialState:"not_validated" as const,credentialMode:"unknown" as const,maskedCredential:"••••••••" as const,capabilities:[]},initialState:MessagingConnectionsPageState={...fixture.initialState,kind:"ready",configuration:{...fixture.configuration,candidate}};
    render(<MessagingConnectionsContainer {...fixture} initialState={initialState} />);await waitFor(()=>expect(screen.getByRole("button",{name:"Confirmar comprobación con Google"})).toBeEnabled());await user.click(screen.getByRole("button",{name:"Confirmar comprobación con Google"}));
    expect(await screen.findByRole("link",{name:"Continuar con Google"})).toBeVisible();expect(fixture.reauthentication.create).toHaveBeenCalledWith({tribeId:fixture.tribeId,resourceId:fixture.connectionId,operation:"validate_messaging_connection",returnPath:"/synthetic/academia/admissions/messaging/connections",confirmed:true},expect.any(AbortSignal));expect(fixture.client.validate).not.toHaveBeenCalled();expect(fixture.store.write).not.toHaveBeenCalled();
  });
  it("should block a stale credential check until the user reads current configuration and confirms again",async()=>{
    const fixture=containerFixture(),user=userEvent.setup(),candidate={id:fixture.connectionId,name:"Zavu candidata",version:1,configurationVersion:1,state:"draft" as const,credentialState:"not_validated" as const,credentialMode:"unknown" as const,maskedCredential:"••••••••" as const,capabilities:[]},initialState:MessagingConnectionsPageState={...fixture.initialState,kind:"ready",configuration:{...fixture.configuration,candidate}};
    fixture.client.validate=vi.fn<MessagingConnectionsBrowserClient["validate"]>(async()=>({status:"failed",code:"connection_conflict",message:"La conexión cambió. Consultá su estado actual.",uncertain:false}));fixture.client.read=vi.fn<MessagingConnectionsBrowserClient["read"]>(async()=>({status:"ready",value:{...fixture.configuration,candidate:{...candidate,version:3,configurationVersion:2}}}));
    render(<MessagingConnectionsContainer {...fixture} initialState={initialState} />);await waitFor(()=>expect(screen.getByRole("checkbox",{name:/Confirmo que quiero comprobar/i})).toBeEnabled());await user.click(screen.getByRole("checkbox",{name:/Confirmo que quiero comprobar/i}));await user.click(screen.getByRole("button",{name:"Comprobar credencial"}));
    await waitFor(()=>expect(screen.getByRole("alert")).toBeVisible());expect(fixture.client.read).not.toHaveBeenCalled();await user.click(screen.getByRole("checkbox",{name:/Confirmo que quiero comprobar/i}));expect(screen.getByRole("button",{name:"Comprobar credencial"})).toBeDisabled();
    await user.click(screen.getByRole("button",{name:"Consultar conexión actual"}));await waitFor(()=>expect(fixture.client.read).toHaveBeenCalledTimes(1));await waitFor(()=>expect(screen.getByRole("checkbox",{name:/Confirmo que quiero comprobar/i})).not.toBeChecked());expect(screen.getByRole("button",{name:"Comprobar credencial"})).toBeDisabled();await user.click(screen.getByRole("checkbox",{name:/Confirmo que quiero comprobar/i}));await user.click(screen.getByRole("button",{name:"Comprobar credencial"}));await waitFor(()=>expect(fixture.client.validate).toHaveBeenCalledTimes(2));expect(vi.mocked(fixture.client.validate).mock.calls[1][2].expectedVersion).toBe(3);
  });
  it("should configure a manual sender explicitly, then read authoritative metadata without inferring fresh credential or channel proof",async()=>{
    const fixture=containerFixture(),user=userEvent.setup(),senderId=randomUUID(),candidate={id:fixture.connectionId,name:"Zavu candidata",version:2,configurationVersion:1,state:"draft" as const,credentialState:"valid" as const,credentialMode:"test" as const,maskedCredential:"••••••••" as const,capabilities:[]},initialState:MessagingConnectionsPageState={...fixture.initialState,kind:"ready",configuration:{...fixture.configuration,candidate}};
    const resourcesClient:MessagingResourcesBrowserClient={read:vi.fn<MessagingResourcesBrowserClient["read"]>(async()=>({status:"ready",value:{connectionId:fixture.connectionId,configurationVersion:1,items:[]}})),configure:vi.fn<MessagingResourcesBrowserClient["configure"]>(async(_scope,input)=>({status:"ready",value:{operationId:input.operationId,state:"completed",replayed:false,result:{id:fixture.connectionId,name:candidate.name,version:3,configurationVersion:2,state:"draft",maskedCredential:"••••••••",changed:true}}}))};
    fixture.client.read=vi.fn<MessagingConnectionsBrowserClient["read"]>(async()=>({status:"ready",value:{...fixture.configuration,candidate:{...candidate,version:3,configurationVersion:2,credentialState:"not_validated",credentialMode:"unknown"}}}));
    render(<MessagingConnectionsContainer {...fixture} initialState={initialState} resourcesClient={resourcesClient} />);await waitFor(()=>expect(screen.getByLabelText("Identificador del remitente")).toBeEnabled());expect(resourcesClient.read).not.toHaveBeenCalled();expect(resourcesClient.configure).not.toHaveBeenCalled();await user.type(screen.getByLabelText("Identificador del remitente"),senderId);await user.click(screen.getByRole("checkbox",{name:/Revisé el canal/i}));await user.click(screen.getByRole("button",{name:"Guardar configuración del canal"}));
    await waitFor(()=>expect(screen.getByText("Falta comprobar la credencial")).toBeVisible());expect(resourcesClient.configure).toHaveBeenCalledTimes(1);expect(resourcesClient.configure).toHaveBeenCalledWith({slug:"synthetic",connectionId:fixture.connectionId,configurationVersion:1},expect.objectContaining({channel:"email",senderId,expectedVersion:2,confirmed:true}),expect.any(AbortSignal));expect(fixture.client.validate).not.toHaveBeenCalled();expect(fixture.client.read).toHaveBeenCalledTimes(1);expect(screen.getByLabelText("Identificador del remitente")).toHaveValue("");
  });
  it("should list a scoped resource page only on request and keep sender selection empty until an explicit choice",async()=>{
    const fixture=containerFixture(),user=userEvent.setup(),senderId=randomUUID(),candidate={id:fixture.connectionId,name:"Zavu candidata",version:2,configurationVersion:1,state:"draft" as const,credentialState:"valid" as const,credentialMode:"test" as const,maskedCredential:"••••••••" as const,capabilities:[]},initialState:MessagingConnectionsPageState={...fixture.initialState,kind:"ready",configuration:{...fixture.configuration,candidate}},resourcesClient:MessagingResourcesBrowserClient={read:vi.fn<MessagingResourcesBrowserClient["read"]>(async()=>({status:"ready",value:{connectionId:fixture.connectionId,configurationVersion:1,items:[{id:senderId,label:"Remitente visible",channels:["email"],readiness:"ready"}]}})),configure:vi.fn<MessagingResourcesBrowserClient["configure"]>(async()=>({status:"failed",code:"resource_unavailable",message:"No disponible.",uncertain:false}))};
    render(<MessagingConnectionsContainer {...fixture} initialState={initialState} resourcesClient={resourcesClient} />);await waitFor(()=>expect(screen.getByRole("button",{name:"Consultar remitentes"})).toBeEnabled());expect(resourcesClient.read).not.toHaveBeenCalled();await user.click(screen.getByRole("button",{name:"Consultar remitentes"}));await waitFor(()=>expect(resourcesClient.read).toHaveBeenCalledTimes(1));await waitFor(()=>expect(screen.getByRole("combobox",{name:"Remitente del canal"})).toBeEnabled());expect(screen.getByLabelText("Identificador del remitente")).toHaveValue("");expect(resourcesClient.configure).not.toHaveBeenCalled();expect(fixture.client.read).not.toHaveBeenCalled();
  });
  it("should recover an uncertain channel configuration with the original UUID and current selection instead of repeating the resource write",async()=>{
    const fixture=containerFixture(),user=userEvent.setup(),senderId=randomUUID(),candidate={id:fixture.connectionId,name:"Zavu candidata",version:2,configurationVersion:1,state:"draft" as const,credentialState:"valid" as const,credentialMode:"test" as const,maskedCredential:"••••••••" as const,capabilities:[]},initialState:MessagingConnectionsPageState={...fixture.initialState,kind:"ready",configuration:{...fixture.configuration,candidate}},configure=vi.fn<MessagingResourcesBrowserClient["configure"]>(async()=>({status:"failed",code:"dependency_unavailable",message:"Resultado pendiente.",uncertain:true})),resourcesClient:MessagingResourcesBrowserClient={read:vi.fn<MessagingResourcesBrowserClient["read"]>(async()=>({status:"failed",code:"resource_unavailable",message:"No disponible.",uncertain:false})),configure};
    render(<MessagingConnectionsContainer {...fixture} initialState={initialState} resourcesClient={resourcesClient} />);await waitFor(()=>expect(screen.getByLabelText("Identificador del remitente")).toBeEnabled());await user.type(screen.getByLabelText("Identificador del remitente"),senderId);await user.click(screen.getByRole("checkbox",{name:/Revisé el canal/i}));await user.click(screen.getByRole("button",{name:"Guardar configuración del canal"}));await waitFor(()=>expect(screen.getByRole("button",{name:"Consultar guardado"})).toBeEnabled());
    const operationId=configure.mock.calls[0][1].operationId;expect(fixture.store.write).toHaveBeenCalledWith(fixture.viewerId,"synthetic",{type:"configure_messaging_connection",operationId,original:{connectionId:fixture.connectionId,configurationVersion:1,expectedVersion:2,channel:"email",senderId}});expect(screen.getByLabelText("Identificador del remitente")).toBeDisabled();
    fixture.client.operation=vi.fn<MessagingConnectionsBrowserClient["operation"]>(async()=>({status:"ready",value:{type:"configure_messaging_connection",state:"completed",operationId,replayed:true,result:{id:fixture.connectionId,name:"Candidata histórica",version:3,configurationVersion:2,state:"draft",maskedCredential:"••••••••",changed:true}}}));fixture.client.read=vi.fn<MessagingConnectionsBrowserClient["read"]>(async()=>({status:"ready",value:{...fixture.configuration,selected:{...candidate,name:"Selección actual",version:5,configurationVersion:2,state:"active",credentialMode:"production"},candidate:null}}));
    await user.click(screen.getByRole("button",{name:"Consultar guardado"}));await waitFor(()=>expect(screen.getByText("Selección actual")).toBeVisible());expect(screen.queryByText("Candidata histórica")).not.toBeInTheDocument();expect(configure).toHaveBeenCalledTimes(1);expect(resourcesClient.read).not.toHaveBeenCalled();
  });
  it.each([{label:"Confirmar consulta de remitentes con Google",operation:"read_messaging_senders"},{label:"Confirmar configuración con Google",operation:"configure_messaging_connection"}])("should bind $operation Google confirmation to the candidate and clear resource consent",async({label,operation})=>{
    const fixture=containerFixture(),user=userEvent.setup(),candidate={id:fixture.connectionId,name:"Zavu candidata",version:2,configurationVersion:1,state:"draft" as const,credentialState:"valid" as const,credentialMode:"test" as const,maskedCredential:"••••••••" as const,capabilities:[]},initialState:MessagingConnectionsPageState={...fixture.initialState,kind:"ready",configuration:{...fixture.configuration,candidate}},resourcesClient:MessagingResourcesBrowserClient={read:vi.fn<MessagingResourcesBrowserClient["read"]>(async()=>({status:"failed",code:"resource_unavailable",message:"No disponible.",uncertain:false})),configure:vi.fn<MessagingResourcesBrowserClient["configure"]>(async()=>({status:"failed",code:"resource_unavailable",message:"No disponible.",uncertain:false}))};
    render(<MessagingConnectionsContainer {...fixture} initialState={initialState} resourcesClient={resourcesClient} />);await waitFor(()=>expect(screen.getByRole("button",{name:label})).toBeEnabled());await user.click(screen.getByRole("checkbox",{name:/Revisé el canal/i}));await user.click(screen.getByRole("button",{name:label}));
    expect(await screen.findByRole("link",{name:"Continuar con Google"})).toBeVisible();expect(fixture.reauthentication.create).toHaveBeenCalledWith({tribeId:fixture.tribeId,resourceId:fixture.connectionId,operation,returnPath:"/synthetic/academia/admissions/messaging/connections",confirmed:true},expect.any(AbortSignal));expect(screen.getByRole("checkbox",{name:/Revisé el canal/i})).not.toBeChecked();expect(resourcesClient.read).not.toHaveBeenCalled();expect(resourcesClient.configure).not.toHaveBeenCalled();
  });

  it("should remove a previous Google intent link when preparation of a different sensitive operation fails",async()=>{
    const fixture=containerFixture(),user=userEvent.setup(),candidate={id:fixture.connectionId,name:"Zavu candidata",version:2,configurationVersion:1,state:"draft" as const,credentialState:"valid" as const,credentialMode:"test" as const,maskedCredential:"••••••••" as const,capabilities:[]},initialState:MessagingConnectionsPageState={...fixture.initialState,kind:"ready",configuration:{...fixture.configuration,candidate}},reauthentication:ReauthenticationIntentBrowserClient={create:vi.fn<ReauthenticationIntentBrowserClient["create"]>().mockResolvedValueOnce({status:"ready",href:`/auth/reauthenticate?intentId=${randomUUID()}`}).mockResolvedValueOnce({status:"failed"})};
    render(<MessagingConnectionsContainer {...fixture} initialState={initialState} reauthentication={reauthentication} />);await waitFor(()=>expect(screen.getByRole("button",{name:"Confirmar consulta de remitentes con Google"})).toBeEnabled());await user.click(screen.getByRole("button",{name:"Confirmar consulta de remitentes con Google"}));expect(await screen.findByRole("link",{name:"Continuar con Google"})).toBeVisible();
    await waitFor(()=>expect(screen.getByRole("button",{name:"Confirmar configuración con Google"})).toBeEnabled());await user.click(screen.getByRole("button",{name:"Confirmar configuración con Google"}));await waitFor(()=>expect(screen.getByRole("alert")).toBeVisible());expect(screen.queryByRole("link",{name:"Continuar con Google"})).not.toBeInTheDocument();expect(fixture.client.create).not.toHaveBeenCalled();
  });
  it("should allow an explicit current read after an original lookup has no recoverable record while preserving the pending UUID and blocking new writes",async()=>{
    const fixture=containerFixture(),user=userEvent.setup(),operationId=randomUUID();fixture.store.read.mockReturnValue({type:"save_messaging_credentials",operationId});fixture.client.operation=vi.fn<MessagingConnectionsBrowserClient["operation"]>(async()=>({status:"failed",code:"resource_unavailable",message:"El recurso solicitado no está disponible.",uncertain:false}));
    render(<MessagingConnectionsContainer {...fixture} />);await waitFor(()=>expect(screen.getByRole("button",{name:"Consultar guardado"})).toBeEnabled());await user.click(screen.getByRole("button",{name:"Consultar guardado"}));await waitFor(()=>expect(fixture.client.operation).toHaveBeenCalledTimes(1));
    await user.click(screen.getByRole("button",{name:"Consultar conexión actual"}));await waitFor(()=>expect(fixture.client.read).toHaveBeenCalledTimes(2));expect(screen.getByRole("button",{name:"Consultar guardado"})).toBeVisible();expect(fixture.store.write).not.toHaveBeenCalledWith(fixture.viewerId,"synthetic",null);expect(fixture.client.create).not.toHaveBeenCalled();expect(screen.getByRole("button",{name:"Guardar conexión"})).toBeDisabled();
  });

  it("should explicitly resume an unregistered creation with its original UUID and name, a newly entered ephemeral key and renewed consent",async()=>{
    const fixture=containerFixture(),user=userEvent.setup(),operationId=randomUUID(),credential=randomUUID();fixture.store.read.mockReturnValue({type:"save_messaging_credentials",operationId,original:{name:"Nombre original"}});fixture.client.operation=vi.fn<MessagingConnectionsBrowserClient["operation"]>(async()=>({status:"failed",code:"resource_unavailable",message:"No disponible.",uncertain:false}));
    render(<MessagingConnectionsContainer {...fixture} />);await waitFor(()=>expect(screen.getByRole("button",{name:"Consultar guardado"})).toBeEnabled());expect(fixture.client.create).not.toHaveBeenCalled();await user.click(screen.getByRole("button",{name:"Consultar guardado"}));await waitFor(()=>expect(fixture.client.read).toHaveBeenCalledTimes(1));
    expect(screen.getByRole("button",{name:"Reanudar operación original"})).toBeDisabled();await user.type(screen.getByLabelText("Clave de Zavu"),credential);await user.click(screen.getByRole("checkbox",{name:/Confirmo reanudar/i}));await user.click(screen.getByRole("button",{name:"Reanudar operación original"}));
    await waitFor(()=>expect(fixture.client.create).toHaveBeenCalledTimes(1));expect(vi.mocked(fixture.client.create).mock.calls[0][1]).toEqual({operationId,confirmed:true,providerId:"zavu",name:"Nombre original",apiKey:credential});expect(JSON.stringify(fixture.store.write.mock.calls)).not.toContain(credential);
    fixture.client.operation=vi.fn<MessagingConnectionsBrowserClient["operation"]>(async()=>({status:"ready",value:{type:"save_messaging_credentials",state:"completed",operationId,replayed:true,result:{id:fixture.connectionId,name:"Nombre original",version:1,configurationVersion:1,state:"draft",maskedCredential:"••••••••"}}}));fixture.client.read=vi.fn<MessagingConnectionsBrowserClient["read"]>(async()=>({status:"ready",value:{...fixture.configuration,candidate:{id:fixture.connectionId,name:"Nombre original",version:1,configurationVersion:1,state:"draft",maskedCredential:"••••••••",credentialState:"not_validated",credentialMode:"unknown",capabilities:[]}}}));
    await waitFor(()=>expect(screen.getByRole("button",{name:"Consultar guardado"})).toBeEnabled());await user.click(screen.getByRole("button",{name:"Consultar guardado"}));await waitFor(()=>expect(screen.getByText("Conexión candidata")).toBeVisible());
  });

  it("should confirm Google recovery for the original connection even when the current candidate is different",async()=>{
    const fixture=containerFixture(),user=userEvent.setup(),operationId=randomUUID(),originalId=randomUUID(),candidate={id:fixture.connectionId,name:"Candidata nueva",version:3,configurationVersion:2,state:"draft" as const,credentialState:"not_validated" as const,credentialMode:"unknown" as const,maskedCredential:"••••••••" as const,capabilities:[]};fixture.store.read.mockReturnValue({type:"validate_messaging_connection",operationId,original:{connectionId:originalId,configurationVersion:1,expectedVersion:2}});fixture.client.operation=vi.fn<MessagingConnectionsBrowserClient["operation"]>(async()=>({status:"failed",code:"resource_unavailable",message:"No disponible.",uncertain:false}));fixture.client.read=vi.fn<MessagingConnectionsBrowserClient["read"]>(async()=>({status:"ready",value:{...fixture.configuration,candidate}}));
    render(<MessagingConnectionsContainer {...fixture} />);await waitFor(()=>expect(screen.getByRole("button",{name:"Consultar guardado"})).toBeEnabled());await user.click(screen.getByRole("button",{name:"Consultar guardado"}));await waitFor(()=>expect(screen.getByRole("button",{name:"Confirmar recuperación con Google"})).toBeEnabled());await user.click(screen.getByRole("button",{name:"Confirmar recuperación con Google"}));
    expect(await screen.findByRole("link",{name:"Continuar con Google"})).toBeVisible();expect(fixture.reauthentication.create).toHaveBeenCalledWith({tribeId:fixture.tribeId,resourceId:originalId,operation:"validate_messaging_connection",returnPath:"/synthetic/academia/admissions/messaging/connections",confirmed:true},expect.any(AbortSignal));expect(fixture.client.validate).not.toHaveBeenCalled();
  });

  it("should explain a legacy reference with no original fields without promising a continuation or discarding it",async()=>{
    const fixture=containerFixture(),user=userEvent.setup(),operationId=randomUUID();fixture.store.read.mockReturnValue({type:"save_messaging_credentials",operationId});fixture.client.operation=vi.fn<MessagingConnectionsBrowserClient["operation"]>(async()=>({status:"failed",code:"resource_unavailable",message:"No disponible.",uncertain:false}));
    render(<MessagingConnectionsContainer {...fixture} />);await waitFor(()=>expect(screen.getByRole("button",{name:"Consultar guardado"})).toBeEnabled());await user.click(screen.getByRole("button",{name:"Consultar guardado"}));await waitFor(()=>expect(screen.getByRole("alert")).toHaveTextContent(/no conserva los datos originales/i));expect(screen.queryByRole("button",{name:"Reanudar operación original"})).not.toBeInTheDocument();expect(screen.getByRole("button",{name:"Consultar conexión actual"})).toBeVisible();expect(fixture.store.write).not.toHaveBeenCalledWith(fixture.viewerId,"synthetic",null);
  });

  it("should preserve an irrecoverable original in history before explicitly clearing local tracking, without cancelling or starting another write",async()=>{
    const fixture=containerFixture(),user=userEvent.setup(),operationId=randomUUID(),intent={type:"save_messaging_credentials" as const,operationId,original:{name:"Original pendiente"}};fixture.store.read.mockReturnValue(intent);fixture.client.operation=vi.fn<MessagingConnectionsBrowserClient["operation"]>(async()=>({status:"failed",code:"resource_unavailable",message:"No disponible.",uncertain:false}));
    render(<MessagingConnectionsContainer {...fixture} />);await waitFor(()=>expect(screen.getByRole("button",{name:"Consultar guardado"})).toBeEnabled());await user.click(screen.getByRole("button",{name:"Consultar guardado"}));await waitFor(()=>expect(screen.getByRole("button",{name:"Conservar en historial y continuar"})).toBeVisible());expect(screen.getByRole("button",{name:"Conservar en historial y continuar"})).toBeDisabled();await user.click(screen.getByRole("checkbox",{name:/Entiendo que dejar de seguir/i}));await user.click(screen.getByRole("button",{name:"Conservar en historial y continuar"}));
    await waitFor(()=>expect(fixture.store.archive).toHaveBeenCalledWith(fixture.viewerId,"synthetic",intent));expect(fixture.store.write).toHaveBeenCalledWith(fixture.viewerId,"synthetic",null);expect(screen.queryByRole("button",{name:"Consultar guardado"})).not.toBeInTheDocument();expect(screen.getByRole("button",{name:"Consultar intento conservado"})).toBeVisible();expect(fixture.client.create).not.toHaveBeenCalled();await user.click(screen.getByRole("button",{name:"Consultar intento conservado"}));expect(await screen.findByRole("button",{name:"Consultar guardado"})).toBeVisible();expect(fixture.client.create).not.toHaveBeenCalled();expect(screen.queryByRole("button",{name:"Reanudar operación original"})).not.toBeInTheDocument();expect(screen.queryByRole("button",{name:"Conservar en historial y continuar"})).not.toBeInTheDocument();
  });

});
