/** @vitest-environment node */
/** Exercises the structural leadership cutover against actual tenant messaging history and protected SQL. @module admission-leadership-transfer-tests */
import { randomBytes, randomUUID } from "node:crypto";
import { sql } from "drizzle-orm";
import { describe, expect, it } from "vitest";
import { withAcademyAdmissionDatabase } from "@/tests/support/academy-admission-database";
import { prepareMessagingConnectionCreation } from "@/tests/support/messaging-connection-fixture";
import { seedPreviousMessagingSelection } from "@/tests/support/messaging-selection-fixture";

describe.skipIf(process.env.RUN_ADMISSION_SQL_TESTS!=="1")("canonical leadership messaging cutover",()=>{
  it.each(["role","status"] as const)("should reject a direct leader %s change before upgrading a tribe fence held by another current authority",async(field)=>{
    await withAcademyAdmissionDatabase(async(database)=>{
      const fixture=await prepareMessagingConnectionCreation(database);await database.applyMigration("20261005093000_guard_academy_membership_sources.sql");await database.applyMigration("20261008200000_guard_messaging_leadership_changes.sql");const held=Promise.withResolvers<void>(),release=Promise.withResolvers<void>(),holding=database.withContext(fixture.fixture.own,async(transaction)=>{await transaction.execute(sql`select id from public.tribes where id=${fixture.context.tribeId} for share`);held.resolve();await release.promise;});await held.promise;
      try{
        await expect(database.withContext(fixture.fixture.own,async(transaction)=>{await transaction.execute(sql`set local statement_timeout='1s'`);await transaction.execute(field==="role"?sql`update public.tribe_members set role='guardian' where tribe_id=${fixture.context.tribeId} and user_id=${fixture.context.actorUserId}`:sql`update public.tribe_members set status='muted' where tribe_id=${fixture.context.tribeId} and user_id=${fixture.context.actorUserId}`);})).rejects.toMatchObject({cause:{code:"55P03"}});
      }finally{release.resolve();await holding;}
      expect(await database.withContext(fixture.fixture.own,async(transaction)=>(await transaction.execute(sql`select role,status from public.tribe_members where tribe_id=${fixture.context.tribeId} and user_id=${fixture.context.actorUserId}`)).rows[0])).toEqual({role:"leader",status:"active"});
    });
  },600_000);
  it.each(["muted","deleted"] as const)("should stop old credentials when the canonical leader becomes %s and roll back the stop with an aborted role mutation",async(change)=>{
    await withAcademyAdmissionDatabase(async(database)=>{
      const fixture=await prepareMessagingConnectionCreation(database);await database.applyMigration("20261008200000_guard_messaging_leadership_changes.sql");const created=await fixture.repository.create(fixture.context,{operationId:randomUUID(),confirmed:true,providerId:"zavu",name:"Credencial del líder",apiKey:randomUUID()});if(created.state!=="completed")throw new Error("Expected candidate fixture");
      /** @returns Only lifecycle and retained envelope metadata, never credential material. */
      const snapshot=()=>database.withContext(fixture.fixture.own,async(transaction)=>({connection:(await transaction.execute(sql`select version,state,state_reason,is_candidate,candidate_version from public.tenant_messaging_connections where id=${created.result.id}`)).rows[0],envelopes:(await transaction.execute(sql`select secret_ref,connection_version,retired_at from public.messaging_secret_envelopes where connection_id=${created.result.id}`)).rows}));
      const before=await snapshot();await database.withContext(fixture.fixture.own,(transaction)=>transaction.execute(sql`update public.tribe_members set role=role where tribe_id=${fixture.context.tribeId} and user_id=${fixture.context.actorUserId}`));expect(await snapshot()).toEqual(before);
      await expect(database.withContext(fixture.fixture.own,async(transaction)=>{await transaction.execute(sql`update public.tribe_members set role='guardian' where tribe_id=${fixture.context.tribeId} and user_id=${fixture.context.actorUserId}`);expect((await transaction.execute(sql`select state from public.tenant_messaging_connections where id=${created.result.id}`)).rows[0]).toEqual({state:"suspended"});throw new Error("Synthetic leadership transaction aborted");})).rejects.toThrow("Synthetic leadership transaction aborted");expect(await snapshot()).toEqual(before);
      await database.withContext(fixture.fixture.own,(transaction)=>transaction.execute(change==="muted"?sql`update public.tribe_members set status='muted' where tribe_id=${fixture.context.tribeId} and user_id=${fixture.context.actorUserId}`:sql`delete from public.tribe_members where tribe_id=${fixture.context.tribeId} and user_id=${fixture.context.actorUserId}`));expect(await snapshot()).toEqual({connection:{...before.connection,state:"suspended",state_reason:"leadership_changed",version:2},envelopes:before.envelopes});
    });
  },600_000);
  it("should suspend the previous leader's selected and candidate connections in the same direct SQL transfer while retaining all admission and charged history",async()=>{
    await withAcademyAdmissionDatabase(async(database)=>{
      const fixture=await prepareMessagingConnectionCreation(database);await database.applyMigration("20261005092500_guard_messaging_attempts.sql");await database.applyMigration("20261008200000_guard_messaging_leadership_changes.sql");await database.withContext(fixture.fixture.own,(transaction)=>transaction.execute(sql`insert into public.messaging_usage_policies(tribe_id) values (${fixture.context.tribeId})`));
      const candidate=await fixture.repository.create(fixture.context,{operationId:randomUUID(),confirmed:true,providerId:"zavu",name:"Candidata del líder anterior",apiKey:randomUUID()});if(candidate.state!=="completed")throw new Error("Expected encrypted candidate fixture");const previous=await seedPreviousMessagingSelection(database,fixture,candidate.result.id),nextLeaderId=randomUUID();
      const invitationId=randomUUID();await database.withContext(fixture.fixture.own,async(transaction)=>{await transaction.execute(sql`insert into public."user"(id,name,email,"emailVerified","createdAt","updatedAt") values (${nextLeaderId},'Synthetic next leader',${`${nextLeaderId}@example.test`},false,clock_timestamp(),clock_timestamp())`);await transaction.execute(sql`insert into public.tribe_members(tribe_id,user_id,role,status) values (${fixture.context.tribeId},${nextLeaderId},'guardian','active')`);await transaction.execute(sql`insert into public.academy_personal_invitations(id,tribe_id,created_by_user_id,contact_type,normalized_contact,contact_fingerprint,fingerprint_key_id,token_hash,token_key_id) values (${invitationId},${fixture.context.tribeId},${fixture.context.actorUserId},'email','invited@example.test',${randomBytes(32)},'synthetic-contact',${randomBytes(32)},'synthetic-token')`);});const before=await previous.snapshot();
      /** @returns Only invitation lifecycle and membership identity/status facts retained across the canonical role change. */
      const retained=()=>database.withContext(fixture.fixture.own,async(transaction)=>({invitation:(await transaction.execute(sql`select id,tribe_id,created_by_user_id,status,version,created_at,expires_at,redeemed_at,authorization_revoked_at from public.academy_personal_invitations where id=${invitationId}`)).rows[0],members:(await transaction.execute(sql`select id,user_id,status,created_at from public.tribe_members where tribe_id=${fixture.context.tribeId} order by user_id`)).rows}));const retainedBefore=await retained();
      await database.withContext(fixture.fixture.own,async(transaction)=>{
        await transaction.execute(sql`select id from public.tribes where id=${fixture.context.tribeId} for update`);await transaction.execute(sql`update public.tribe_members set role='guardian' where tribe_id=${fixture.context.tribeId} and user_id=${fixture.context.actorUserId}`);await transaction.execute(sql`update public.tribe_members set role='leader' where tribe_id=${fixture.context.tribeId} and user_id=${nextLeaderId}`);
        expect((await transaction.execute(sql`select id,state,state_reason,version,is_selected,is_candidate from public.tenant_messaging_connections where tribe_id=${fixture.context.tribeId} order by id`)).rows).toEqual(expect.arrayContaining([{id:previous.connectionId,state:"suspended",state_reason:"leadership_changed",version:2,is_selected:true,is_candidate:false},{id:candidate.result.id,state:"suspended",state_reason:"leadership_changed",version:2,is_selected:false,is_candidate:true}]));
      });
      const after=await previous.snapshot();for(const field of["versions","secrets","policy","proofs","challenges","request","deliveries","reservations","usage"] as const)expect(after[field]).toEqual(before[field]);expect(await retained()).toEqual(retainedBefore);const canonical=await database.withContext(fixture.fixture.own,async(transaction)=>({leader:(await transaction.execute(sql`select user_id from public.tribe_members where tribe_id=${fixture.context.tribeId} and role='leader'`)).rows,creator:(await transaction.execute(sql`select created_by from public.tribes where id=${fixture.context.tribeId}`)).rows[0]}));expect(canonical).toEqual({leader:[{user_id:nextLeaderId}],creator:{created_by:fixture.context.actorUserId}});
    });
  },600_000);
});
