/** @vitest-environment node */
/** Exercises the tribe owner and original recovery with actual SQL, encryption and canonical leadership guards. @module postgres-tribe-leadership-tests */
import { randomUUID } from "node:crypto";
import { sql } from "drizzle-orm";
import { describe, expect, it } from "vitest";
import { withAcademyAdmissionDatabase } from "@/tests/support/academy-admission-database";
import { prepareMessagingConnectionCreation } from "@/tests/support/messaging-connection-fixture";
import { PostgresTribeLeadershipRepository } from "@/src/modules/tribes/infrastructure/repositories/postgres-tribe-leadership-repository";
import { buildTribeLeadershipModule } from "@/src/modules/tribes/setup";
import { PostgresAuthenticatedAccountProvider } from "@/src/modules/auth/infrastructure/authenticated-account-provider";
import type { RequestDatabase } from "@/src/modules/shared/infrastructure/database/server-database-client";
import type { TribeLeadershipTransferContext } from "@/src/modules/tribes/domain/repositories/tribe-leadership-repository";

describe.skipIf(process.env.RUN_ADMISSION_SQL_TESTS!=="1")("native tribe leadership owner",()=>{
  it("should report the expired actual session if commit recovery loses its authority without repeating the confirmed transfer",async()=>{
    await withAcademyAdmissionDatabase(async(database)=>{
      const fixture=await prepareMessagingConnectionCreation(database);for(const migration of["20261005093000_guard_academy_membership_sources.sql","20261008200000_guard_messaging_leadership_changes.sql"])await database.applyMigration(migration);const nextLeaderUserId=randomUUID();await database.withContext(fixture.fixture.own,async(transaction)=>{await transaction.execute(sql`insert into public."user"(id,name,email,"emailVerified","createdAt","updatedAt") values (${nextLeaderUserId},'Synthetic successor',${`${nextLeaderUserId}@example.test`},false,clock_timestamp(),clock_timestamp())`);await transaction.execute(sql`insert into public.tribe_members(tribe_id,user_id,role,status) values (${fixture.context.tribeId},${nextLeaderUserId},'guardian','active')`);});
      const context={tribeId:fixture.context.tribeId,actorUserId:fixture.context.actorUserId,sessionId:fixture.context.sessionId,requestId:randomUUID()},input={operationId:randomUUID(),expectedLeaderUserId:context.actorUserId,nextLeaderUserId,formerLeaderRole:"tribemate" as const,confirmed:true};let loseReply=true;
      const execute=async<Result>(_context:TribeLeadershipTransferContext,run:(transaction:RequestDatabase)=>Promise<Result>)=>{const result=await database.withContext(fixture.fixture.own,run);if(loseReply&&result&&typeof result==="object"&&"state"in result&&result.state==="completed"){loseReply=false;await database.withContext(fixture.fixture.own,(transaction)=>transaction.execute(sql`update public.session set "expiresAt"=clock_timestamp() where id=${context.sessionId}`));throw new Error("Synthetic transfer committed before native session expired");}return result;},writer=new PostgresTribeLeadershipRepository(execute,async()=>fixture.fixture.config);
      await expect(writer.transfer(context,input)).rejects.toMatchObject({code:"authentication_required",operationId:undefined});const confirmed=await database.withContext(fixture.fixture.own,async(transaction)=>({leader:(await transaction.execute(sql`select user_id from public.tribe_members where tribe_id=${context.tribeId} and role='leader'`)).rows,original:(await transaction.execute(sql`select state,public_result from public.academy_admission_operations where idempotency_key=${input.operationId} and operation_type='transfer_tribe_leadership'`)).rows}));expect(confirmed).toEqual({leader:[{user_id:nextLeaderUserId}],original:[{state:"completed",public_result:{previousLeaderUserId:context.actorUserId,leaderUserId:nextLeaderUserId,formerLeaderRole:"tribemate",suspendedConnectionIds:[]}}]});
    });
  },600_000);
  it("should roll back role changes and keep the original unfinished when required structural messaging suspension is unavailable",async()=>{
    await withAcademyAdmissionDatabase(async(database)=>{
      const fixture=await prepareMessagingConnectionCreation(database);await database.applyMigration("20261005093000_guard_academy_membership_sources.sql");const nextLeaderUserId=randomUUID(),created=await fixture.repository.create(fixture.context,{operationId:randomUUID(),confirmed:true,providerId:"zavu",name:"Conexión sin guarda",apiKey:randomUUID()});if(created.state!=="completed")throw new Error("Expected encrypted connection fixture");await database.withContext(fixture.fixture.own,async(transaction)=>{await transaction.execute(sql`insert into public."user"(id,name,email,"emailVerified","createdAt","updatedAt") values (${nextLeaderUserId},'Synthetic successor',${`${nextLeaderUserId}@example.test`},false,clock_timestamp(),clock_timestamp())`);await transaction.execute(sql`insert into public.tribe_members(tribe_id,user_id,role,status) values (${fixture.context.tribeId},${nextLeaderUserId},'guardian','active')`);});
      const context={tribeId:fixture.context.tribeId,actorUserId:fixture.context.actorUserId,sessionId:fixture.context.sessionId,requestId:randomUUID()},input={operationId:randomUUID(),expectedLeaderUserId:context.actorUserId,nextLeaderUserId,formerLeaderRole:"guardian" as const,confirmed:true},writer=new PostgresTribeLeadershipRepository((_context,run)=>database.withContext(fixture.fixture.own,run),async()=>fixture.fixture.config);
      await expect(writer.transfer(context,input)).rejects.toMatchObject({code:"unexpected_failure"});const after=await database.withContext(fixture.fixture.own,async(transaction)=>({members:(await transaction.execute(sql`select user_id,role from public.tribe_members where tribe_id=${context.tribeId} order by user_id`)).rows,connection:(await transaction.execute(sql`select state,version from public.tenant_messaging_connections where id=${created.result.id}`)).rows[0],original:(await transaction.execute(sql`select state,public_result from public.academy_admission_operations where idempotency_key=${input.operationId} and operation_type='transfer_tribe_leadership'`)).rows[0]}));expect(after.members).toEqual(expect.arrayContaining([{user_id:context.actorUserId,role:"leader"},{user_id:nextLeaderUserId,role:"guardian"}]));expect(after.connection).toEqual({state:"draft",version:1});expect(after.original).toEqual({state:"started",public_result:null});
    });
  },600_000);
  it("should atomically transfer existing active membership and suspend the previous key then recover a lost commit reply without another role change",async()=>{
    await withAcademyAdmissionDatabase(async(database)=>{
      const fixture=await prepareMessagingConnectionCreation(database);for(const migration of["20261005093000_guard_academy_membership_sources.sql","20261008200000_guard_messaging_leadership_changes.sql"])await database.applyMigration(migration);
      const nextLeaderUserId=randomUUID(),created=await fixture.repository.create(fixture.context,{operationId:randomUUID(),confirmed:true,providerId:"zavu",name:"Conexión original",apiKey:randomUUID()});if(created.state!=="completed")throw new Error("Expected encrypted original connection");await database.withContext(fixture.fixture.own,async(transaction)=>{await transaction.execute(sql`insert into public."user"(id,name,email,"emailVerified","createdAt","updatedAt") values (${nextLeaderUserId},'Synthetic successor',${`${nextLeaderUserId}@example.test`},false,clock_timestamp(),clock_timestamp())`);await transaction.execute(sql`insert into public.tribe_members(tribe_id,user_id,role,status) values (${fixture.context.tribeId},${nextLeaderUserId},'guardian','active')`);});
      const input={operationId:randomUUID(),expectedLeaderUserId:fixture.context.actorUserId,nextLeaderUserId,formerLeaderRole:"tribemate" as const,confirmed:true},context={tribeId:fixture.context.tribeId,actorUserId:fixture.context.actorUserId,sessionId:fixture.context.sessionId,requestId:randomUUID()};let loseReply=true;
      /** @returns Only roles/identity/lifecycle and original DTO, never private key or contact. */
      const snapshot=()=>database.withContext(fixture.fixture.own,async(transaction)=>({members:(await transaction.execute(sql`select id,user_id,role,status,created_at from public.tribe_members where tribe_id=${context.tribeId} order by user_id`)).rows,connection:(await transaction.execute(sql`select version,state,state_reason,is_candidate,candidate_version,contributed_by_user_id from public.tenant_messaging_connections where id=${created.result.id}`)).rows[0],operations:(await transaction.execute(sql`select operation_type,idempotency_key,state,public_result from public.academy_admission_operations where tribe_id=${context.tribeId} and operation_type='transfer_tribe_leadership'`)).rows}));
      const before=await snapshot(),execute=async<Result>(_context:TribeLeadershipTransferContext,run:(transaction:RequestDatabase)=>Promise<Result>)=>{const result=await database.withContext(fixture.fixture.own,run);if(loseReply&&result&&typeof result==="object"&&"state" in result&&result.state==="completed"){loseReply=false;throw new Error("Synthetic committed leadership reply lost");}return result;},writer=new PostgresTribeLeadershipRepository(execute,async()=>fixture.fixture.config),accounts=new PostgresAuthenticatedAccountProvider(async()=>({userId:context.actorUserId,sessionId:context.sessionId}),(_identity,run)=>database.withContext(fixture.fixture.own,run));
      const leadershipModule=buildTribeLeadershipModule({accounts,execute,readSecurityConfig:async()=>fixture.fixture.config}),result=await leadershipModule.useCases.transferLeadership.execute({tribeId:context.tribeId,requestId:context.requestId,...input});expect(result).toMatchObject({state:"completed",operationId:input.operationId,replayed:true,result:{previousLeaderUserId:context.actorUserId,leaderUserId:nextLeaderUserId,formerLeaderRole:"tribemate",suspendedConnectionIds:[created.result.id]}});
      const after=await snapshot();expect(after.members).toEqual(before.members.map((member)=>({...member,role:member.user_id===nextLeaderUserId?"leader":"tribemate"})));expect(after.connection).toEqual({...before.connection,state:"suspended",state_reason:"leadership_changed",version:2});expect(after.operations).toEqual([expect.objectContaining({idempotency_key:input.operationId,state:"completed",public_result:result.state==="completed"?result.result:undefined})]);expect(await writer.transfer(context,input)).toMatchObject({state:"completed",replayed:true});expect(await snapshot()).toEqual(after);
      await expect(writer.transfer(context,{...input,operationId:randomUUID()})).rejects.toMatchObject({code:"permission_denied"});expect(await snapshot()).toEqual(after);
    });
  },600_000);
});
