"use client";
/** Presents explicit channel/resource choices without session, transport, SDK or persistence ownership. @module messaging-connection-resources */
import {useId} from "react";
import {Button,Checkbox,Input,Label,Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "beez-ui";
import type {MessagingResourcePageResult} from "@/src/modules/messaging/application/results/messaging-resource-page-result";
import {MESSAGING_PUBLIC_CHANNEL,MESSAGING_RESOURCE_READINESS} from "@/src/modules/messaging/constants/messaging-public-contract";
import {MESSAGING_CHANNEL_LABEL} from "@/src/modules/messaging/constants/messaging-connection-presentation";
import styles from "./styles.module.scss";

/** Own references are proposals; the server confirms detail before committing any effective version. */
export type MessagingConnectionResourcesProps={
  channel:typeof MESSAGING_PUBLIC_CHANNEL[keyof typeof MESSAGING_PUBLIC_CHANNEL];senderId:string;templateId:string;templateLanguage:string;confirmed:boolean;busy:boolean;canSave:boolean;
  senders:Pick<MessagingResourcePageResult,"items"|"nextCursor">;templates:Pick<MessagingResourcePageResult,"items"|"nextCursor">;
  fieldErrors:Partial<Record<"senderId"|"templateId"|"templateLanguage",string>>;message:{kind:"status"|"alert";text:string}|null;
  onChannelChange:(channel:MessagingConnectionResourcesProps["channel"])=>void;onSenderChange:(value:string)=>void;onTemplateChange:(value:string)=>void;onTemplateLanguageChange:(value:string)=>void;onConfirmationChange:(confirmed:boolean)=>void;
  onReadSenders:()=>void;onReadTemplates:()=>void;onMoreSenders:()=>void;onMoreTemplates:()=>void;onSave:()=>void;onReauthenticate:()=>void;onReadSendersReauthenticate:()=>void;onReadTemplatesReauthenticate:()=>void;
};

/** @param props - Controlled own resource pages and explicit action callbacks. @returns Only fields required by the selected channel; no choice is selected automatically. */
export function MessagingConnectionResources(props:MessagingConnectionResourcesProps){
  const fieldId=useId(),senderId=`${fieldId}-sender`,templateId=`${fieldId}-template`,languageId=`${fieldId}-language`,channelId=`${fieldId}-channel`,confirmationId=`${fieldId}-confirmation`;
  const whatsapp=props.channel===MESSAGING_PUBLIC_CHANNEL.whatsapp,senders=props.senders.items.filter((sender)=>sender.channels.includes(props.channel));
  return<section className={styles.MessagingConnectionResources} aria-labelledby={`${fieldId}-title`}>
    <h3 id={`${fieldId}-title`} className={styles.MessagingConnectionResources__title}>Preparar un canal</h3>
    <p className={styles.MessagingConnectionResources__help}>Los campos forman un borrador para el próximo guardado. Elegí recursos existentes de Zavu. El guardado comprueba el recurso y crea una versión candidata cuando cambia la configuración; después requiere nuevas comprobaciones. No aprovisiona recursos ni envía mensajes.</p>
    <form className={styles.MessagingConnectionResources__form} aria-busy={props.busy} onSubmit={(event)=>{event.preventDefault();props.onSave();}}>
      <div className={styles.MessagingConnectionResources__field}><Label htmlFor={channelId}>Canal que querés preparar</Label><Select value={props.channel} disabled={props.busy} onValueChange={(value)=>{const channel=Object.values(MESSAGING_PUBLIC_CHANNEL).find((candidate)=>candidate===value);if(channel)props.onChannelChange(channel);}}><SelectTrigger id={channelId}><SelectValue /></SelectTrigger><SelectContent>{Object.values(MESSAGING_PUBLIC_CHANNEL).map((channel)=><SelectItem key={channel} value={channel}>{MESSAGING_CHANNEL_LABEL[channel]}</SelectItem>)}</SelectContent></Select></div>
      <div className={styles.MessagingConnectionResources__actions}><Button className={styles.MessagingConnectionResources__action} type="button" variant="outline" disabled={props.busy} onClick={props.onReadSenders}>Consultar remitentes</Button><Button className={styles.MessagingConnectionResources__action} type="button" variant="outline" disabled={props.busy} onClick={props.onReadSendersReauthenticate}>Confirmar consulta de remitentes con Google</Button>{props.senders.nextCursor&&<Button className={styles.MessagingConnectionResources__action} type="button" variant="outline" disabled={props.busy} onClick={props.onMoreSenders}>Ver más remitentes</Button>}</div>
      <div className={styles.MessagingConnectionResources__field}><Label htmlFor={`${senderId}-choice`}>Remitente del canal</Label><Select value={senders.some((sender)=>sender.id===props.senderId)?props.senderId:""} disabled={props.busy||senders.length===0} onValueChange={props.onSenderChange}><SelectTrigger id={`${senderId}-choice`}><SelectValue placeholder="Elegí un remitente" /></SelectTrigger><SelectContent>{senders.map((sender)=><SelectItem key={sender.id} value={sender.id}>{sender.label||sender.id}{sender.readiness!==MESSAGING_RESOURCE_READINESS.ready?" · Requiere preparación":""}</SelectItem>)}</SelectContent></Select>{senders.length===0&&<p className={styles.MessagingConnectionResources__help}>Todavía no hay opciones consultadas para este canal. Podés volver a consultar o ingresar un identificador que el guardado comprobará.</p>}</div>
      <div className={styles.MessagingConnectionResources__field}><Label htmlFor={senderId}>Identificador del remitente</Label><Input id={senderId} value={props.senderId} disabled={props.busy} onChange={(event)=>props.onSenderChange(event.target.value)} aria-invalid={Boolean(props.fieldErrors.senderId)} aria-describedby={props.fieldErrors.senderId?`${senderId}-error`:undefined} />{props.fieldErrors.senderId&&<p id={`${senderId}-error`} className={styles.MessagingConnectionResources__error}>{props.fieldErrors.senderId}</p>}</div>
      {whatsapp&&<>
        <div className={styles.MessagingConnectionResources__actions}><Button className={styles.MessagingConnectionResources__action} type="button" variant="outline" disabled={props.busy} onClick={props.onReadTemplates}>Consultar plantillas</Button><Button className={styles.MessagingConnectionResources__action} type="button" variant="outline" disabled={props.busy} onClick={props.onReadTemplatesReauthenticate}>Confirmar consulta de plantillas con Google</Button>{props.templates.nextCursor&&<Button className={styles.MessagingConnectionResources__action} type="button" variant="outline" disabled={props.busy} onClick={props.onMoreTemplates}>Ver más plantillas</Button>}</div>
        <div className={styles.MessagingConnectionResources__field}><Label htmlFor={`${templateId}-choice`}>Plantilla de autenticación</Label><Select value={props.templates.items.some((template)=>template.id===props.templateId)?props.templateId:""} disabled={props.busy||props.templates.items.length===0} onValueChange={props.onTemplateChange}><SelectTrigger id={`${templateId}-choice`}><SelectValue placeholder="Elegí una plantilla" /></SelectTrigger><SelectContent>{props.templates.items.map((template)=><SelectItem key={template.id} value={template.id}>{template.label||template.id}{template.language?` · ${template.language}`:""}{template.readiness!==MESSAGING_RESOURCE_READINESS.ready?" · Requiere preparación":""}</SelectItem>)}</SelectContent></Select></div>
        <div className={styles.MessagingConnectionResources__field}><Label htmlFor={templateId}>Identificador de plantilla</Label><Input id={templateId} value={props.templateId} disabled={props.busy} onChange={(event)=>props.onTemplateChange(event.target.value)} aria-invalid={Boolean(props.fieldErrors.templateId)} aria-describedby={props.fieldErrors.templateId?`${templateId}-error`:undefined} />{props.fieldErrors.templateId&&<p id={`${templateId}-error`} className={styles.MessagingConnectionResources__error}>{props.fieldErrors.templateId}</p>}</div>
        <div className={styles.MessagingConnectionResources__field}><Label htmlFor={languageId}>Idioma de la plantilla</Label><Input id={languageId} value={props.templateLanguage} disabled={props.busy} onChange={(event)=>props.onTemplateLanguageChange(event.target.value)} aria-invalid={Boolean(props.fieldErrors.templateLanguage)} aria-describedby={props.fieldErrors.templateLanguage?`${languageId}-error`:undefined} />{props.fieldErrors.templateLanguage&&<p id={`${languageId}-error`} className={styles.MessagingConnectionResources__error}>{props.fieldErrors.templateLanguage}</p>}</div>
        <p className={styles.MessagingConnectionResources__help}>WhatsApp requiere una plantilla de autenticación aprobada y su idioma exacto. Preparala en Zavu antes de guardar; TuTribu no conecta Meta ni crea plantillas.</p>
      </>}
      {props.message&&<p className={styles.MessagingConnectionResources__feedback} role={props.message.kind}>{props.message.text}</p>}
      <div className={styles.MessagingConnectionResources__consent}><Checkbox id={confirmationId} checked={props.confirmed} disabled={props.busy} onCheckedChange={(checked)=>props.onConfirmationChange(checked===true)} /><Label htmlFor={confirmationId}>Revisé el canal y sus recursos y quiero guardar esta configuración.</Label></div>
      <div className={styles.MessagingConnectionResources__actions}><Button className={styles.MessagingConnectionResources__action} type="button" variant="outline" disabled={props.busy} onClick={props.onReauthenticate}>Confirmar configuración con Google</Button><Button className={styles.MessagingConnectionResources__action} type="submit" disabled={props.busy||!props.canSave}>Guardar configuración del canal</Button></div>
    </form>
  </section>;
}
