const SIDEBAR_COOKIE_MAX_AGE_DAYS = 7;
const SIDEBAR_COOKIE_MAX_AGE_HOURS_PER_DAY = 24;
const SIDEBAR_COOKIE_MAX_AGE_MINUTES_PER_HOUR = 60;
const SIDEBAR_COOKIE_MAX_AGE_SECONDS_PER_MINUTE = 60;

export const SIDEBAR_COOKIE_NAME = "sidebar_state";
export const SIDEBAR_COOKIE_OPEN_VALUE = "true";
export const SIDEBAR_COOKIE_MAX_AGE =
  SIDEBAR_COOKIE_MAX_AGE_SECONDS_PER_MINUTE *
  SIDEBAR_COOKIE_MAX_AGE_MINUTES_PER_HOUR *
  SIDEBAR_COOKIE_MAX_AGE_HOURS_PER_DAY *
  SIDEBAR_COOKIE_MAX_AGE_DAYS;

