"use client";
/** Presents explicit CSV selection and own progress without transport or session access. @module allowlist-import-presenter */
import type { AllowlistImportDto } from "@/src/modules/academy-admissions/application/results/admission-management-result-schemas";
import { useId, useMemo, useState } from "react";
import { Button, Checkbox, Input, Label } from "beez-ui";
import { Link } from "@/components/navigation/link";
import { ALLOWLIST_IMPORT_FILE_ACCEPT, ALLOWLIST_IMPORT_VISIBLE_ROW_COUNT, ALLOWLIST_IMPORT_BROWSER_COPY } from "@/src/modules/academy-admissions/constants/allowlist-import-browser";
import { ALLOWLIST_IMPORT_REPORT_ERROR_LABEL, ALLOWLIST_IMPORT_REPORT_OUTCOME_LABEL } from "@/src/modules/academy-admissions/constants/allowlist-import";
import { ADMISSION_IMPORT_PUBLIC_STATE } from "@/src/modules/academy-admissions/constants/admission-management-contract";
import styles from "./styles.module.scss";
export type AllowlistImportProps = { ready: boolean; busy: boolean; privateVisible: boolean; initializationFailed: boolean; hasSavedImport: boolean; onRetryInitialization: () => void; fileName: string | null; contactType: "email" | "phone" | null; snapshot: AllowlistImportDto | null; selection: readonly number[]; confirmed: boolean; pending: boolean; canResume: boolean; conflict: boolean; policyConflict: boolean; unresolvedCount: number; canReconcile: boolean; reauthenticationRequired: boolean; recoveryHref: string | null; errorMessage: string | null; fieldError: string | null; statusMessage: string | null; onFile: (file: File) => void; onConfirmChange: (value: boolean) => void; onSelectRow: (row: number, selected: boolean) => void; onPreview: () => void; onConfirm: () => void; onReadOriginal: () => void; onReadCurrent: () => void; onReadPolicy: () => void; onReauthenticate: () => void; onTemplate: () => void; onReport: () => void; onReconcile: () => void };
/** @param props - Safe controlled view state and explicit callbacks. @returns Semantic paged rows and explicit impact confirmations without session, file reading or network access. */
export function AllowlistImport(props: AllowlistImportProps) {
  const fieldId = useId(), [offset, setOffset] = useState(0), rows = props.snapshot?.rows ?? [];
  const selected = useMemo(() => new Set(props.selection), [props.selection]), boundedOffset = Math.min(offset, Math.max(0, Math.ceil(rows.length / ALLOWLIST_IMPORT_VISIBLE_ROW_COUNT) - 1) * ALLOWLIST_IMPORT_VISIBLE_ROW_COUNT);
  const visibleRows = rows.slice(boundedOffset, boundedOffset + ALLOWLIST_IMPORT_VISIBLE_ROW_COUNT), disabled = !props.ready || props.busy, pendingBlocks = props.pending && !props.canResume;
  const terminal = props.snapshot?.state === ADMISSION_IMPORT_PUBLIC_STATE.completed || props.snapshot?.state === ADMISSION_IMPORT_PUBLIC_STATE.cancelled || props.snapshot?.state === ADMISSION_IMPORT_PUBLIC_STATE.expired;
  return <section className={styles.AllowlistImport} aria-label="Importación de habilitados" aria-busy={props.busy}>
    <p className={styles.AllowlistImport__help}>La vista previa no agrega entradas. La confirmación sólo incorpora filas válidas nuevas; no reemplaza toda la lista, reactiva entradas ni crea membresías.</p>
    {!props.privateVisible ? <p role="alert">{props.errorMessage ?? ALLOWLIST_IMPORT_BROWSER_COPY.account}</p> : <>
      {!props.ready && !props.initializationFailed && <p role="status">{ALLOWLIST_IMPORT_BROWSER_COPY.checking}</p>}
      {props.initializationFailed && <Button type="button" variant="outline" disabled={props.busy} onClick={props.onRetryInitialization}>Reintentar consulta inicial</Button>}
      {props.hasSavedImport && !props.snapshot && <Button type="button" variant="outline" disabled={disabled} onClick={props.onReadCurrent}>Consultar progreso actual</Button>}
      <section className={styles.AllowlistImport__section} aria-labelledby={`${fieldId}-file-title`}>
        <h2 id={`${fieldId}-file-title`}>1. Preparar el archivo</h2>
        <p className={styles.AllowlistImport__help}>CSV en UTF-8, separado por comas, con encabezados <code>identity,display_name</code>. Hasta 10.000 filas y 5 MiB. El nombre es opcional; para teléfonos usá el prefijo internacional completo.</p>
        {!props.contactType && <p role="status">{ALLOWLIST_IMPORT_BROWSER_COPY.noPolicy}</p>}
        <Button type="button" variant="outline" disabled={disabled} onClick={props.onTemplate}>Descargar plantilla</Button>
        <form className={styles.AllowlistImport__form} noValidate onSubmit={(event) => { event.preventDefault(); if (!disabled && !props.pending && props.confirmed && props.fileName && props.contactType && !props.policyConflict && !props.unresolvedCount) props.onPreview(); }}>
          <div className={styles.AllowlistImport__field}><Label htmlFor={`${fieldId}-file`}>Archivo CSV de habilitados</Label><Input id={`${fieldId}-file`} type="file" accept={ALLOWLIST_IMPORT_FILE_ACCEPT} disabled={disabled || props.pending || props.unresolvedCount > 0 || !props.contactType} aria-describedby={`${fieldId}-file-help`} aria-invalid={Boolean(props.fieldError)} onChange={(event) => { const file = event.target.files?.[0]; if (file) { setOffset(0); props.onFile(file); } event.target.value = ""; }} /><p id={`${fieldId}-file-help`} className={styles.AllowlistImport__help}>{props.fileName ? `Archivo conservado: ${props.fileName}` : "Elegí el archivo para revisar su formato antes de crear la vista previa."}</p></div>
          {!props.snapshot && <div className={styles.AllowlistImport__confirmation}><Checkbox id={`${fieldId}-preview-confirmed`} checked={props.confirmed} disabled={disabled || props.pending || !props.fileName || !props.contactType} onCheckedChange={(value) => props.onConfirmChange(value === true)} /><Label htmlFor={`${fieldId}-preview-confirmed`}>Confirmo guardar esta vista previa temporal</Label></div>}
          <div className={styles.AllowlistImport__actions}><Button type="submit" disabled={disabled || props.pending || !props.fileName || !props.contactType || !props.confirmed || Boolean(props.snapshot) || props.policyConflict || props.unresolvedCount > 0}>Crear vista previa</Button>{props.policyConflict && <Button type="button" variant="outline" disabled={disabled} onClick={props.onReadPolicy}>Consultar configuración actual</Button>}</div>
        </form>
      </section>
      {props.snapshot && <section className={styles.AllowlistImport__section} aria-labelledby={`${fieldId}-rows-title`}>
        <h2 id={`${fieldId}-rows-title`}>2. Revisar y elegir las filas</h2>
        <p className={styles.AllowlistImport__help}>Marcá cada fila válida que querés incorporar. No se seleccionan filas automáticamente. Los resultados ya confirmados se conservan y no se repiten.</p>
        <p className={styles.AllowlistImport__help}>Versión {props.snapshot.sourceVersion}. Reporte disponible hasta <time dateTime={props.snapshot.expiresAt}>{props.snapshot.expiresAt.replace("T", " ").replace("Z", " UTC")}</time>; después de ese plazo no puede consultarse. La eliminación automática de archivos sigue en desarrollo.</p>
        <dl className={styles.AllowlistImport__counts}><div><dt>Elegidas ahora</dt><dd>{props.selection.length}</dd></div><div><dt>Agregadas</dt><dd>{props.snapshot.counts.added}</dd></div><div><dt>Sin cambios</dt><dd>{props.snapshot.counts.unchanged}</dd></div><div><dt>Omitidas</dt><dd>{props.snapshot.counts.skipped}</dd></div><div><dt>Conflictos</dt><dd>{props.snapshot.counts.conflict}</dd></div></dl>
        <ul className={styles.AllowlistImport__rows}>{visibleRows.map((row) => <li className={styles.AllowlistImport__row} key={row.rowNumber}>
          <div className={styles.AllowlistImport__selection}><Checkbox id={`${fieldId}-row-${row.rowNumber}`} checked={selected.has(row.rowNumber)} disabled={disabled || pendingBlocks || terminal || row.errors.length > 0 || row.outcome !== undefined} onCheckedChange={(value) => props.onSelectRow(row.rowNumber, value === true)} /><Label htmlFor={`${fieldId}-row-${row.rowNumber}`}>Seleccionar fila {row.rowNumber}</Label></div>
          <div className={styles.AllowlistImport__identity}><strong>{row.identity || "Contacto vacío"}</strong>{row.displayName && <span>{row.displayName}</span>}<span className={styles.AllowlistImport__help}>{row.outcome ? ALLOWLIST_IMPORT_REPORT_OUTCOME_LABEL[row.outcome] : row.errors.length ? "Revisar datos" : "Válida pendiente"}{row.version !== undefined && ` · Versión de entrada ${row.version}`}</span>{row.errors.length > 0 && <span className={styles.AllowlistImport__error}>{row.errors.map((error) => ALLOWLIST_IMPORT_REPORT_ERROR_LABEL[error]).join(" · ")}</span>}</div>
        </li>)}</ul>
        {rows.length > ALLOWLIST_IMPORT_VISIBLE_ROW_COUNT && <nav className={styles.AllowlistImport__actions} aria-label="Páginas de filas importadas"><Button type="button" variant="outline" disabled={props.busy || boundedOffset === 0} onClick={() => setOffset(Math.max(0, boundedOffset - ALLOWLIST_IMPORT_VISIBLE_ROW_COUNT))}>Filas anteriores</Button><span>Filas {boundedOffset + 1}–{Math.min(boundedOffset + ALLOWLIST_IMPORT_VISIBLE_ROW_COUNT, rows.length)} de {rows.length}</span><Button type="button" variant="outline" disabled={props.busy || boundedOffset + ALLOWLIST_IMPORT_VISIBLE_ROW_COUNT >= rows.length} onClick={() => setOffset(boundedOffset + ALLOWLIST_IMPORT_VISIBLE_ROW_COUNT)}>Filas siguientes</Button></nav>}
        <form className={styles.AllowlistImport__form} noValidate onSubmit={(event) => { event.preventDefault(); if (!disabled && !pendingBlocks && !terminal && props.confirmed && props.selection.length && !props.conflict) props.onConfirm(); }}>
          <div className={styles.AllowlistImport__confirmation}><Checkbox id={`${fieldId}-rows-confirmed`} checked={props.confirmed} disabled={disabled || pendingBlocks || terminal || props.selection.length === 0 || props.conflict} onCheckedChange={(value) => props.onConfirmChange(value === true)} /><Label htmlFor={`${fieldId}-rows-confirmed`}>Confirmo incorporar sólo las filas elegidas</Label></div>
          <div className={styles.AllowlistImport__actions}><Button type="submit" disabled={disabled || pendingBlocks || terminal || !props.confirmed || props.selection.length === 0 || props.conflict}>{props.canResume ? "Retomar filas pendientes" : "Confirmar filas seleccionadas"}</Button><Button type="button" variant="outline" disabled={disabled} onClick={props.onReadCurrent}>Consultar progreso actual</Button><Button type="button" variant="outline" disabled={disabled} onClick={props.onReport}>Descargar reporte</Button></div>
        </form>
        <p className={styles.AllowlistImport__help}>El reporte neutraliza fórmulas y conserva HTML como texto. Es para lectura; no lo uses como archivo original para reimportar ni asumas que otra herramienta preserva su protección al guardarlo.</p>
      </section>}
      {props.fieldError && <p role="alert" className={styles.AllowlistImport__error}>{props.fieldError}</p>}
      {props.errorMessage && <p role="alert" className={styles.AllowlistImport__error}>{props.errorMessage}</p>}
      {props.statusMessage && <p role="status">{props.statusMessage}</p>}
      {(props.pending || props.unresolvedCount > 0) && <div className={styles.AllowlistImport__actions}><Button type="button" variant="outline" disabled={disabled} onClick={props.onReadOriginal}>Consultar operación original</Button>{props.unresolvedCount > 0 && <span className={styles.AllowlistImport__help}>Confirmaciones anteriores por conciliar: {props.unresolvedCount}</span>}{props.canReconcile && <Button type="button" variant="outline" disabled={disabled} onClick={props.onReconcile}>Conciliar resultados anteriores</Button>}</div>}
      {props.reauthenticationRequired && (props.recoveryHref ? <Link href={props.recoveryHref}>Continuar confirmación con Google</Link> : <Button type="button" variant="outline" disabled={disabled} onClick={props.onReauthenticate}>Confirmar identidad para importar</Button>)}
    </>}
  </section>;
}
