/** Composes real native credential/configuration/diagnostic preparation for activation and rotation scenarios. @module messaging-activation-fixture */
import {randomBytes,randomUUID} from "node:crypto";
import {sql} from "drizzle-orm";
import {expect} from "vitest";
import type {AcademyAdmissionTestDatabase} from "@/tests/support/academy-admission-database";
import {prepareMessagingConnectionCreation} from "@/tests/support/messaging-connection-fixture";
import {createAdmissionProviderTransport} from "@/tests/support/admission-provider-transport";
import {PostgresAuthenticatedAccountProvider} from "@/src/modules/auth/infrastructure/authenticated-account-provider";
import {PostgresMessagingConnectionActivation} from "@/src/modules/messaging/infrastructure/repositories/postgres-messaging-connection-activation";
import {readAdmissionEmailLifecycleDependency} from "@/src/modules/notifications/infrastructure/repositories/admission-email-lifecycle-reader";
import {PostgresMessagingSelectionDependencies} from "@/src/modules/academy-admissions/infrastructure/repositories/postgres-messaging-selection-dependencies";
import {ZavuCredentialInspectorFactory} from "@/src/modules/messaging/infrastructure/zavu/zavu-credential-inspector-factory";
import {ZavuMessageDeliverySender} from "@/src/modules/messaging/infrastructure/zavu/zavu-message-delivery-sender";
import {ScopedConnectionDiagnosticDispatcher} from "@/src/modules/messaging/infrastructure/composition/connection-diagnostic-dispatcher";
import {buildMessagingModule,buildMessagingWorkModule} from "@/src/modules/messaging/setup";
import {VERIFICATION_MESSAGE_COPY} from "@/src/modules/messaging/constants/zavu-delivery";
import type {RequestDatabase} from "@/src/modules/shared/infrastructure/database/server-database-client";

/** @param database - Owned branch. @param existing - Optional current native owner/tribe for a separate replacement candidate. @param diagnosticRecipient - Optional distinct synthetic destination, preserving the specified account/contact/tribe/purpose challenge namespace. @returns Real configuration/validation/diagnostic evidence and the exact activation context without external network. */
export async function prepareMessagingConnectionActivation(database:AcademyAdmissionTestDatabase,existing?:Awaited<ReturnType<typeof prepareMessagingConnectionCreation>>,diagnosticRecipient?:string){
  let fixture=existing??await prepareMessagingConnectionCreation(database);const credential=randomUUID(),senderId=randomUUID();
  if(!existing)for(const migration of["20261005092500_guard_messaging_attempts.sql","20261005100000_guard_messaging_secret_retirement.sql","20261006120000_index_messaging_contact_windows.sql","20261006140000_claim_messaging_deliveries_fairly.sql","20261006160000_purge_verification_delivery_material.sql","20261006230000_bind_credential_validation_usage.sql","20261007050000_claim_scoped_diagnostic_delivery.sql","20261008161500_create_admission_email_settings.sql"])await database.applyMigration(migration);
  if(existing){const context=await refreshMessagingActivationRecency(database,fixture,"save_messaging_credentials",fixture.context.tribeId);fixture={...fixture,context:{...fixture.context,authenticatedAt:context.authenticatedAt,validUntil:context.validUntil}};}
  const created=await fixture.repository.create(fixture.context,{operationId:randomUUID(),confirmed:true,providerId:"zavu",name:"Activación real",apiKey:credential});if(created.state!=="completed")throw new Error("Expected protected candidate");
  await database.withContext(fixture.fixture.own,async(transaction)=>{
    const now=new Date((await transaction.execute<{now:string}>(sql`select clock_timestamp() as now`)).rows[0].now),validUntil=new Date(now.getTime()+540_000);
    if(!existing)await transaction.execute(sql`insert into public.messaging_usage_policies(tribe_id) values (${fixture.context.tribeId})`);
    for(const operation of["configure_messaging_connection","validate_messaging_connection","diagnose_messaging_connection","verify_messaging_diagnostic","activate_messaging_connection"]){const intentId=randomUUID();await transaction.execute(sql`insert into public.global_reauthentication_intents(id,user_id,original_session_id,account_id,provider_subject,tribe_id,operation,resource_id,return_path,nonce_hash,state,created_at,expires_at,consumed_at) values (${intentId},${fixture.context.actorUserId},${fixture.context.sessionId},${fixture.context.accountId},${fixture.context.subject},${fixture.context.tribeId},${operation},${created.result.id},'/synthetic-activation',${randomBytes(32)},'consumed',${now},${validUntil},${now})`);await transaction.execute(sql`insert into public.recent_authentication_evidence(intent_id,user_id,account_id,provider_subject,session_id,tribe_id,operation,resource_id,authenticated_at,verified_at,valid_until) values (${intentId},${fixture.context.actorUserId},${fixture.context.accountId},${fixture.context.subject},${fixture.context.sessionId},${fixture.context.tribeId},${operation},${created.result.id},${now},${now},${validUntil})`);}
  });
  let code="",transactions=0;
  const execute=async<Result>(_context:{actorUserId:string},run:(database:RequestDatabase)=>Promise<Result>)=>{transactions+=1;try{return await database.withContext(fixture.fixture.own,run);}finally{transactions-=1;}};
  const accounts=new PostgresAuthenticatedAccountProvider(async()=>({userId:fixture.context.actorUserId,sessionId:fixture.context.sessionId}),(_identity,run)=>execute(fixture.context,run));
  const request=buildMessagingModule({accounts,clock:()=>new Date(),execute:(_account,run)=>execute(fixture.context,run)}).createRequestModule({selection:"management",readSecurityConfig:async()=>fixture.fixture.config});
  const transport=createAdmissionProviderTransport([{origin:"https://api.zavu.dev",pathname:`/v1/senders/${senderId}`,method:"GET",respond:()=>Response.json({id:senderId,name:"Remitente",channels:["email"]})},{origin:"https://api.zavu.dev",pathname:"/v1/me",method:"GET",respond:()=>Response.json({isTestMode:false,apiKey:{id:randomUUID()},project:{id:randomUUID()},team:{id:randomUUID()}})},{origin:"https://api.zavu.dev",pathname:"/v1/messages",method:"POST",respond:async(incoming)=>{expect(transactions).toBe(0);const body=await incoming.json() as{text:string};code=body.text.slice(VERIFICATION_MESSAGE_COPY.prefix.length,-VERIFICATION_MESSAGE_COPY.suffix.length);return Response.json({message:{id:randomUUID(),direction:"outbound",channel:"email",status:"sent"}});}}]);
  const inspectors=new ZavuCredentialInspectorFactory(transport.fetch),base={tribeId:fixture.context.tribeId,connectionId:created.result.id,requestId:randomUUID()};
  expect(await request.createConnectionConfiguration(inspectors).execute({...base,operationId:randomUUID(),confirmed:true,expectedVersion:1,channel:"email",senderId},new AbortController().signal)).toMatchObject({ok:true,value:{state:"completed",result:{version:2,configurationVersion:2}}});
  expect(await request.createCredentialValidation(inspectors).execute({...base,operationId:randomUUID(),confirmed:true,expectedVersion:2},new AbortController().signal)).toMatchObject({ok:true,value:{state:"completed",result:{version:3,credentialMode:"production"}}});
  const deferred:Promise<void>[]=[],dispatcher=new ScopedConnectionDiagnosticDispatcher({readSecurityFacts:async()=>({environment:fixture.fixture.config.environment,securityEpoch:fixture.fixture.config.securityEpoch,recoveryLocked:false}),createDispatcher:(diagnosticScope,authorize)=>buildMessagingWorkModule({diagnosticScope,authorize,execute:(_actor,run)=>execute(fixture.context,run),readSecurityConfig:async()=>fixture.fixture.config,createSender:(preparation)=>new ZavuMessageDeliverySender(preparation,transport.fetch),runtime:{now:Date.now,createId:randomUUID,defer:(work)=>{deferred.push(work);},report:()=>{throw new Error("Unexpected diagnostic failure");}}}).useCases.dispatch});
  const issued=await request.createDiagnosticIssuance(dispatcher).execute({...base,operationId:randomUUID(),confirmed:true,expectedVersion:3,channel:"email",recipient:diagnosticRecipient??fixture.fixture.own.email});if(!issued.ok||issued.value.state!=="completed"||issued.value.result.outcome!=="issued")throw new Error(`Expected real diagnostic issuance: ${!issued.ok?issued.failure.code:issued.value.state!=="completed"?issued.value.state:issued.value.result.outcome==="denied"?issued.value.result.code:issued.value.result.outcome}`);await Promise.all(deferred);
  const verificationInput={...base,diagnosticId:issued.value.result.diagnosticId,operationId:randomUUID(),code};
  expect(await request.useCases.verifyDiagnostic.execute(verificationInput)).toMatchObject({ok:true,value:{state:"completed",result:{outcome:"verified"}}});
  const resolved=await request.useCases.resolveContext.execute({...base,operation:"activate_messaging_connection"});if(!resolved.allowed)throw new Error("Expected current activation authority");
  const owner=new PostgresMessagingConnectionActivation(execute,async()=>fixture.fixture.config,(transaction)=>new PostgresMessagingSelectionDependencies(transaction,readAdmissionEmailLifecycleDependency));
  const lifecycleVersion=await database.withContext(fixture.fixture.own,async(transaction)=>(await transaction.execute<{version:number}>(sql`select version from public.tenant_messaging_connections where id=${created.result.id}`)).rows[0].version);
  return{fixture,transport,owner,request,inspectors,execute,verificationInput,credential,senderId,context:resolved.context,input:{operationId:randomUUID(),expectedVersion:lifecycleVersion,confirmed:true as const},get transactions(){return transactions;}};
}

/** @param database - Exact owned branch. @param fixture - Native account/session and tribe from the existing owner. @param operation - Actual sensitive action. @param resourceId - Exact action resource. @returns Current SQL authentication bounds after persisting fresh native evidence. */
export async function refreshMessagingActivationRecency(database:AcademyAdmissionTestDatabase,fixture:Awaited<ReturnType<typeof prepareMessagingConnectionCreation>>,operation:string,resourceId:string){
  return database.withContext(fixture.fixture.own,async(transaction)=>{
    const now=new Date((await transaction.execute<{now:Date|string}>(sql`select clock_timestamp() as now`)).rows[0].now),validUntil=new Date(now.getTime()+540_000),intentId=randomUUID();
    await transaction.execute(sql`insert into public.global_reauthentication_intents(id,user_id,original_session_id,account_id,provider_subject,tribe_id,operation,resource_id,return_path,nonce_hash,state,created_at,expires_at,consumed_at) values (${intentId},${fixture.context.actorUserId},${fixture.context.sessionId},${fixture.context.accountId},${fixture.context.subject},${fixture.context.tribeId},${operation},${resourceId},'/synthetic-rotation',${randomBytes(32)},'consumed',${now},${validUntil},${now})`);
    await transaction.execute(sql`insert into public.recent_authentication_evidence(intent_id,user_id,account_id,provider_subject,session_id,tribe_id,operation,resource_id,authenticated_at,verified_at,valid_until) values (${intentId},${fixture.context.actorUserId},${fixture.context.accountId},${fixture.context.subject},${fixture.context.sessionId},${fixture.context.tribeId},${operation},${resourceId},${now},${now},${validUntil})`);
    return{authenticatedAt:now,validUntil};
  });
}
