/** Verifies candidate preparation independently of explicit selection and credential production mode. @module messaging-candidate-preparation-tests */
import {describe,expect,it} from "vitest";
import {assessMessagingCandidatePreparation} from "@/src/modules/messaging/domain/policies/messaging-candidate-preparation";

/** @returns An exact immutable configuration with independently confirmed channel capability facts. */
function preparationFixture(){return{configuration:{emailSenderId:"mail-sender",smsSenderId:null,whatsappSenderId:null,whatsappTemplateId:null,whatsappTemplateLanguage:null},credentialValidated:true,capabilities:[{channel:"email" as const,senderId:"mail-sender",templateId:null,templateLanguage:null,state:"prepared" as const,testedAt:new Date("2026-10-08T12:00:00Z")} ]};}

describe("candidate preparation",()=>{
  it("should propose ready only after all configured channels are locally confirmed without selecting the connection",()=>{expect(assessMessagingCandidatePreparation(preparationFixture())).toEqual({prepared:true});});
  it("should remain draft for an unchecked credential, no configured channel, missing test or unavailable capability",()=>{const fixture=preparationFixture();expect(assessMessagingCandidatePreparation({...fixture,credentialValidated:false})).toEqual({prepared:false});expect(assessMessagingCandidatePreparation({...fixture,configuration:{...fixture.configuration,emailSenderId:null}})).toEqual({prepared:false});expect(assessMessagingCandidatePreparation({...fixture,capabilities:[{...fixture.capabilities[0],testedAt:null}]})).toEqual({prepared:false});expect(assessMessagingCandidatePreparation({...fixture,capabilities:[{...fixture.capabilities[0],state:"unavailable"}]})).toEqual({prepared:false});});
  it("should reject an unusable local test timestamp without fabricating prepared state",()=>{const fixture=preparationFixture();expect(assessMessagingCandidatePreparation({...fixture,capabilities:[{...fixture.capabilities[0],testedAt:new Date(Number.NaN)}]})).toEqual({prepared:false});});
  it("should require every configured channel and exact sender/template/language rather than one successful channel",()=>{const fixture=preparationFixture(),configuration={...fixture.configuration,smsSenderId:"sms-sender",whatsappSenderId:"wa-sender",whatsappTemplateId:"auth-template",whatsappTemplateLanguage:"es"},capabilities=[...fixture.capabilities,{channel:"sms" as const,senderId:"sms-sender",templateId:null,templateLanguage:null,state:"prepared" as const,testedAt:fixture.capabilities[0].testedAt},{channel:"whatsapp" as const,senderId:"wa-sender",templateId:"auth-template",templateLanguage:"es",state:"prepared" as const,testedAt:fixture.capabilities[0].testedAt}];expect(assessMessagingCandidatePreparation({...fixture,configuration})).toEqual({prepared:false});expect(assessMessagingCandidatePreparation({...fixture,configuration,capabilities})).toEqual({prepared:true});expect(assessMessagingCandidatePreparation({...fixture,configuration,capabilities:capabilities.map((capability)=>capability.channel==="whatsapp"?{...capability,templateLanguage:"en"}:capability)})).toEqual({prepared:false});});
});
