/** @vitest-environment node */
/** Exercises the full native HTTP create/configure/validate/issue/read/verify flow with real libraries and a closed synthetic provider. @module connection-diagnostic-http-tests */
import {randomBytes,randomUUID} from "node:crypto";
import {join} from "node:path";
import {sql} from "drizzle-orm";
import {describe,expect,it} from "vitest";
import {makeSignature} from "better-auth/crypto";
import {withAcademyAdmissionDatabase} from "@/tests/support/academy-admission-database";
import {prepareMessagingConnectionCreation} from "@/tests/support/messaging-connection-fixture";
import {withAdmissionNextServer} from "@/tests/support/admission-next-server";

describe.skipIf(process.env.RUN_ADMISSION_BROWSER_TESTS!=="1")("native diagnostic HTTP",()=>{
  it("should configure, validate, issue once and verify only the received diagnostic while preserving independent transport",async()=>{
    await withAcademyAdmissionDatabase(async(database)=>{
      const fixture=await prepareMessagingConnectionCreation(database),tribeId=fixture.context.tribeId,slug=`connection-${tribeId}`,credential=randomUUID(),senderId=randomUUID();
      for(const migration of["20261005092500_guard_messaging_attempts.sql","20261005093000_guard_academy_membership_sources.sql","20261007001000_read_public_admission_overview.sql","20261005100000_guard_messaging_secret_retirement.sql","20261006120000_index_messaging_contact_windows.sql","20261006140000_claim_messaging_deliveries_fairly.sql","20261006160000_purge_verification_delivery_material.sql","20261006230000_bind_credential_validation_usage.sql","20261007050000_claim_scoped_diagnostic_delivery.sql"])await database.applyMigration(migration);
      await database.withContext(fixture.fixture.own,(transaction)=>transaction.execute(sql`insert into public.tribe_academy_settings(tribe_id,access_model,admission_enabled) values (${tribeId},'academy',true)`));
      let providerRequests=0,receivedCode="";
      await database.withServerEnvironment((environment)=>withAdmissionNextServer(environment,slug,async(origin,secret)=>{
        const cookie=`better-auth.session_token=${encodeURIComponent(`${fixture.sessionToken}.${await makeSignature(fixture.sessionToken,secret)}`)}`,headers={cookie,origin,"content-type":"application/json"},base=`${origin}/api/tribes/${slug}/messaging`;
        const createdResponse=await fetch(`${base}/connections`,{method:"POST",headers,body:JSON.stringify({operationId:randomUUID(),confirmed:true,providerId:"zavu",name:"Diagnóstico nativo",apiKey:credential})});expect(createdResponse.status).toBe(201);const created=await createdResponse.json(),connectionId=created.result.id,path=`${base}/connections/${connectionId}`;
        /** @param operation - Exact sensitive action being exercised next. @returns Current own SQL recency evidence, not a real Google callback or provider setup. */
        const refreshRecency=async(operation:string)=>database.withContext(fixture.fixture.own,async(transaction)=>{const now=new Date((await transaction.execute<{now:string}>(sql`select clock_timestamp() as now`)).rows[0].now),validUntil=new Date(now.getTime()+540_000),intentId=randomUUID();await transaction.execute(sql`insert into public.global_reauthentication_intents(id,user_id,original_session_id,account_id,provider_subject,tribe_id,operation,resource_id,return_path,nonce_hash,state,created_at,expires_at,consumed_at) values (${intentId},${fixture.context.actorUserId},${fixture.context.sessionId},${fixture.context.accountId},${fixture.context.subject},${tribeId},${operation},${connectionId},'/synthetic-native-diagnostic',${randomBytes(32)},'consumed',${now},${validUntil},${now})`);await transaction.execute(sql`insert into public.recent_authentication_evidence(intent_id,user_id,account_id,provider_subject,session_id,tribe_id,operation,resource_id,authenticated_at,verified_at,valid_until) values (${intentId},${fixture.context.actorUserId},${fixture.context.accountId},${fixture.context.subject},${fixture.context.sessionId},${tribeId},${operation},${connectionId},${now},${now},${validUntil})`);});
        await refreshRecency("configure_messaging_connection");const configured=await fetch(`${path}/configuration`,{method:"PUT",headers,body:JSON.stringify({operationId:randomUUID(),confirmed:true,expectedVersion:1,channel:"email",senderId})});expect(configured.status).toBe(200);expect(await configured.json()).toMatchObject({result:{version:2,configurationVersion:2}});
        await refreshRecency("validate_messaging_connection");const validated=await fetch(`${path}/validate`,{method:"POST",headers,body:JSON.stringify({operationId:randomUUID(),confirmed:true,expectedVersion:2})});expect(validated.status).toBe(200);expect(await validated.json()).toMatchObject({result:{version:3,configurationVersion:2,credentialMode:"production"}});expect(providerRequests).toBe(2);
        await database.withContext(fixture.fixture.own,(transaction)=>transaction.execute(sql`insert into public.messaging_usage_policies(tribe_id,allowed_countries) values (${tribeId},ARRAY[]::text[])`));
        await refreshRecency("diagnose_messaging_connection");const body={operationId:randomUUID(),confirmed:true,expectedVersion:3,channel:"email",recipient:fixture.fixture.own.email};
        const issuedResponse=await fetch(`${path}/diagnostics`,{method:"POST",headers,body:JSON.stringify(body)});expect(issuedResponse.status).toBe(200);const issued=await issuedResponse.json();expect(issued).toMatchObject({state:"completed",result:{outcome:"issued",connectionId,connectionVersion:2,channel:"email"}});expect(providerRequests).toBe(3);if(!receivedCode)throw new Error("Expected private synthetic diagnostic receipt");expect(JSON.stringify(issued)).not.toContain(receivedCode);expect(JSON.stringify(issued)).not.toContain(credential);expect(JSON.stringify(issued)).not.toContain(fixture.fixture.own.email);
        const replay=await fetch(`${path}/diagnostics`,{method:"POST",headers,body:JSON.stringify(body)});expect(replay.status).toBe(200);expect(await replay.json()).toMatchObject({replayed:true,result:issued.result});expect(providerRequests).toBe(3);
        const delivery=await fetch(`${base}/deliveries/${issued.result.deliveryId}`,{headers:{cookie}});expect(delivery.status).toBe(200);const transport=await delivery.json();expect(transport).toMatchObject({id:issued.result.deliveryId,state:"accepted",purpose:"connection_diagnostic",channel:"email"});expect(transport).not.toHaveProperty("providerMessageId");expect(providerRequests).toBe(3);
        await refreshRecency("verify_messaging_diagnostic");const verified=await fetch(`${path}/diagnostics/${issued.result.diagnosticId}/verify`,{method:"POST",headers,body:JSON.stringify({operationId:randomUUID(),confirmed:true,verificationCode:receivedCode})});expect(verified.status).toBe(200);const proof=await verified.json();expect(proof).toMatchObject({state:"completed",result:{outcome:"verified",connectionVersion:2,channel:"email",capabilityState:"prepared"}});expect(proof.result).not.toHaveProperty("proofId");expect(providerRequests).toBe(3);
        await database.withContext(fixture.fixture.own,(transaction)=>transaction.execute(sql`update public.recent_authentication_evidence set invalidated_at=clock_timestamp() where tribe_id=${tribeId} and invalidated_at is null`));
        expect((await fetch(`${base}/deliveries/${issued.result.deliveryId}`,{headers:{cookie}})).status).toBe(200);expect((await fetch(`${path}/diagnostics`,{method:"POST",headers,body:JSON.stringify({...body,operationId:randomUUID()})})).status).toBe(401);expect(providerRequests).toBe(3);
        const counts=await database.withContext(fixture.fixture.own,async(transaction)=>(await transaction.execute(sql`select (select count(*)::int from public.message_deliveries where tribe_id=${tribeId}) as deliveries,(select count(*)::int from public.message_delivery_attempts where tribe_id=${tribeId}) as attempts,(select count(*)::int from public.messaging_usage_reservations where tribe_id=${tribeId}) as reservations,(select count(*)::int from public.academy_admission_verification_proofs where tribe_id=${tribeId}) as admission_proofs,(select count(*)::int from public.global_identity_evidence where user_id=${fixture.context.actorUserId}) as global_evidence`)).rows[0]);expect(counts).toEqual({deliveries:1,attempts:1,reservations:1,admission_proofs:0,global_evidence:0});
      },{preloadModules:[join(process.cwd(),"tests/support/native-zavu-provider-transport.mjs")],environment:{ADMISSION_TEST_ZAVU_CREDENTIAL:credential,ADMISSION_TEST_ZAVU_SENDER_ID:senderId,ADMISSION_TEST_ZAVU_RECIPIENT:fixture.fixture.own.email,ADMISSION_TEST_ZAVU_TEST_MODE:"false"},onProviderRequest:()=>{providerRequests+=1;},onDiagnosticCode:(code)=>{receivedCode=code;}}));
    });
  },1_200_000);
});
