/** @vitest-environment node */
/** Exercises explicit UI selection after actual diagnostic proof, preserving original activation recovery with real Next/auth/SQL/SDK and a closed synthetic provider. @module messaging-phone-setup-browser-ui-tests */
import {randomBytes,randomUUID} from "node:crypto";
import {join} from "node:path";
import {chromium,webkit} from "@playwright/test";
import {sql} from "drizzle-orm";
import {describe,expect,it} from "vitest";
import {makeSignature} from "better-auth/crypto";
import {withAcademyAdmissionDatabase} from "@/tests/support/academy-admission-database";
import {prepareMessagingConnectionCreation} from "@/tests/support/messaging-connection-fixture";
import {withAdmissionNextServer} from "@/tests/support/admission-next-server";
import {captureAdmissionReview} from "@/tests/support/admission-review-capture";

describe.skipIf(process.env.RUN_ADMISSION_BROWSER_TESTS!=="1")("native phone setup UI",()=>{
  it.each([{name:"chromium",engine:chromium,width:1280},{name:"chromium",engine:chromium,width:390},{name:"webkit",engine:webkit,width:1280},{name:"webkit",engine:webkit,width:390}])("should save countries through the UI before its first SMS diagnostic and activate only after receiving its code on $name at $width",async({name,engine,width})=>{
    await withAcademyAdmissionDatabase(async(database)=>{
      const fixture=await prepareMessagingConnectionCreation(database),tribeId=fixture.context.tribeId,slug=`connection-${tribeId}`,credential=randomUUID(),senderId=randomUUID(),recipient="+5491155501234";
      for(const migration of["20261005092500_guard_messaging_attempts.sql","20261005093000_guard_academy_membership_sources.sql","20261007001000_read_public_admission_overview.sql","20261005100000_guard_messaging_secret_retirement.sql","20261006120000_index_messaging_contact_windows.sql","20261006140000_claim_messaging_deliveries_fairly.sql","20261006160000_purge_verification_delivery_material.sql","20261006230000_bind_credential_validation_usage.sql","20261007050000_claim_scoped_diagnostic_delivery.sql","20261008161500_create_admission_email_settings.sql"])await database.applyMigration(migration);
      await database.withContext(fixture.fixture.own,(transaction)=>transaction.execute(sql`insert into public.tribe_academy_settings(tribe_id,access_model,admission_enabled) values (${tribeId},'academy',true)`));let providerRequests=0,receivedCode="";const dispatchObservations:{stage:string;code:string}[]=[];
      await database.withServerEnvironment((environment)=>withAdmissionNextServer(environment,slug,async(origin,secret)=>{
        const cookieValue=encodeURIComponent(`${fixture.sessionToken}.${await makeSignature(fixture.sessionToken,secret)}`),headers={cookie:`better-auth.session_token=${cookieValue}`,origin,"content-type":"application/json"},base=`${origin}/api/tribes/${slug}/messaging`;
        const created=await fetch(`${base}/connections`,{method:"POST",headers,body:JSON.stringify({operationId:randomUUID(),confirmed:true,providerId:"zavu",name:"Prueba de canal",apiKey:credential})});expect(created.status).toBe(201);const connectionId=(await created.json()).result.id;
        const refreshRecency=async(operation:string)=>database.withContext(fixture.fixture.own,async(transaction)=>{const now=new Date((await transaction.execute<{now:string}>(sql`select clock_timestamp() as now`)).rows[0].now),validUntil=new Date(now.getTime()+540_000),intentId=randomUUID(),resourceId=operation==="initialize_messaging_usage"||operation==="update_messaging_usage"?tribeId:connectionId;await transaction.execute(sql`insert into public.global_reauthentication_intents(id,user_id,original_session_id,account_id,provider_subject,tribe_id,operation,resource_id,return_path,nonce_hash,state,created_at,expires_at,consumed_at) values (${intentId},${fixture.context.actorUserId},${fixture.context.sessionId},${fixture.context.accountId},${fixture.context.subject},${tribeId},${operation},${resourceId},'/synthetic-ui-diagnostic',${randomBytes(32)},'consumed',${now},${validUntil},${now})`);await transaction.execute(sql`insert into public.recent_authentication_evidence(intent_id,user_id,account_id,provider_subject,session_id,tribe_id,operation,resource_id,authenticated_at,verified_at,valid_until) values (${intentId},${fixture.context.actorUserId},${fixture.context.accountId},${fixture.context.subject},${fixture.context.sessionId},${tribeId},${operation},${resourceId},${now},${now},${validUntil})`);});
        await refreshRecency("configure_messaging_connection");const configured=await fetch(`${base}/connections/${connectionId}/configuration`,{method:"PUT",headers,body:JSON.stringify({operationId:randomUUID(),confirmed:true,expectedVersion:1,channel:"sms",senderId})});expect(configured.status).toBe(200);
        await refreshRecency("validate_messaging_connection");const validated=await fetch(`${base}/connections/${connectionId}/validate`,{method:"POST",headers,body:JSON.stringify({operationId:randomUUID(),confirmed:true,expectedVersion:2})});expect(validated.status).toBe(200);expect(providerRequests).toBe(2);
        await refreshRecency("initialize_messaging_usage");await refreshRecency("update_messaging_usage");await refreshRecency("diagnose_messaging_connection");await refreshRecency("verify_messaging_diagnostic");
        const browser=await engine.launch({headless:true}),context=await browser.newContext({viewport:{width,height:900},reducedMotion:"reduce"}),page=await context.newPage(),errors:string[]=[];page.on("pageerror",(error)=>errors.push(error.message));
        try{
          await context.addCookies([{name:"better-auth.session_token",value:cookieValue,url:origin,httpOnly:true,sameSite:"Lax"}]);await page.goto(`${origin}/${slug}/academia/admissions/messaging/connections`,{waitUntil:"networkidle",timeout:120_000});await page.getByLabel("Destino de la prueba",{exact:true}).waitFor();await page.waitForFunction(()=>!(document.querySelector('input[id$="-recipient"]') as HTMLInputElement|null)?.disabled);expect(providerRequests).toBe(2);
          await page.getByRole("combobox",{name:"Canal de la prueba",exact:true}).click();await page.getByRole("option",{name:"SMS",exact:true}).click();await page.getByText(/Guardá los países de mensajería/).waitFor();expect(await page.getByRole("button",{name:"Enviar código de prueba",exact:true}).isDisabled()).toBe(true);expect(providerRequests).toBe(2);
          await page.getByRole("link",{name:"Volver a países y cupos",exact:true}).click();await page.getByRole("button",{name:"Iniciar configuración de uso",exact:true}).waitFor({timeout:120_000});await page.waitForFunction(()=>{const checkbox=document.querySelector('button[role="checkbox"]') as HTMLButtonElement|null;return Boolean(checkbox&&!checkbox.disabled);},{},{timeout:120_000});await refreshRecency("initialize_messaging_usage");await page.getByRole("checkbox",{name:/Revisé los países y cupos/}).check();await page.getByRole("button",{name:"Iniciar configuración de uso",exact:true}).click();await page.getByRole("button",{name:"Guardar países y cupos",exact:true}).waitFor({timeout:120_000});await page.waitForFunction(()=>{const selector=Array.from(document.querySelectorAll('button[role="combobox"]')).find((element)=>element.getAttribute("id")?.endsWith("-country")) as HTMLButtonElement|undefined;return Boolean(selector&&!selector.disabled);},{},{timeout:120_000});await page.getByRole("combobox",{name:"Agregar país al borrador",exact:true}).click();await page.getByRole("option",{name:"Argentina",exact:true}).click();await refreshRecency("update_messaging_usage");await page.getByRole("checkbox",{name:/Revisé los países y cupos/}).check();await page.getByRole("button",{name:"Guardar países y cupos",exact:true}).click();await page.getByText("Países guardados: Argentina.",{exact:true}).waitFor({timeout:120_000});expect(providerRequests).toBe(2);
          const savedUsage=await fetch(`${base}/usage-policy`,{headers});expect(savedUsage.status).toBe(200);expect(await savedUsage.json()).toMatchObject({state:"configured",policy:{version:2,allowedCountries:["AR"]}});
          await page.goto(`${origin}/${slug}/academia/admissions/messaging/connections`,{waitUntil:"networkidle",timeout:120_000});await page.getByRole("combobox",{name:"Canal de la prueba",exact:true}).waitFor();await page.waitForFunction(()=>!(document.querySelector('input[id$="-recipient"]') as HTMLInputElement|null)?.disabled);await page.getByRole("combobox",{name:"Canal de la prueba",exact:true}).click();await page.getByRole("option",{name:"SMS",exact:true}).click();await page.getByRole("combobox",{name:"País guardado del teléfono",exact:true}).click();await page.getByRole("option",{name:"AR",exact:true}).click();expect(providerRequests).toBe(2);
          if(name==="chromium"&&width===1280)await captureAdmissionReview(page,"phone-countries-saved",[recipient,credential,fixture.sessionToken,secret,fixture.fixture.own.email,fixture.context.actorUserId],"connection-phone-setup-captures.json");
          let issuedDeliveryId="",issueElapsedMs=0;
          const issuePath=`**/api/tribes/${slug}/messaging/connections/${connectionId}/diagnostics`;await page.route(issuePath,async(route)=>{let response;try{const startedAt=Date.now();response=await route.fetch({timeout:240_000});issueElapsedMs=Date.now()-startedAt;}catch{throw new Error("Diagnostic issue test transport failed before controlled response loss");}const result=await response.json();expect({status:response.status(),outcome:result.result?.outcome,code:result.code}).toMatchObject({status:200,outcome:"issued"});issuedDeliveryId=result.result.deliveryId;await route.abort("failed");});
          await refreshRecency("diagnose_messaging_connection");
          await page.getByLabel("Destino de la prueba",{exact:true}).fill(recipient);await page.getByRole("checkbox",{name:/Confirmo el destino y el consumo/}).check();await page.getByRole("button",{name:"Enviar código de prueba",exact:true}).click();await page.getByRole("button",{name:"Consultar guardado",exact:true}).waitFor({timeout:240_000});await page.waitForFunction(()=>{const button=Array.from(document.querySelectorAll("button")).find((element)=>element.textContent?.trim()==="Consultar guardado");return Boolean(button&&!button.disabled);},{},{timeout:240_000});if(providerRequests!==3){const metadata=await database.withContext(fixture.fixture.own,async(transaction)=>({delivery:(await transaction.execute(sql`select state,last_outcome from public.message_deliveries where id=${issuedDeliveryId} and tribe_id=${tribeId}`)).rows[0],attempts:(await transaction.execute(sql`select state,safe_reason from public.message_delivery_attempts where delivery_id=${issuedDeliveryId} order by sequence`)).rows,reservations:(await transaction.execute<{count:number}>(sql`select count(*)::int as count from public.messaging_usage_reservations where delivery_id=${issuedDeliveryId}`)).rows[0].count}));console.log(JSON.stringify({phase:"diagnostic_dispatch_observation",providerRequests,issueElapsedMs,dispatchObservations,...metadata}));}expect(providerRequests).toBe(3);expect((await page.getByLabel("Destino de la prueba",{exact:true}).inputValue())==="").toBe(true);
          await page.unroute(issuePath);await page.getByRole("button",{name:"Consultar guardado",exact:true}).click();await page.getByLabel("Código recibido",{exact:true}).waitFor({timeout:120_000});expect(providerRequests).toBe(3);await page.getByRole("button",{name:"Consultar entrega de la prueba",exact:true}).click();await page.getByText("Aceptada por el proveedor",{exact:true}).waitFor({timeout:120_000});expect(providerRequests).toBe(3);
          if(!receivedCode)throw new Error("Expected private synthetic code receipt");if(name==="chromium"&&width===1280)await captureAdmissionReview(page,"phone-issued",[recipient,credential,receivedCode,fixture.sessionToken,secret,fixture.fixture.own.email,fixture.context.actorUserId],"connection-phone-setup-captures.json");
          await page.reload({waitUntil:"networkidle",timeout:120_000});await page.getByLabel("Código recibido",{exact:true}).waitFor({timeout:120_000});expect(providerRequests).toBe(3);expect((await page.getByLabel("Código recibido",{exact:true}).inputValue())==="").toBe(true);await page.getByRole("button",{name:"Consultar prueba 1: SMS",exact:true}).click();await page.waitForFunction(()=>{const field=document.querySelector('input[id$="-code"]') as HTMLInputElement|null;return Boolean(field&&!field.disabled);},{},{timeout:120_000});expect(providerRequests).toBe(3);await refreshRecency("verify_messaging_diagnostic");
          const verifyPath=`**/api/tribes/${slug}/messaging/connections/${connectionId}/diagnostics/*/verify`;await page.route(verifyPath,async(route)=>{try{await route.fetch({timeout:240_000});await route.abort("failed");}catch{throw new Error("Diagnostic verify test transport failed before controlled response loss");}});await page.getByLabel("Código recibido",{exact:true}).fill(receivedCode);await page.getByRole("button",{name:"Confirmar código recibido",exact:true}).click();await page.getByRole("button",{name:"Consultar guardado",exact:true}).waitFor({timeout:240_000});await page.waitForFunction(()=>{const button=Array.from(document.querySelectorAll("button")).find((element)=>element.textContent?.trim()==="Consultar guardado");return Boolean(button&&!button.disabled);},{},{timeout:240_000});expect((await page.getByLabel("Código recibido",{exact:true}).inputValue())==="").toBe(true);await page.unroute(verifyPath);await page.getByRole("button",{name:"Consultar guardado",exact:true}).click();await page.getByText("SMS: Canal comprobado",{exact:true}).waitFor({timeout:120_000});expect(providerRequests).toBe(3);expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)).toBe(false);
          const stored=await page.evaluate(()=>Object.values(sessionStorage).join("\n"));expect(stored).not.toContain(credential);expect(stored).not.toContain(receivedCode);expect(stored).not.toContain(fixture.fixture.own.email);expect(stored).not.toContain(recipient);
          await page.getByText("Preparada",{exact:true}).waitFor({timeout:120_000});
          const preparedMetadata=await database.withContext(fixture.fixture.own,async(transaction)=>(await transaction.execute(sql`select version,state,is_selected,is_candidate,selected_version,candidate_version from public.tenant_messaging_connections where id=${connectionId}`)).rows[0]);expect(preparedMetadata).toEqual({version:4,state:"ready",is_selected:false,is_candidate:true,selected_version:null,candidate_version:2});
          if(name==="chromium"&&width===1280)await captureAdmissionReview(page,"phone-tested",[recipient,credential,receivedCode,fixture.sessionToken,secret,fixture.fixture.own.email,fixture.context.actorUserId],"connection-phone-setup-captures.json");
          await database.withContext(fixture.fixture.own,(transaction)=>transaction.execute(sql`insert into public.admission_email_settings(tribe_id,enabled,enabled_at) values (${tribeId},true,clock_timestamp())`));await refreshRecency("activate_messaging_connection");const rejectedSelection=page.waitForResponse((response)=>new URL(response.url()).pathname===`/api/tribes/${slug}/messaging/connections/${connectionId}/activate`,{timeout:240_000});await page.getByRole("checkbox",{name:/Confirmo que quiero usar esta candidata/}).check();await page.getByRole("button",{name:"Activar candidata",exact:true}).click();const denied=await rejectedSelection;expect(await denied.json()).toMatchObject({code:"missing_capability"});await page.getByRole("alert").getByText("La academia todavía no tiene preparado el canal necesario.",{exact:true}).waitFor({timeout:120_000});expect(providerRequests).toBe(3);
          if(name==="chromium"&&width===1280)await captureAdmissionReview(page,"phone-email-required",[recipient,credential,receivedCode,fixture.sessionToken,secret,fixture.fixture.own.email,fixture.context.actorUserId],"connection-phone-setup-captures.json");
          const stillPrepared=await database.withContext(fixture.fixture.own,async(transaction)=>({connection:(await transaction.execute(sql`select version,state,is_selected,is_candidate,selected_version,candidate_version from public.tenant_messaging_connections where id=${connectionId}`)).rows[0],email:(await transaction.execute(sql`select enabled,version from public.admission_email_settings where tribe_id=${tribeId}`)).rows[0]}));expect(stillPrepared).toEqual({connection:preparedMetadata,email:{enabled:true,version:1}});await database.withContext(fixture.fixture.own,(transaction)=>transaction.execute(sql`update public.admission_email_settings set enabled=false,version=version+1 where tribe_id=${tribeId}`));
          await page.getByRole("button",{name:"Consultar conexión actual",exact:true}).click();await page.getByText("La conexión actual quedó consultada. Revisá los datos y confirmá otra vez.",{exact:true}).waitFor({timeout:240_000});await page.waitForFunction(()=>{const button=Array.from(document.querySelectorAll("button")).find((element)=>element.textContent?.trim()==="Consultar conexión actual");return Boolean(button&&!button.disabled);},{},{timeout:120_000});expect(await page.getByRole("alert").filter({hasText:"La academia todavía no tiene preparado el canal necesario."}).count()).toBe(0);console.log(JSON.stringify({phase:"current_read_alert_owners",alerts:await page.getByRole("alert").evaluateAll((elements)=>elements.map((element)=>({tag:element.tagName,host:(element.getRootNode() as ShadowRoot).host?.tagName??null})))}));
          await refreshRecency("activate_messaging_connection");expect(await page.getByRole("button",{name:"Activar candidata",exact:true}).isDisabled()).toBe(true);
          if(name==="chromium"&&width===1280)await captureAdmissionReview(page,"phone-activation-confirmation",[recipient,credential,receivedCode,fixture.sessionToken,secret,fixture.fixture.own.email,fixture.context.actorUserId],"connection-phone-setup-captures.json");
          const activationPath=`**/api/tribes/${slug}/messaging/connections/${connectionId}/activate`;await page.route(activationPath,async(route)=>{let response;try{response=await route.fetch({timeout:240_000});}catch{throw new Error("Activation test transport failed before controlled response loss");}const result=await response.json();expect({status:response.status(),state:result.result?.state}).toEqual({status:200,state:"active"});await route.abort("failed");});
          await page.getByRole("checkbox",{name:/Confirmo que quiero usar esta candidata/}).check();await page.getByRole("button",{name:"Activar candidata",exact:true}).click();await page.getByRole("button",{name:"Consultar guardado",exact:true}).waitFor({timeout:240_000});await page.waitForFunction(()=>{const button=Array.from(document.querySelectorAll("button")).find((element)=>element.textContent?.trim()==="Consultar guardado");return Boolean(button&&!button.disabled);},{},{timeout:240_000});expect(providerRequests).toBe(3);await page.unroute(activationPath);await page.getByRole("button",{name:"Consultar guardado",exact:true}).click();await page.getByRole("heading",{name:"Conexión seleccionada",exact:true}).waitFor({timeout:120_000});expect(await page.getByRole("heading",{name:"Conexión candidata",exact:true}).count()).toBe(0);expect(providerRequests).toBe(3);expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)).toBe(false);
          const selection=await database.withContext(fixture.fixture.own,async(transaction)=>({connection:(await transaction.execute(sql`select state,is_selected,is_candidate,selected_version,candidate_version from public.tenant_messaging_connections where id=${connectionId}`)).rows[0],policy:(await transaction.execute(sql`select requires_additional_verification from public.academy_admission_policies where tribe_id=${tribeId}`)).rows,email:(await transaction.execute(sql`select enabled,version from public.admission_email_settings where tribe_id=${tribeId}`)).rows[0]}));expect(selection.connection).toEqual({state:"active",is_selected:true,is_candidate:false,selected_version:2,candidate_version:null});expect(selection.policy).toEqual([]);expect(selection.email).toEqual({enabled:false,version:2});
          if(name==="chromium"&&width===1280)await captureAdmissionReview(page,"phone-selected",[recipient,credential,receivedCode,fixture.sessionToken,secret,fixture.fixture.own.email,fixture.context.actorUserId],"connection-phone-setup-captures.json");
          const counts=await database.withContext(fixture.fixture.own,async(transaction)=>(await transaction.execute(sql`select (select count(*)::int from public.message_deliveries where tribe_id=${tribeId}) as deliveries,(select count(*)::int from public.message_delivery_attempts where tribe_id=${tribeId}) as attempts,(select count(*)::int from public.messaging_usage_reservations where tribe_id=${tribeId}) as reservations,(select count(*)::int from public.academy_admission_verification_proofs where tribe_id=${tribeId}) as admission_proofs,(select count(*)::int from public.global_identity_evidence where user_id=${fixture.context.actorUserId}) as global_evidence`)).rows[0]);expect(counts).toEqual({deliveries:1,attempts:1,reservations:1,admission_proofs:0,global_evidence:0});
        }finally{await page.unrouteAll({behavior:"ignoreErrors"});await context.close();await browser.close();}
      },{preloadModules:[join(process.cwd(),"tests/support/native-zavu-provider-transport.mjs")],environment:{ADMISSION_TEST_ZAVU_CREDENTIAL:credential,ADMISSION_TEST_ZAVU_SENDER_ID:senderId,ADMISSION_TEST_ZAVU_RECIPIENT:recipient,ADMISSION_TEST_ZAVU_DIAGNOSTIC_CHANNEL:"sms",ADMISSION_TEST_ZAVU_TEST_MODE:"false"},onProviderRequest:()=>{providerRequests+=1;},onDiagnosticCode:(code)=>{receivedCode=code;},onDispatchObservation:(observation)=>{if(dispatchObservations.length<20)dispatchObservations.push(observation);}}));
    });
  },1_200_000);
});
