/** @vitest-environment node */
/** Exercises actual local compromise effects and original replay against protected SQL evidence/accounting. @module messaging-connection-compromise-tests */
import { randomBytes, randomUUID } from "node:crypto";
import { sql } from "drizzle-orm";
import { describe, expect, it } from "vitest";
import { withAcademyAdmissionDatabase } from "@/tests/support/academy-admission-database";
import { prepareMessagingConnectionCreation } from "@/tests/support/messaging-connection-fixture";
import { seedPreviousMessagingSelection } from "@/tests/support/messaging-selection-fixture";
import { PostgresMessagingConnectionSuspension } from "@/src/modules/messaging/infrastructure/repositories/postgres-messaging-connection-suspension";
import { PostgresMessagingLifecycleDependencies } from "@/src/modules/academy-admissions/infrastructure/repositories/postgres-messaging-lifecycle-dependencies";
import type { MessagingConnectionLifecycleContext } from "@/src/modules/messaging/domain/repositories/messaging-connection-lifecycle";
import { createAcademyApprovedMembershipWriter } from "@/src/modules/tribes/infrastructure/repositories/apply-approved-academy-membership";
import { createPostgresAdmissionNotificationObligationWriter } from "@/src/modules/notifications/infrastructure/repositories/admission-notification-obligation-writer";

describe.skipIf(process.env.RUN_ADMISSION_SQL_TESTS!=="1")("compromised connection evidence",()=>{
  it("should preserve actual approved membership, applied proof and decision provenance after a compromised connection is suspended",async()=>{
    await withAcademyAdmissionDatabase(async(database)=>{
      const fixture=await prepareMessagingConnectionCreation(database);for(const migration of["20261005092500_guard_messaging_attempts.sql","20261005093000_guard_academy_membership_sources.sql","20261005100000_guard_messaging_secret_retirement.sql","20261006200000_scope_admission_audit_operations.sql","20261006220000_extend_admission_notifications.sql","20261007005000_read_admission_reviews.sql","20261007030000_capture_admission_decision_evidence.sql"])await database.applyMigration(migration);
      await database.withContext(fixture.fixture.own,(transaction)=>transaction.execute(sql`insert into public.messaging_usage_policies(tribe_id) values (${fixture.context.tribeId})`));const created=await fixture.repository.create(fixture.context,{operationId:randomUUID(),confirmed:true,providerId:"zavu",name:"Candidata conservada",apiKey:randomUUID()});if(created.state!=="completed")throw new Error("Expected candidate fixture");const previous=await seedPreviousMessagingSelection(database,fixture,created.result.id);
      await database.withContext(fixture.fixture.own,async(transaction)=>{await transaction.execute(sql`insert into public.tribe_academy_settings(tribe_id,access_model,admission_enabled) values (${fixture.context.tribeId},'academy',true)`);const activatedAt=(await transaction.execute<{now:Date|string}>(sql`select clock_timestamp() as now`)).rows[0].now;await transaction.execute(sql`update public.academy_admission_policies set is_open=true,version=version+1,activated_at=${activatedAt} where tribe_id=${fixture.context.tribeId}`);await transaction.execute(sql`update public.tribes set admissions_control_activated_at=${activatedAt} where id=${fixture.context.tribeId}`);});
      // Seed a protected historical approval with real membership/notice owners. The current manual/OFF approval route cannot yet accept local evidence (US9).
      await database.withContext(fixture.fixture.own,async(transaction)=>{
        const decisionId=randomUUID(),effectId=randomUUID(),proof=(await transaction.execute<{verified_at:Date|string}>(sql`select verified_at from public.academy_admission_verification_proofs where id=${previous.used.proofId} and applied_request_id=${previous.requestId} for share`)).rows[0],evidence={kind:"local",referenceId:previous.used.proofId,verifiedAt:new Date(proof.verified_at).toISOString()};
        await transaction.execute(sql`insert into public.academy_admission_decisions(id,request_id,tribe_id,user_id,request_version,outcome,actor_user_id,actor_kind,rule,policy_version,verification_epoch,internal_reason,membership_effect_id,evidence_snapshot) values (${decisionId},${previous.requestId},${fixture.context.tribeId},${previous.used.userId},2,'approved',${fixture.context.actorUserId},'user','manual_review',8,5,'Revisión histórica sintética',${effectId},${JSON.stringify(evidence)}::jsonb)`);
        await transaction.execute(sql`update public.academy_admission_requests set status='approved',version=version+1,decision_id=${decisionId} where id=${previous.requestId} and status='pending' and version=2`);
        expect(await createAcademyApprovedMembershipWriter(transaction).apply({tribeId:fixture.context.tribeId,userId:previous.used.userId,decisionId})).toMatchObject({status:"joined",member:{role:"tribemate",status:"active"}});
        await createPostgresAdmissionNotificationObligationWriter(transaction).record({id:randomUUID(),tribeId:fixture.context.tribeId,admissionRequestId:previous.requestId,applicantUserId:previous.used.userId,event:"approved"});
        await transaction.execute(sql`insert into public.academy_admission_audit_events(tribe_id,actor_user_id,resource_type,resource_id,event_type,rule,resource_version) values (${fixture.context.tribeId},${fixture.context.actorUserId},'admission_request',${previous.requestId},'approved','manual_review',3)`);
      });
      /** @returns Stable admitted facts from actual owner effects, without contact or credentials. */
      const admitted=()=>database.withContext(fixture.fixture.own,async(transaction)=>({member:(await transaction.execute(sql`select id,role,status,admission_membership_effect_id from public.tribe_members where tribe_id=${fixture.context.tribeId} and user_id=${previous.used.userId}`)).rows[0],decisions:(await transaction.execute(sql`select id,outcome,evidence_snapshot,membership_effect_id from public.academy_admission_decisions where request_id=${previous.requestId}`)).rows}));
      const before=await previous.snapshot(),approved=await admitted();expect(approved.member).toMatchObject({role:"tribemate",status:"active",admission_membership_effect_id:expect.anything()});expect(approved.decisions).toEqual([expect.objectContaining({outcome:"approved",evidence_snapshot:expect.objectContaining({kind:"local",referenceId:previous.used.proofId})})]);
      const context=await database.withContext(fixture.fixture.own,async(transaction):Promise<MessagingConnectionLifecycleContext>=>{
        const now=new Date((await transaction.execute<{now:Date|string}>(sql`select clock_timestamp() as now`)).rows[0].now),validUntil=new Date(now.getTime()+540_000),intentId=randomUUID();
        await transaction.execute(sql`insert into public.global_reauthentication_intents(id,user_id,original_session_id,account_id,provider_subject,tribe_id,operation,resource_id,return_path,nonce_hash,state,created_at,expires_at,consumed_at) values (${intentId},${fixture.context.actorUserId},${fixture.context.sessionId},${fixture.context.accountId},${fixture.context.subject},${fixture.context.tribeId},'suspend_messaging_connection',${previous.connectionId},'/synthetic-approved-compromise',${randomBytes(32)},'consumed',${now},${validUntil},${now})`);
        await transaction.execute(sql`insert into public.recent_authentication_evidence(intent_id,user_id,account_id,provider_subject,session_id,tribe_id,operation,resource_id,authenticated_at,verified_at,valid_until) values (${intentId},${fixture.context.actorUserId},${fixture.context.accountId},${fixture.context.subject},${fixture.context.sessionId},${fixture.context.tribeId},'suspend_messaging_connection',${previous.connectionId},${now},${now},${validUntil})`);return{...fixture.context,connectionId:previous.connectionId,resourceId:previous.connectionId,operation:"suspend_messaging_connection",authenticatedAt:now,validUntil};
      });
      const owner=new PostgresMessagingConnectionSuspension((_context,run)=>database.withContext(fixture.fixture.own,run),async()=>fixture.fixture.config,(transaction)=>new PostgresMessagingLifecycleDependencies(transaction,async()=>true));expect(await owner.suspend(context,{operationId:randomUUID(),confirmed:true,expectedVersion:1,reason:"suspected_compromise"})).toMatchObject({state:"completed",result:{state:"suspended",version:2}});
      const after=await previous.snapshot();expect(after.proofs.find((proof)=>proof.id===previous.used.proofId)).toEqual(before.proofs.find((proof)=>proof.id===previous.used.proofId));expect(after.request).toEqual(before.request);expect(await admitted()).toEqual(approved);expect(after.proofs.find((proof)=>proof.id===previous.unused.proofId)).toMatchObject({status:"invalid",invalidation_reason:"suspected_compromise"});expect(after.policy).toEqual(before.policy);expect(after.usage).toEqual(before.usage);expect(after.reservations).toEqual(before.reservations);
    });
  },600_000);
  it("should revoke unused and pending-applied evidence while preserving policy, request provenance, accepted/unknown deliveries and charged reservations",async()=>{
    await withAcademyAdmissionDatabase(async(database)=>{
      const fixture=await prepareMessagingConnectionCreation(database);await database.applyMigration("20261005092500_guard_messaging_attempts.sql");await database.applyMigration("20261005100000_guard_messaging_secret_retirement.sql");
      await database.withContext(fixture.fixture.own,(transaction)=>transaction.execute(sql`insert into public.messaging_usage_policies(tribe_id) values (${fixture.context.tribeId})`));
      const created=await fixture.repository.create(fixture.context,{operationId:randomUUID(),confirmed:true,providerId:"zavu",name:"Candidata conservada",apiKey:randomUUID()});if(created.state!=="completed")throw new Error("Expected candidate fixture");
      const previous=await seedPreviousMessagingSelection(database,fixture,created.result.id),before=await previous.snapshot();
      const context=await database.withContext(fixture.fixture.own,async(transaction):Promise<MessagingConnectionLifecycleContext>=>{
        const now=new Date((await transaction.execute<{now:Date|string}>(sql`select clock_timestamp() as now`)).rows[0].now),validUntil=new Date(now.getTime()+540_000),intentId=randomUUID();
        await transaction.execute(sql`insert into public.global_reauthentication_intents(id,user_id,original_session_id,account_id,provider_subject,tribe_id,operation,resource_id,return_path,nonce_hash,state,created_at,expires_at,consumed_at) values (${intentId},${fixture.context.actorUserId},${fixture.context.sessionId},${fixture.context.accountId},${fixture.context.subject},${fixture.context.tribeId},'suspend_messaging_connection',${previous.connectionId},'/synthetic-compromise',${randomBytes(32)},'consumed',${now},${validUntil},${now})`);
        await transaction.execute(sql`insert into public.recent_authentication_evidence(intent_id,user_id,account_id,provider_subject,session_id,tribe_id,operation,resource_id,authenticated_at,verified_at,valid_until) values (${intentId},${fixture.context.actorUserId},${fixture.context.accountId},${fixture.context.subject},${fixture.context.sessionId},${fixture.context.tribeId},'suspend_messaging_connection',${previous.connectionId},${now},${now},${validUntil})`);
        return{...fixture.context,connectionId:previous.connectionId,resourceId:previous.connectionId,operation:"suspend_messaging_connection",authenticatedAt:now,validUntil};
      });
      const owner=new PostgresMessagingConnectionSuspension((_context,run)=>database.withContext(fixture.fixture.own,run),async()=>fixture.fixture.config,(transaction)=>new PostgresMessagingLifecycleDependencies(transaction,async()=>true)),input={operationId:randomUUID(),confirmed:true as const,expectedVersion:1,reason:"suspected_compromise" as const};
      const interruptedId=randomUUID(),interrupted=new PostgresMessagingConnectionSuspension((_context,run)=>database.withContext(fixture.fixture.own,run),async()=>fixture.fixture.config,(transaction)=>{
        const dependencies=new PostgresMessagingLifecycleDependencies(transaction,async()=>true);return{readRetirementFacts:(scope)=>dependencies.readRetirementFacts(scope),retireReferences:(scope,ledgerId)=>dependencies.retireReferences(scope,ledgerId),invalidateCompromisedEvidence:async(scope,ledgerId)=>{await dependencies.invalidateCompromisedEvidence(scope,ledgerId);throw new Error("Synthetic admission dependency failed after staged compromise effects");}};
      });
      await expect(interrupted.suspend(context,{...input,operationId:interruptedId})).rejects.toMatchObject({code:"operation_unresolved",operationId:interruptedId});expect(await previous.snapshot()).toEqual(before);
      const interruptedLedger=await database.withContext(fixture.fixture.own,async(transaction)=>(await transaction.execute<{state:string;audit_count:number}>(sql`select operation.state,(select count(*)::int from public.academy_admission_audit_events audit where audit.operation_id=operation.id) as audit_count from public.academy_admission_operations operation where operation.tribe_id=${context.tribeId} and operation.idempotency_key=${interruptedId} and operation.operation_type='suspend_messaging_connection'`)).rows[0]);expect(interruptedLedger).toEqual({state:"started",audit_count:0});
      expect(await owner.suspend(context,input)).toMatchObject({state:"completed",result:{id:previous.connectionId,version:2,state:"suspended",reason:"suspected_compromise",changed:true}});
      const after=await previous.snapshot();expect(after.policy).toEqual(before.policy);expect(after.request).toEqual(before.request);expect(after.usage).toEqual(before.usage);expect(after.reservations).toEqual(before.reservations);expect(after.secrets).toEqual(before.secrets);
      expect(after.connections.find((connection)=>connection.id===created.result.id)).toEqual(before.connections.find((connection)=>connection.id===created.result.id));expect(after.connections.find((connection)=>connection.id===previous.connectionId)).toMatchObject({state:"suspended",is_selected:true,selected_version:1});
      for(const evidence of[previous.used,previous.unused])expect(after.proofs.find((proof)=>proof.id===evidence.proofId)).toMatchObject({status:"invalid",invalidation_reason:"suspected_compromise"});
      expect(after.proofs.find((proof)=>proof.id===previous.used.proofId)).toMatchObject({applied_request_id:previous.requestId,applied_at:before.proofs.find((proof)=>proof.id===previous.used.proofId)!.applied_at});
      for(const deliveryId of[previous.acceptedDeliveryId,previous.unknownDeliveryId])expect(after.deliveries.find((delivery)=>delivery.id===deliveryId)).toEqual(before.deliveries.find((delivery)=>delivery.id===deliveryId));
      for(const evidence of[previous.used,previous.unused])expect(after.deliveries.find((delivery)=>delivery.id===evidence.deliveryId)).toMatchObject({state:"cancelled",last_outcome:"suspected_compromise"});
      expect(await owner.suspend(context,input)).toMatchObject({state:"completed",replayed:true,result:{version:2,changed:true}});expect(await previous.snapshot()).toEqual(after);
    });
  },600_000);
});
