/** @vitest-environment node */
/** Exercises explicit lifecycle controls and lost-response recovery with actual Next/auth/SQL and closed provider transport. @module messaging-lifecycle-browser-ui-tests */
import { randomBytes, randomUUID } from "node:crypto";
import { join } from "node:path";
import { chromium, webkit } from "@playwright/test";
import { sql } from "drizzle-orm";
import { describe, expect, it } from "vitest";
import { makeSignature } from "better-auth/crypto";
import { withAcademyAdmissionDatabase } from "@/tests/support/academy-admission-database";
import { prepareMessagingConnectionCreation } from "@/tests/support/messaging-connection-fixture";
import { withAdmissionNextServer } from "@/tests/support/admission-next-server";
import { captureAdmissionReview } from "@/tests/support/admission-review-capture";
import { messagingConnectionOperationRecoverySchema } from "@/src/modules/messaging/application/results/messaging-connection-operation-result";

describe.skipIf(process.env.RUN_ADMISSION_BROWSER_TESTS!=="1")("native local lifecycle UI",()=>{
  it.each([{name:"chromium",engine:chromium,width:1280},{name:"chromium",engine:chromium,width:390},{name:"webkit",engine:webkit,width:1280},{name:"webkit",engine:webkit,width:390}])("should suspend then retire a candidate with fresh consent and recover a lost original on $name at $width",async({name,engine,width})=>{
    await withAcademyAdmissionDatabase(async(database)=>{
      const fixture=await prepareMessagingConnectionCreation(database),tribeId=fixture.context.tribeId,slug=`connection-${tribeId}`,credential=randomUUID();
      for(const migration of["20261005093000_guard_academy_membership_sources.sql","20261007001000_read_public_admission_overview.sql","20261005100000_guard_messaging_secret_retirement.sql","20261006160000_purge_verification_delivery_material.sql","20261008161500_create_admission_email_settings.sql"])await database.applyMigration(migration);
      await database.withContext(fixture.fixture.own,(transaction)=>transaction.execute(sql`insert into public.tribe_academy_settings(tribe_id,access_model,admission_enabled) values (${tribeId},'academy',true)`));let providerRequests=0;
      await database.withServerEnvironment((environment)=>withAdmissionNextServer(environment,slug,async(origin,secret)=>{
        const cookie=encodeURIComponent(`${fixture.sessionToken}.${await makeSignature(fixture.sessionToken,secret)}`),headers={cookie:`better-auth.session_token=${cookie}`,origin,"content-type":"application/json"},base=`${origin}/api/tribes/${slug}/messaging`;
        const creation=await fetch(`${base}/connections`,{method:"POST",headers,body:JSON.stringify({operationId:randomUUID(),confirmed:true,providerId:"zavu",name:"Conexión de ejemplo",apiKey:credential})});expect(creation.status).toBe(201);const connectionId=(await creation.json()).result.id;
        /** @param operation - Local action requiring independently scoped native evidence. @returns After creating synthetic current consent, without Google/provider transport. */
        const refreshRecency=async(operation:"suspend_messaging_connection"|"disconnect_messaging_connection")=>database.withContext(fixture.fixture.own,async(transaction)=>{
          const now=new Date((await transaction.execute<{now:Date|string}>(sql`select clock_timestamp() as now`)).rows[0].now),validUntil=new Date(now.getTime()+540_000),intentId=randomUUID();
          await transaction.execute(sql`insert into public.global_reauthentication_intents(id,user_id,original_session_id,account_id,provider_subject,tribe_id,operation,resource_id,return_path,nonce_hash,state,created_at,expires_at,consumed_at) values (${intentId},${fixture.context.actorUserId},${fixture.context.sessionId},${fixture.context.accountId},${fixture.context.subject},${tribeId},${operation},${connectionId},'/synthetic-lifecycle-ui',${randomBytes(32)},'consumed',${now},${validUntil},${now})`);
          await transaction.execute(sql`insert into public.recent_authentication_evidence(intent_id,user_id,account_id,provider_subject,session_id,tribe_id,operation,resource_id,authenticated_at,verified_at,valid_until) values (${intentId},${fixture.context.actorUserId},${fixture.context.accountId},${fixture.context.subject},${fixture.context.sessionId},${tribeId},${operation},${connectionId},${now},${now},${validUntil})`);
        });
        const browser=await engine.launch({headless:true}),context=await browser.newContext({viewport:{width,height:900},reducedMotion:"reduce"}),page=await context.newPage(),errors:string[]=[],posts:{path:string;body:{operationId:string;expectedVersion:number}}[]=[];page.on("pageerror",(error)=>errors.push(error.message));page.on("request",(request)=>{if(request.method()==="POST"&&/\/(suspend|disconnect)$/.test(new URL(request.url()).pathname))posts.push({path:new URL(request.url()).pathname,body:request.postDataJSON()});});
        try{
          await context.addCookies([{name:"better-auth.session_token",value:cookie,url:origin,httpOnly:true,sameSite:"Lax"}]);await page.goto(`${origin}/${slug}/academia/admissions/messaging/connections`,{waitUntil:"networkidle",timeout:120_000});
          const consent=page.getByRole("checkbox",{name:/Revisé la conexión, la acción/}),local=page.getByRole("region",{name:"Seguridad y retiro de conexiones"});await consent.waitFor();await page.waitForFunction(()=>!(document.querySelector('button[role="checkbox"][id$="-consent"]') as HTMLButtonElement|null)?.disabled);
          expect(await page.getByRole("button",{name:"Suspender conexión",exact:true}).isDisabled()).toBe(true);expect(posts).toEqual([]);await refreshRecency("suspend_messaging_connection");
          if(name==="chromium"&&width===1280)await captureAdmissionReview(page,"lifecycle-security-confirmation",[credential,fixture.sessionToken,secret,fixture.fixture.own.email,fixture.context.actorUserId],"connection-lifecycle-captures.json",{selector:'section[aria-label="Seguridad y retiro de conexiones"]'});
          const suspendPath=`**/api/tribes/${slug}/messaging/connections/${connectionId}/suspend`;await page.route(suspendPath,async(route)=>{let response;try{response=await route.fetch({timeout:240_000});}catch{throw new Error("Lifecycle suspension test transport failed before controlled response loss");}expect(response.status()).toBe(200);expect(await response.json()).toMatchObject({state:"completed",result:{id:connectionId,version:2,state:"suspended",reason:"security_stop"}});await route.abort("failed");});
          await consent.check();await page.getByRole("button",{name:"Suspender conexión",exact:true}).click();await page.getByRole("button",{name:"Consultar guardado",exact:true}).waitFor({timeout:240_000});await page.waitForFunction(()=>{const button=Array.from(document.querySelectorAll("button")).find((element)=>element.textContent?.trim()==="Consultar guardado");return Boolean(button&&!button.disabled);},{},{timeout:240_000});expect(posts).toHaveLength(1);expect(posts[0].body.expectedVersion).toBe(1);await page.unroute(suspendPath);
          await page.reload({waitUntil:"networkidle",timeout:120_000});await page.getByRole("button",{name:"Consultar guardado",exact:true}).waitFor({timeout:120_000});const originalResponse=page.waitForResponse((response)=>new URL(response.url()).pathname===`/api/tribes/${slug}/messaging/operations/${posts[0].body.operationId}`,{timeout:120_000});await page.getByRole("button",{name:"Consultar guardado",exact:true}).click();const original=await originalResponse,originalBody=await original.json();expect(original.status()).toBe(200);expect(messagingConnectionOperationRecoverySchema.safeParse(originalBody).success).toBe(true);expect(originalBody).toMatchObject({state:"completed",type:"suspend_messaging_connection",operationId:posts[0].body.operationId,result:{id:connectionId,state:"suspended",version:2,reason:"security_stop"}});await page.getByText("Suspendida",{exact:true}).waitFor({timeout:120_000});await page.waitForFunction(()=>!Array.from(document.querySelectorAll("button")).some((element)=>element.textContent?.trim()==="Consultar guardado"),{},{timeout:120_000});expect(posts).toHaveLength(1);expect(await consent.isChecked()).toBe(false);
          if(name==="chromium"&&width===1280)await captureAdmissionReview(page,"lifecycle-security-recovered",[credential,fixture.sessionToken,secret,fixture.fixture.own.email,fixture.context.actorUserId],"connection-lifecycle-captures.json");
          await local.getByRole("combobox",{name:"Acción local",exact:true}).click();await page.getByRole("option",{name:"Desconectar y retirar recursos",exact:true}).click();expect(await page.getByRole("button",{name:"Desconectar conexión",exact:true}).isDisabled()).toBe(true);await refreshRecency("disconnect_messaging_connection");
          if(name==="chromium"&&width===1280)await captureAdmissionReview(page,"lifecycle-retirement-confirmation",[credential,fixture.sessionToken,secret,fixture.fixture.own.email,fixture.context.actorUserId],"connection-lifecycle-captures.json",{selector:'section[aria-label="Seguridad y retiro de conexiones"]'});
          await consent.check();await page.getByRole("button",{name:"Desconectar conexión",exact:true}).click();await local.getByText("No hay conexiones vigentes para gestionar.",{exact:true}).waitFor({timeout:240_000});expect(posts).toHaveLength(2);expect(posts[1].body.expectedVersion).toBe(2);expect(posts[1].body.operationId).not.toBe(posts[0].body.operationId);expect(providerRequests).toBe(0);expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)).toBe(false);
          const stored=await database.withContext(fixture.fixture.own,async(transaction)=>(await transaction.execute(sql`select state,version,is_selected,is_candidate,retired_at from public.tenant_messaging_connections where id=${connectionId}`)).rows[0]);expect(stored).toMatchObject({state:"disconnected",version:3,is_selected:false,is_candidate:false,retired_at:expect.anything()});
          if(name==="chromium"&&width===1280)await captureAdmissionReview(page,"lifecycle-retired",[credential,fixture.sessionToken,secret,fixture.fixture.own.email,fixture.context.actorUserId],"connection-lifecycle-captures.json");
        }finally{try{await page.unrouteAll({behavior:"ignoreErrors"});}finally{await context.close();await browser.close();}}
      },{preloadModules:[join(process.cwd(),"tests/support/native-zavu-provider-transport.mjs")],environment:{ADMISSION_TEST_ZAVU_CREDENTIAL:credential},onProviderRequest:()=>{providerRequests+=1;}}));
    });
  },900_000);
});
