/** @vitest-environment node */
/** Exercises explicit UI diagnostic emission and local code verification with real Next/auth/SQL/SDK and a closed synthetic provider. @module messaging-diagnostic-browser-ui-tests */
import {randomBytes,randomUUID} from "node:crypto";
import {join} from "node:path";
import {chromium,webkit} from "@playwright/test";
import {sql} from "drizzle-orm";
import {describe,expect,it} from "vitest";
import {makeSignature} from "better-auth/crypto";
import {withAcademyAdmissionDatabase} from "@/tests/support/academy-admission-database";
import {prepareMessagingConnectionCreation} from "@/tests/support/messaging-connection-fixture";
import {withAdmissionNextServer} from "@/tests/support/admission-next-server";
import {captureAdmissionReview} from "@/tests/support/admission-review-capture";

describe.skipIf(process.env.RUN_ADMISSION_BROWSER_TESTS!=="1")("native diagnostic UI",()=>{
  it.each([{name:"chromium",engine:chromium,width:1280},{name:"chromium",engine:chromium,width:390},{name:"webkit",engine:webkit,width:1280},{name:"webkit",engine:webkit,width:390}])("should issue once and verify the received code after lost responses on $name at $width",async({name,engine,width})=>{
    await withAcademyAdmissionDatabase(async(database)=>{
      const fixture=await prepareMessagingConnectionCreation(database),tribeId=fixture.context.tribeId,slug=`connection-${tribeId}`,credential=randomUUID(),senderId=randomUUID();
      for(const migration of["20261005092500_guard_messaging_attempts.sql","20261005093000_guard_academy_membership_sources.sql","20261007001000_read_public_admission_overview.sql","20261005100000_guard_messaging_secret_retirement.sql","20261006120000_index_messaging_contact_windows.sql","20261006140000_claim_messaging_deliveries_fairly.sql","20261006160000_purge_verification_delivery_material.sql","20261006230000_bind_credential_validation_usage.sql","20261007050000_claim_scoped_diagnostic_delivery.sql"])await database.applyMigration(migration);
      await database.withContext(fixture.fixture.own,(transaction)=>transaction.execute(sql`insert into public.tribe_academy_settings(tribe_id,access_model,admission_enabled) values (${tribeId},'academy',true)`));let providerRequests=0,receivedCode="";
      await database.withServerEnvironment((environment)=>withAdmissionNextServer(environment,slug,async(origin,secret)=>{
        const cookieValue=encodeURIComponent(`${fixture.sessionToken}.${await makeSignature(fixture.sessionToken,secret)}`),headers={cookie:`better-auth.session_token=${cookieValue}`,origin,"content-type":"application/json"},base=`${origin}/api/tribes/${slug}/messaging`;
        const created=await fetch(`${base}/connections`,{method:"POST",headers,body:JSON.stringify({operationId:randomUUID(),confirmed:true,providerId:"zavu",name:"Prueba de canal",apiKey:credential})});expect(created.status).toBe(201);const connectionId=(await created.json()).result.id;
        const refreshRecency=async(operation:string)=>database.withContext(fixture.fixture.own,async(transaction)=>{const now=new Date((await transaction.execute<{now:string}>(sql`select clock_timestamp() as now`)).rows[0].now),validUntil=new Date(now.getTime()+540_000),intentId=randomUUID(),resourceId=operation==="initialize_messaging_usage"?tribeId:connectionId;await transaction.execute(sql`insert into public.global_reauthentication_intents(id,user_id,original_session_id,account_id,provider_subject,tribe_id,operation,resource_id,return_path,nonce_hash,state,created_at,expires_at,consumed_at) values (${intentId},${fixture.context.actorUserId},${fixture.context.sessionId},${fixture.context.accountId},${fixture.context.subject},${tribeId},${operation},${resourceId},'/synthetic-ui-diagnostic',${randomBytes(32)},'consumed',${now},${validUntil},${now})`);await transaction.execute(sql`insert into public.recent_authentication_evidence(intent_id,user_id,account_id,provider_subject,session_id,tribe_id,operation,resource_id,authenticated_at,verified_at,valid_until) values (${intentId},${fixture.context.actorUserId},${fixture.context.accountId},${fixture.context.subject},${fixture.context.sessionId},${tribeId},${operation},${resourceId},${now},${now},${validUntil})`);});
        await refreshRecency("configure_messaging_connection");const configured=await fetch(`${base}/connections/${connectionId}/configuration`,{method:"PUT",headers,body:JSON.stringify({operationId:randomUUID(),confirmed:true,expectedVersion:1,channel:"email",senderId})});expect(configured.status).toBe(200);
        await refreshRecency("validate_messaging_connection");const validated=await fetch(`${base}/connections/${connectionId}/validate`,{method:"POST",headers,body:JSON.stringify({operationId:randomUUID(),confirmed:true,expectedVersion:2})});expect(validated.status).toBe(200);expect(providerRequests).toBe(2);
        await refreshRecency("initialize_messaging_usage");const usage=await fetch(`${base}/usage-policy`,{method:"POST",headers,body:JSON.stringify({operationId:randomUUID(),confirmed:true})});expect(usage.status).toBe(200);expect(await usage.json()).toMatchObject({state:"completed",result:{version:1,allowedCountries:[],verificationDailyLimit:100,notificationDailyLimit:200}});await refreshRecency("diagnose_messaging_connection");await refreshRecency("verify_messaging_diagnostic");
        const browser=await engine.launch({headless:true}),context=await browser.newContext({viewport:{width,height:900},reducedMotion:"reduce"}),page=await context.newPage(),errors:string[]=[];page.on("pageerror",(error)=>errors.push(error.message));
        try{
          await context.addCookies([{name:"better-auth.session_token",value:cookieValue,url:origin,httpOnly:true,sameSite:"Lax"}]);await page.goto(`${origin}/${slug}/academia/admissions/messaging/connections`,{waitUntil:"networkidle",timeout:120_000});await page.getByLabel("Destino de la prueba",{exact:true}).waitFor();await page.waitForFunction(()=>!(document.querySelector('input[type="email"]') as HTMLInputElement|null)?.disabled);expect(providerRequests).toBe(2);
          if(name==="chromium"&&width===1280)await captureAdmissionReview(page,"diagnostic-empty",[credential,fixture.sessionToken,secret,fixture.fixture.own.email,fixture.context.actorUserId],"connection-diagnostic-captures.json");
          let issuedDeliveryId="";
          const issuePath=`**/api/tribes/${slug}/messaging/connections/${connectionId}/diagnostics`;await page.route(issuePath,async(route)=>{let response;try{response=await route.fetch({timeout:240_000});}catch{throw new Error("Diagnostic issue test transport failed before controlled response loss");}const result=await response.json();expect({status:response.status(),outcome:result.result?.outcome,code:result.code}).toMatchObject({status:200,outcome:"issued"});issuedDeliveryId=result.result.deliveryId;await route.abort("failed");});
          await refreshRecency("diagnose_messaging_connection");
          await page.getByLabel("Destino de la prueba",{exact:true}).fill(fixture.fixture.own.email);await page.getByRole("checkbox",{name:/Confirmo el destino y el consumo/}).check();await page.getByRole("button",{name:"Enviar código de prueba",exact:true}).click();await page.getByRole("button",{name:"Consultar guardado",exact:true}).waitFor({timeout:240_000});await page.waitForFunction(()=>{const button=Array.from(document.querySelectorAll("button")).find((element)=>element.textContent?.trim()==="Consultar guardado");return Boolean(button&&!button.disabled);},{},{timeout:240_000});if(providerRequests!==3){const metadata=await database.withContext(fixture.fixture.own,async(transaction)=>({delivery:(await transaction.execute(sql`select state,last_outcome from public.message_deliveries where id=${issuedDeliveryId} and tribe_id=${tribeId}`)).rows[0],attempts:(await transaction.execute(sql`select state,safe_reason from public.message_delivery_attempts where delivery_id=${issuedDeliveryId} order by sequence`)).rows,reservations:(await transaction.execute<{count:number}>(sql`select count(*)::int as count from public.messaging_usage_reservations where delivery_id=${issuedDeliveryId}`)).rows[0].count}));console.log(JSON.stringify({phase:"diagnostic_dispatch_observation",providerRequests,...metadata}));}expect(providerRequests).toBe(3);expect((await page.getByLabel("Destino de la prueba",{exact:true}).inputValue())==="").toBe(true);
          await page.unroute(issuePath);await page.getByRole("button",{name:"Consultar guardado",exact:true}).click();await page.getByLabel("Código recibido",{exact:true}).waitFor({timeout:120_000});expect(providerRequests).toBe(3);await page.getByRole("button",{name:"Consultar entrega de la prueba",exact:true}).click();await page.getByText("Aceptada por el proveedor",{exact:true}).waitFor({timeout:120_000});expect(providerRequests).toBe(3);
          if(!receivedCode)throw new Error("Expected private synthetic code receipt");if(name==="chromium"&&width===1280)await captureAdmissionReview(page,"diagnostic-issued",[credential,receivedCode,fixture.sessionToken,secret,fixture.fixture.own.email,fixture.context.actorUserId],"connection-diagnostic-captures.json");
          await page.reload({waitUntil:"networkidle",timeout:120_000});await page.getByLabel("Código recibido",{exact:true}).waitFor({timeout:120_000});expect(providerRequests).toBe(3);expect((await page.getByLabel("Código recibido",{exact:true}).inputValue())==="").toBe(true);await page.getByRole("button",{name:"Consultar prueba 1: Correo",exact:true}).click();await page.waitForFunction(()=>{const field=document.querySelector('input[id$="-code"]') as HTMLInputElement|null;return Boolean(field&&!field.disabled);},{},{timeout:120_000});expect(providerRequests).toBe(3);await refreshRecency("verify_messaging_diagnostic");
          const verifyPath=`**/api/tribes/${slug}/messaging/connections/${connectionId}/diagnostics/*/verify`;await page.route(verifyPath,async(route)=>{try{await route.fetch({timeout:240_000});await route.abort("failed");}catch{throw new Error("Diagnostic verify test transport failed before controlled response loss");}});await page.getByLabel("Código recibido",{exact:true}).fill(receivedCode);await page.getByRole("button",{name:"Confirmar código recibido",exact:true}).click();await page.getByRole("button",{name:"Consultar guardado",exact:true}).waitFor({timeout:240_000});await page.waitForFunction(()=>{const button=Array.from(document.querySelectorAll("button")).find((element)=>element.textContent?.trim()==="Consultar guardado");return Boolean(button&&!button.disabled);},{},{timeout:240_000});expect((await page.getByLabel("Código recibido",{exact:true}).inputValue())==="").toBe(true);await page.unroute(verifyPath);await page.getByRole("button",{name:"Consultar guardado",exact:true}).click();await page.getByText("Correo: Canal comprobado",{exact:true}).waitFor({timeout:120_000});expect(providerRequests).toBe(3);expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)).toBe(false);
          const stored=await page.evaluate(()=>Object.values(sessionStorage).join("\n"));expect(stored).not.toContain(credential);expect(stored).not.toContain(receivedCode);expect(stored).not.toContain(fixture.fixture.own.email);
          if(name==="chromium"&&width===1280)await captureAdmissionReview(page,"diagnostic-verified",[credential,receivedCode,fixture.sessionToken,secret,fixture.fixture.own.email,fixture.context.actorUserId],"connection-diagnostic-captures.json");
          const counts=await database.withContext(fixture.fixture.own,async(transaction)=>(await transaction.execute(sql`select (select count(*)::int from public.message_deliveries where tribe_id=${tribeId}) as deliveries,(select count(*)::int from public.message_delivery_attempts where tribe_id=${tribeId}) as attempts,(select count(*)::int from public.messaging_usage_reservations where tribe_id=${tribeId}) as reservations,(select count(*)::int from public.academy_admission_verification_proofs where tribe_id=${tribeId}) as admission_proofs,(select count(*)::int from public.global_identity_evidence where user_id=${fixture.context.actorUserId}) as global_evidence`)).rows[0]);expect(counts).toEqual({deliveries:1,attempts:1,reservations:1,admission_proofs:0,global_evidence:0});
        }finally{await page.unrouteAll({behavior:"ignoreErrors"});await context.close();await browser.close();}
      },{preloadModules:[join(process.cwd(),"tests/support/native-zavu-provider-transport.mjs")],environment:{ADMISSION_TEST_ZAVU_CREDENTIAL:credential,ADMISSION_TEST_ZAVU_SENDER_ID:senderId,ADMISSION_TEST_ZAVU_RECIPIENT:fixture.fixture.own.email,ADMISSION_TEST_ZAVU_TEST_MODE:"false"},onProviderRequest:()=>{providerRequests+=1;},onDiagnosticCode:(code)=>{receivedCode=code;}}));
    });
  },1_200_000);
});
