/** @vitest-environment node */
/** Exercises real local lifecycle HTTP validators and result bindings through own application ports. @module messaging-connection-lifecycle-routes-tests */
import { randomUUID } from "node:crypto";
import { describe, expect, it, vi } from "vitest";
import { createMessagingConnectionLifecycleHandlers } from "@/src/modules/messaging/infrastructure/api/messaging-connection-lifecycle-handlers";
import type { MessagingConnectionLifecycleServices } from "@/src/modules/messaging/infrastructure/api/messaging-connection-lifecycle-handlers";

describe("explicit local connection lifecycle HTTP",()=>{
  it("should reject authority, dependency overrides, unrecognized cause and duplicate compromise flags before opening native services",async()=>{
    const connectionId=randomUUID(),open=vi.fn(),handlers=createMessagingConnectionLifecycleHandlers(open),context={params:Promise.resolve({slug:"synthetic",connectionId})},base={operationId:randomUUID(),confirmed:true,expectedVersion:3};
    for(const body of[{...base,reason:"technical provider detail"},{...base,reason:"security_stop",suspectedCompromise:true},{...base,reason:"security_stop",actorUserId:randomUUID()},{...base,reason:"security_stop",confirmed:false}])expect((await handlers.suspend(new Request(`https://tutribu.example.test/api/tribes/synthetic/messaging/connections/${connectionId}/suspend`,{method:"POST",headers:{origin:"https://tutribu.example.test","content-type":"application/json"},body:JSON.stringify(body)}),context)).status).toBe(400);
    expect((await handlers.disconnect(new Request(`https://tutribu.example.test/api/tribes/synthetic/messaging/connections/${connectionId}/disconnect`,{method:"POST",headers:{origin:"https://tutribu.example.test"},body:JSON.stringify({...base,dependenciesResolved:true})}),context)).status).toBe(400);expect(open).not.toHaveBeenCalled();
  });
  it.each([true,false])("should bind suspension snapshot to the original cause/resource/CAS for changed %s and keep it no-store",async(changed)=>{
    const connectionId=randomUUID(),tribeId=randomUUID(),operationId=randomUUID(),result={id:connectionId,version:changed?4:3,state:"suspended" as const,reason:"security_stop" as const,changed},suspend=vi.fn<MessagingConnectionLifecycleServices["lifecycle"]["suspend"]>(async()=>({ok:true,value:{state:"completed",operationId,replayed:false,result}})),disconnect=vi.fn<MessagingConnectionLifecycleServices["lifecycle"]["disconnect"]>(),handlers=createMessagingConnectionLifecycleHandlers(async()=>({lifecycle:{suspend,disconnect},resolveTribe:{execute:async()=>({ok:true,value:{tribeId}})}})),context={params:Promise.resolve({slug:"synthetic",connectionId})},request=()=>new Request(`https://tutribu.example.test/api/tribes/synthetic/messaging/connections/${connectionId}/suspend`,{method:"POST",headers:{origin:"https://tutribu.example.test","content-type":"application/json"},body:JSON.stringify({operationId,confirmed:true,expectedVersion:3,reason:"security_stop"})});
    const response=await handlers.suspend(request(),context);expect(response.status).toBe(200);expect(response.headers.get("cache-control")).toContain("no-store");expect(await response.json()).toEqual({state:"completed",operationId,replayed:false,result});expect(suspend).toHaveBeenCalledWith(expect.objectContaining({tribeId,connectionId,operationId,expectedVersion:3,reason:"security_stop"}));expect(disconnect).not.toHaveBeenCalled();
    suspend.mockResolvedValueOnce({ok:true,value:{state:"completed",operationId,replayed:false,result:{...result,reason:"suspected_compromise"}}});expect((await handlers.suspend(request(),context)).status).toBe(500);
  });
  it("should return genuine original disconnection progress and reject crossed snapshots or origins",async()=>{
    const connectionId=randomUUID(),tribeId=randomUUID(),operationId=randomUUID(),suspend=vi.fn<MessagingConnectionLifecycleServices["lifecycle"]["suspend"]>(),disconnect=vi.fn<MessagingConnectionLifecycleServices["lifecycle"]["disconnect"]>(async()=>({ok:true,value:{state:"started",operationId}})),handlers=createMessagingConnectionLifecycleHandlers(async()=>({lifecycle:{suspend,disconnect},resolveTribe:{execute:async()=>({ok:true,value:{tribeId}})}})),context={params:Promise.resolve({slug:"synthetic",connectionId})},request=(origin="https://tutribu.example.test")=>new Request(`https://tutribu.example.test/api/tribes/synthetic/messaging/connections/${connectionId}/disconnect`,{method:"POST",headers:{origin},body:JSON.stringify({operationId,confirmed:true,expectedVersion:3})});
    expect((await handlers.disconnect(request(),context)).status).toBe(202);disconnect.mockResolvedValueOnce({ok:true,value:{state:"started",operationId:randomUUID()}});expect((await handlers.disconnect(request(),context)).status).toBe(500);expect((await handlers.disconnect(request("https://foreign.example.test"),context)).status).toBe(403);expect(disconnect).toHaveBeenCalledTimes(2);expect(suspend).not.toHaveBeenCalled();
  });
});
