"use client";
/** Presents explicit candidate selection and visible prerequisites without session, persistence or provider ownership. @module messaging-connection-activation */
import {useId} from "react";
import {Button,Checkbox,Label} from "beez-ui";
import type {MessagingConfigurationConnection} from "@/src/modules/messaging/application/results/messaging-configuration-result";
import styles from "./styles.module.scss";

/** The route owns current authority, requirements, consent and original-operation coordination. */
export type MessagingConnectionActivationProps={candidate:MessagingConfigurationConnection;selected:MessagingConfigurationConnection|null;confirmed:boolean;busy:boolean;canActivate:boolean;requirements:readonly string[];onConfirm:(confirmed:boolean)=>void;onActivate:()=>void;onReauthenticate:()=>void};

/** @param props - Current own candidate/selection facts and explicit callbacks. @returns A controlled confirmation form; rendering never selects or sends. */
export function MessagingConnectionActivation(props:MessagingConnectionActivationProps){
  const fieldId=useId();
  return<section className={styles.MessagingConnectionActivation} aria-labelledby={`${fieldId}-title`}><h3 id={`${fieldId}-title`} className={styles.MessagingConnectionActivation__title}>Activar la candidata</h3><p className={styles.MessagingConnectionActivation__description}>{props.candidate.name} · Configuración {props.candidate.configurationVersion}</p>{props.selected&&<p className={styles.MessagingConnectionActivation__description}>La seleccionada {props.selected.name}, configuración {props.selected.configurationVersion}, seguirá vigente hasta confirmar el reemplazo.</p>}<p className={styles.MessagingConnectionActivation__description}>La activación selecciona la candidata comprobada para la mensajería de la academia. Los códigos de admisión y los avisos por correo conservan sus ajustes; activar la conexión no los enciende automáticamente.</p><p className={styles.MessagingConnectionActivation__description}>Requiere una cuenta de producción y pruebas recibidas de los canales necesarios, para esta configuración, dentro de las últimas 24 horas. La confirmación vuelve a comprobar los requisitos actuales.</p>{props.requirements.length>0&&<ul className={styles.MessagingConnectionActivation__requirements} aria-label="Requisitos para activar">{props.requirements.map((requirement)=><li key={requirement}>{requirement}</li>)}</ul>}<form className={styles.MessagingConnectionActivation__form} aria-busy={props.busy} onSubmit={(event)=>{event.preventDefault();props.onActivate();}}><div className={styles.MessagingConnectionActivation__confirmation}><Checkbox id={`${fieldId}-consent`} checked={props.confirmed} disabled={props.busy} onCheckedChange={(checked)=>props.onConfirm(checked===true)} /><Label htmlFor={`${fieldId}-consent`}>Confirmo que quiero usar esta candidata y reemplazar la conexión seleccionada cuando corresponda.</Label></div><div className={styles.MessagingConnectionActivation__actions}><Button className={styles.MessagingConnectionActivation__button} type="button" variant="outline" disabled={props.busy} onClick={props.onReauthenticate}>Confirmar activación con Google</Button><Button className={styles.MessagingConnectionActivation__button} type="submit" disabled={props.busy||!props.canActivate}>{props.selected?"Reemplazar conexión seleccionada":"Activar candidata"}</Button></div></form></section>;
}
