/** Own HTTP mapping of semantic failures; upstream statuses are never copied blindly. */
import { HTTP_STATUS } from "@/src/constants/http-status";
import { ADMISSION_ERROR_CODE } from "@/src/modules/academy-admissions/constants/admission-errors";

export const ADMISSION_ERROR_HTTP_STATUS = {
  [ADMISSION_ERROR_CODE.invalidInput]: HTTP_STATUS.badRequest,
  [ADMISSION_ERROR_CODE.authenticationRequired]: HTTP_STATUS.unauthorized,
  [ADMISSION_ERROR_CODE.permissionDenied]: HTTP_STATUS.forbidden,
  [ADMISSION_ERROR_CODE.resourceUnavailable]: HTTP_STATUS.notFound,
  [ADMISSION_ERROR_CODE.invitationUnavailable]: HTTP_STATUS.notFound,
  [ADMISSION_ERROR_CODE.policyConflict]: HTTP_STATUS.conflict,
  [ADMISSION_ERROR_CODE.requestConflict]: HTTP_STATUS.conflict,
  [ADMISSION_ERROR_CODE.idempotencyConflict]: HTTP_STATUS.conflict,
  [ADMISSION_ERROR_CODE.allowlistConflict]: HTTP_STATUS.conflict,
  [ADMISSION_ERROR_CODE.allowlistImportConflict]: HTTP_STATUS.conflict,
  [ADMISSION_ERROR_CODE.invitationConflict]: HTTP_STATUS.conflict,
  [ADMISSION_ERROR_CODE.usagePolicyConflict]: HTTP_STATUS.conflict,
  [ADMISSION_ERROR_CODE.connectionConflict]: HTTP_STATUS.conflict,
  [ADMISSION_ERROR_CODE.recipientNotAllowed]: HTTP_STATUS.unprocessableEntity,
  [ADMISSION_ERROR_CODE.contactEvidenceRequired]: HTTP_STATUS.conflict,
  [ADMISSION_ERROR_CODE.additionalVerificationRequired]: HTTP_STATUS.conflict,
  [ADMISSION_ERROR_CODE.contactBindingConflict]: HTTP_STATUS.conflict,
  [ADMISSION_ERROR_CODE.challengeExpired]: HTTP_STATUS.conflict,
  [ADMISSION_ERROR_CODE.challengeInvalidated]: HTTP_STATUS.conflict,
  [ADMISSION_ERROR_CODE.proofUnavailable]: HTTP_STATUS.conflict,
  [ADMISSION_ERROR_CODE.verificationAttemptsExceeded]: HTTP_STATUS.tooManyRequests,
  [ADMISSION_ERROR_CODE.usageLimitReached]: HTTP_STATUS.tooManyRequests,
  [ADMISSION_ERROR_CODE.verificationCodeIncorrect]: HTTP_STATUS.unprocessableEntity,
  [ADMISSION_ERROR_CODE.reauthenticationRequired]: HTTP_STATUS.unauthorized,
  [ADMISSION_ERROR_CODE.admissionsPaused]: HTTP_STATUS.forbidden,
  [ADMISSION_ERROR_CODE.admissionIneligible]: HTTP_STATUS.conflict,
  [ADMISSION_ERROR_CODE.membershipRecoveryRequired]: HTTP_STATUS.conflict,
  [ADMISSION_ERROR_CODE.connectionIncomplete]: HTTP_STATUS.conflict,
  [ADMISSION_ERROR_CODE.missingCapability]: HTTP_STATUS.conflict,
  [ADMISSION_ERROR_CODE.invalidCredentials]: HTTP_STATUS.conflict,
  [ADMISSION_ERROR_CODE.upstreamRejected]: HTTP_STATUS.unprocessableEntity,
  [ADMISSION_ERROR_CODE.providerRateLimited]: HTTP_STATUS.tooManyRequests,
  [ADMISSION_ERROR_CODE.transportTimeout]: HTTP_STATUS.serviceUnavailable,
  [ADMISSION_ERROR_CODE.dependencyUnavailable]: HTTP_STATUS.serviceUnavailable,
  [ADMISSION_ERROR_CODE.deliveryUnknown]: HTTP_STATUS.serviceUnavailable,
  [ADMISSION_ERROR_CODE.operationUnresolved]: HTTP_STATUS.accepted,
  [ADMISSION_ERROR_CODE.upstreamPayloadUnusable]: HTTP_STATUS.badGateway,
  [ADMISSION_ERROR_CODE.publicContractUnusable]: HTTP_STATUS.serverError,
  [ADMISSION_ERROR_CODE.unexpectedFailure]: HTTP_STATUS.serverError,
} as const;
