"use client";
/** Presents explicit scoped diagnostic input and safe issued metadata without session, HTTP, provider or polling ownership. @module messaging-connection-diagnostic */
import {useId} from "react";
import {Button,Checkbox,Input,Label,Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "beez-ui";
import {Link} from "@/components/navigation/link";
import type {ConnectionDiagnosticIssueResult} from "@/src/modules/messaging/domain/repositories/connection-diagnostic-issuance";
import type {MessagingUsagePolicyStateDto} from "@/src/modules/messaging/application/results/messaging-public-result-schemas";
import type {z} from "zod";
import type {messageDeliverySchema} from "@/src/modules/messaging/application/results/messaging-flow-result-schemas";
import {MESSAGING_PUBLIC_CHANNEL} from "@/src/modules/messaging/constants/messaging-public-contract";
import {MESSAGING_DELIVERY_STATE_LABEL} from "@/src/modules/messaging/constants/messaging-diagnostic-browser";
import {MESSAGING_CHANNEL_LABEL} from "@/src/modules/messaging/constants/messaging-connection-presentation";
import styles from "./styles.module.scss";

/** Controlled destination/code never belong in durable browser metadata; the route owns authority and lifecycle. */
export type MessagingConnectionDiagnosticProps={channel:typeof MESSAGING_PUBLIC_CHANNEL[keyof typeof MESSAGING_PUBLIC_CHANNEL];recipient:string;country:string;verificationCode:string;confirmed:boolean;busy:boolean;canIssue:boolean;canVerify:boolean;canResend?:boolean;expiresInSeconds?:number|null;resendInSeconds?:number|null;allowedCountries:readonly string[];usage:MessagingUsagePolicyStateDto;diagnostic:Extract<ConnectionDiagnosticIssueResult,{outcome:"issued"}>|null;delivery:z.infer<typeof messageDeliverySchema>|null;message:{kind:"status"|"alert";text:string}|null;fieldErrors:Partial<Record<"recipient"|"country"|"verificationCode",string>>;usageHref?:string;onChannelChange:(channel:MessagingConnectionDiagnosticProps["channel"])=>void;onRecipientChange:(value:string)=>void;onCountryChange:(value:string)=>void;onCodeChange:(value:string)=>void;onConfirm:(confirmed:boolean)=>void;onIssue:()=>void;onResend:()=>void;onVerify:()=>void;onReadDelivery:()=>void;onIssueReauthenticate:()=>void;onVerifyReauthenticate:()=>void};

/** @param props - Own controlled form and readonly current metadata. @returns Explicit sending/verification actions; render and field changes never issue a message. */
export function MessagingConnectionDiagnostic(props:MessagingConnectionDiagnosticProps){
  const fieldId=useId(),phone=props.channel!==MESSAGING_PUBLIC_CHANNEL.email,phoneBlocked=phone&&props.allowedCountries.length===0;
  return<section className={styles.MessagingConnectionDiagnostic} aria-labelledby={`${fieldId}-title`}>
    <h3 id={`${fieldId}-title`} className={styles.MessagingConnectionDiagnostic__title}>Probar el canal de la candidata</h3>
    <p className={styles.MessagingConnectionDiagnostic__explanation}>El envío de la prueba consume un código del cupo de la academia y puede generar un cargo en el proyecto de Zavu de esta conexión. Revisá el destino antes de confirmar. Guardar o comprobar la clave no envía esta prueba.</p>
    {props.usage.policy&&<p className={styles.MessagingConnectionDiagnostic__explanation}>{props.usage.policy.consumption.verificationToday} códigos consumidos hoy de un límite de {props.usage.policy.verificationDailyLimit}. El intento conserva su consumo aunque no se confirme la entrega.</p>}
    <form className={styles.MessagingConnectionDiagnostic__form} aria-busy={props.busy} onSubmit={(event)=>{event.preventDefault();props.onIssue();}}>
      <div className={styles.MessagingConnectionDiagnostic__field}><Label htmlFor={`${fieldId}-channel`}>Canal de la prueba</Label><Select value={props.channel} disabled={props.busy} onValueChange={(value)=>{const channel=Object.values(MESSAGING_PUBLIC_CHANNEL).find((candidate)=>candidate===value);if(channel)props.onChannelChange(channel);}}><SelectTrigger id={`${fieldId}-channel`}><SelectValue /></SelectTrigger><SelectContent>{Object.values(MESSAGING_PUBLIC_CHANNEL).map((channel)=><SelectItem key={channel} value={channel}>{MESSAGING_CHANNEL_LABEL[channel]}</SelectItem>)}</SelectContent></Select></div>
      {phone&&<div className={styles.MessagingConnectionDiagnostic__field}><Label htmlFor={`${fieldId}-country`}>País guardado del teléfono</Label><Select value={props.country} disabled={props.busy||phoneBlocked} onValueChange={props.onCountryChange}><SelectTrigger id={`${fieldId}-country`} aria-invalid={Boolean(props.fieldErrors.country)} aria-describedby={props.fieldErrors.country?`${fieldId}-country-error`:undefined}><SelectValue placeholder="Elegí un país guardado" /></SelectTrigger><SelectContent>{props.allowedCountries.map((country)=><SelectItem key={country} value={country}>{country}</SelectItem>)}</SelectContent></Select>{props.fieldErrors.country&&<p id={`${fieldId}-country-error`} className={styles.MessagingConnectionDiagnostic__error}>{props.fieldErrors.country}</p>}{phoneBlocked&&<p className={styles.MessagingConnectionDiagnostic__error}>Guardá los países de mensajería antes de solicitar una prueba telefónica.{props.usageHref&&<> <Link href={props.usageHref}>Preparar países y cupos</Link></>}</p>}</div>}
      <div className={styles.MessagingConnectionDiagnostic__field}><Label htmlFor={`${fieldId}-recipient`}>Destino de la prueba</Label><Input id={`${fieldId}-recipient`} type={phone?"tel":"email"} autoComplete="off" value={props.recipient} disabled={props.busy} onChange={(event)=>props.onRecipientChange(event.target.value)} aria-invalid={Boolean(props.fieldErrors.recipient)} aria-describedby={props.fieldErrors.recipient?`${fieldId}-recipient-error`:undefined} />{props.fieldErrors.recipient&&<p id={`${fieldId}-recipient-error`} className={styles.MessagingConnectionDiagnostic__error}>{props.fieldErrors.recipient}</p>}</div>
      <div className={styles.MessagingConnectionDiagnostic__confirmation}><Checkbox id={`${fieldId}-consent`} checked={props.confirmed} disabled={props.busy} onCheckedChange={(checked)=>props.onConfirm(checked===true)} /><Label htmlFor={`${fieldId}-consent`}>Confirmo el destino y el consumo para enviar un código de prueba.</Label></div>
      <div className={styles.MessagingConnectionDiagnostic__actions}><Button className={styles.MessagingConnectionDiagnostic__action} type="button" variant="outline" disabled={props.busy} onClick={props.onIssueReauthenticate}>Confirmar prueba con Google</Button><Button className={styles.MessagingConnectionDiagnostic__action} type="submit" disabled={props.busy||phoneBlocked||!props.canIssue}>Enviar código de prueba</Button></div>
    </form>
    {props.message&&<p className={styles.MessagingConnectionDiagnostic__feedback} role={props.message.kind}>{props.message.text}</p>}
    {props.diagnostic&&<section className={styles.MessagingConnectionDiagnostic__result} aria-label="Código de prueba emitido"><p className={styles.MessagingConnectionDiagnostic__explanation}>La prueba corresponde a la configuración {props.diagnostic.connectionVersion} y al destino {props.diagnostic.maskedDestination}.</p>{props.expiresInSeconds!==undefined&&props.expiresInSeconds!==null&&<p className={styles.MessagingConnectionDiagnostic__explanation}>{props.expiresInSeconds>0?`El código vence en ${props.expiresInSeconds} segundos.`:"El código de esta prueba venció."}</p>}{props.resendInSeconds!==undefined&&props.resendInSeconds!==null&&props.resendInSeconds>0&&<p className={styles.MessagingConnectionDiagnostic__explanation}>Podés reenviar después de {props.resendInSeconds} segundos, con destino y consumo confirmados otra vez.</p>}<p className={styles.MessagingConnectionDiagnostic__explanation}>La entrega no confirma que recibiste el código. Introducí el código recibido para probar este canal; no verifica una admisión ni inicia sesión.</p>{props.delivery&&<p role="status" className={styles.MessagingConnectionDiagnostic__explanation}>{MESSAGING_DELIVERY_STATE_LABEL[props.delivery.state]}</p>}<Button className={styles.MessagingConnectionDiagnostic__action} type="button" variant="outline" disabled={props.busy} onClick={props.onReadDelivery}>Consultar entrega de la prueba</Button><form className={styles.MessagingConnectionDiagnostic__form} onSubmit={(event)=>{event.preventDefault();props.onVerify();}}><div className={styles.MessagingConnectionDiagnostic__field}><Label htmlFor={`${fieldId}-code`}>Código recibido</Label><Input id={`${fieldId}-code`} inputMode="numeric" autoComplete="one-time-code" value={props.verificationCode} disabled={props.busy} onChange={(event)=>props.onCodeChange(event.target.value)} aria-invalid={Boolean(props.fieldErrors.verificationCode)} aria-describedby={props.fieldErrors.verificationCode?`${fieldId}-code-error`:undefined} />{props.fieldErrors.verificationCode&&<p id={`${fieldId}-code-error`} className={styles.MessagingConnectionDiagnostic__error}>{props.fieldErrors.verificationCode}</p>}</div><div className={styles.MessagingConnectionDiagnostic__actions}><Button className={styles.MessagingConnectionDiagnostic__action} type="button" variant="outline" disabled={props.busy} onClick={props.onVerifyReauthenticate}>Confirmar verificación con Google</Button><Button className={styles.MessagingConnectionDiagnostic__action} type="submit" disabled={props.busy||!props.canVerify}>Confirmar código recibido</Button></div></form><Button className={styles.MessagingConnectionDiagnostic__action} type="button" variant="outline" disabled={props.busy||!props.canResend} onClick={props.onResend}>Reenviar código de prueba</Button></section>}
  </section>;
}
